import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [("users", "0004_alter_institution_institution_type_and_more"), ("academic", "0006_content_review_fields"), ("content_processing", "0004_academic_proposals_and_population")]
    operations = [
        migrations.CreateModel(name="RetrievalChunkCollection", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("population_version", models.CharField(max_length=64)), ("chunk_policy_version", models.CharField(max_length=64)), ("retrieval_version", models.CharField(max_length=64)), ("embedding_version", models.CharField(max_length=128)), ("chunk_count", models.PositiveIntegerField(default=0)), ("readiness", models.CharField(choices=[("not_indexed", "Not Indexed"), ("indexing", "Indexing"), ("indexed", "Indexed"), ("stale", "Stale"), ("failed", "Failed")], default="not_indexed", max_length=24)), ("checksum", models.CharField(max_length=128)), ("created_at", models.DateTimeField(auto_now_add=True)), ("completed_at", models.DateTimeField(blank=True, null=True)),
            ("population_job", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="retrieval_collections", to="content_processing.academicpopulationjob")), ("proposal", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="retrieval_collections", to="content_processing.academicimportproposal")), ("resource", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="retrieval_collections", to="academic.learningresource")),
        ], options={"db_table": "retrieval_chunk_collection"}),
        migrations.CreateModel(name="RetrievalIndexJob", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("retrieval_version", models.CharField(max_length=64)), ("embedding_version", models.CharField(max_length=128)), ("status", models.CharField(choices=[("not_indexed", "Not Indexed"), ("indexing", "Indexing"), ("indexed", "Indexed"), ("stale", "Stale"), ("failed", "Failed")], default="not_indexed", max_length=24)), ("chunk_count", models.PositiveIntegerField(default=0)), ("indexed_count", models.PositiveIntegerField(default=0)), ("warnings", models.JSONField(blank=True, default=list)), ("statistics", models.JSONField(blank=True, default=dict)), ("diagnostics", models.JSONField(blank=True, default=list)), ("failure_code", models.CharField(blank=True, max_length=128)), ("checksum", models.CharField(blank=True, max_length=128)), ("started_at", models.DateTimeField(blank=True, null=True)), ("completed_at", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)),
            ("collection", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="index_jobs", to="retrieval.retrievalchunkcollection")), ("population_job", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="retrieval_index_jobs", to="content_processing.academicpopulationjob")),
        ], options={"db_table": "retrieval_index_job"}),
        migrations.CreateModel(name="GroundingPackage", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("query_text", models.TextField()), ("retrieved_chunk_ids", models.JSONField(default=list)), ("confidence_scores", models.JSONField(default=list)), ("ranking_metadata", models.JSONField(default=dict)), ("retrieval_rationale", models.TextField(blank=True)), ("metadata_filters", models.JSONField(default=dict)), ("proposal_versions", models.JSONField(default=list)), ("population_versions", models.JSONField(default=list)), ("token_budget_summary", models.JSONField(default=dict)), ("retrieval_statistics", models.JSONField(default=dict)), ("diagnostics", models.JSONField(default=list)), ("checksum", models.CharField(max_length=128, unique=True)), ("created_at", models.DateTimeField(auto_now_add=True)),
        ], options={"db_table": "retrieval_grounding_package"}),
        migrations.CreateModel(name="RetrievalChunk", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("identity_key", models.CharField(max_length=128, unique=True)), ("proposal_version", models.CharField(max_length=64)), ("population_version", models.CharField(max_length=64)), ("chunk_policy_version", models.CharField(max_length=64)), ("retrieval_version", models.CharField(max_length=64)), ("embedding_version", models.CharField(max_length=128)), ("text", models.TextField()), ("chunk_type", models.CharField(max_length=32)), ("ordering", models.PositiveIntegerField()), ("source_page_start", models.PositiveIntegerField()), ("source_page_end", models.PositiveIntegerField()), ("token_estimate", models.PositiveIntegerField()), ("confidence", models.FloatField(default=0)), ("checksum", models.CharField(max_length=128)), ("embedding", models.JSONField(blank=True, default=list)), ("metadata", models.JSONField(blank=True, default=dict)), ("created_at", models.DateTimeField(auto_now_add=True)),
            ("collection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chunks", to="retrieval.retrievalchunkcollection")), ("concept", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="retrieval_chunks", to="academic.contentconcept")), ("institution", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="retrieval_chunks", to="users.institution")), ("population_job", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="retrieval_chunks", to="content_processing.academicpopulationjob")), ("proposal", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="retrieval_chunks", to="content_processing.academicimportproposal")), ("resource", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="retrieval_chunks", to="academic.learningresource")), ("section", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="retrieval_chunks", to="academic.contentsection")), ("semantic_segment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="retrieval_chunks", to="content_processing.semanticsegment")), ("subject", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="retrieval_chunks", to="academic.subject")),
        ], options={"db_table": "retrieval_chunk", "ordering": ["ordering"]}),
        migrations.CreateModel(name="GroundingCitation", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("source_page_start", models.PositiveIntegerField()), ("source_page_end", models.PositiveIntegerField()), ("rank", models.PositiveIntegerField()), ("score", models.FloatField()),
            ("chunk", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="grounding_citations", to="retrieval.retrievalchunk")), ("concept", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="academic.contentconcept")), ("institution", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="users.institution")), ("package", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="citations", to="retrieval.groundingpackage")), ("population_job", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="content_processing.academicpopulationjob")), ("proposal", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="content_processing.academicimportproposal")), ("resource", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="academic.learningresource")), ("section", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="academic.contentsection")), ("semantic_segment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="content_processing.semanticsegment")), ("subject", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="academic.subject")),
        ], options={"db_table": "retrieval_grounding_citation"}),
        migrations.AddConstraint(model_name="retrievalchunkcollection", constraint=models.UniqueConstraint(fields=("population_job", "population_version", "chunk_policy_version", "retrieval_version", "embedding_version"), name="retrieval_collection_identity")),
        migrations.AddConstraint(model_name="retrievalindexjob", constraint=models.UniqueConstraint(fields=("population_job", "retrieval_version", "embedding_version"), name="retrieval_index_job_identity")),
        migrations.AddConstraint(model_name="retrievalchunk", constraint=models.UniqueConstraint(fields=("collection", "ordering"), name="retrieval_chunk_order_unique")),
        migrations.AddConstraint(model_name="retrievalchunk", constraint=models.CheckConstraint(condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)), name="retrieval_chunk_confidence_range")),
        migrations.AddConstraint(model_name="retrievalchunk", constraint=models.CheckConstraint(condition=models.Q(("source_page_end__gte", models.F("source_page_start"))), name="retrieval_chunk_page_range")),
        migrations.AddIndex(model_name="retrievalchunk", index=models.Index(fields=["institution", "subject", "resource"], name="retrieval_academic_idx")),
        migrations.AddIndex(model_name="retrievalchunk", index=models.Index(fields=["section", "concept"], name="retrieval_content_idx")),
        migrations.AddConstraint(model_name="groundingcitation", constraint=models.UniqueConstraint(fields=("package", "chunk"), name="retrieval_citation_unique")),
        migrations.CreateModel(name="RetrievalStatistic", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("chunk_count", models.PositiveIntegerField(default=0)), ("indexed_count", models.PositiveIntegerField(default=0)), ("embedding_batch_count", models.PositiveIntegerField(default=0)), ("ranking_policy_version", models.CharField(max_length=64)), ("values", models.JSONField(blank=True, default=dict)), ("created_at", models.DateTimeField(auto_now_add=True)),
            ("collection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="statistic_records", to="retrieval.retrievalchunkcollection")), ("index_job", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="statistic_record", to="retrieval.retrievalindexjob")),
        ], options={"db_table": "retrieval_statistic"}),
        migrations.CreateModel(name="RetrievalDiagnostic", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("severity", models.CharField(max_length=16)), ("code", models.CharField(max_length=128)), ("message", models.TextField()), ("details", models.JSONField(blank=True, default=dict)), ("created_at", models.DateTimeField(auto_now_add=True)),
            ("grounding_package", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="diagnostic_records", to="retrieval.groundingpackage")), ("index_job", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="diagnostic_records", to="retrieval.retrievalindexjob")),
        ], options={"db_table": "retrieval_diagnostic"}),
    ]
