from __future__ import annotations

from typing import Protocol

from apps.assessment_review.domain.models import (
    AssessmentReview,
    DifficultyCalibration,
    QualityFinding,
    QuestionReview,
    ReviewDecision,
    ReviewerAssignment,
)
from apps.assessments.domain.models import Assessment, ItemBankEntry
from apps.users.domain.models import User


class AssessmentReviewRepository(Protocol):
    def add(self, review: AssessmentReview) -> AssessmentReview: ...
    def save(self, review: AssessmentReview) -> AssessmentReview: ...
    def get(self, review_id: str) -> AssessmentReview: ...
    def get_for_assessment(self, assessment: Assessment) -> AssessmentReview | None: ...
    def list_pending(self) -> list[AssessmentReview]: ...
    def list_for_assessment(self, assessment: Assessment) -> list[AssessmentReview]: ...
    def list_for_reviewer(self, reviewer: User) -> list[AssessmentReview]: ...


class QuestionReviewRepository(Protocol):
    def add(self, review: QuestionReview) -> QuestionReview: ...
    def save(self, review: QuestionReview) -> QuestionReview: ...
    def get(self, review_id: str) -> QuestionReview: ...
    def get_for_item(self, item_bank_entry: ItemBankEntry) -> QuestionReview | None: ...
    def list_pending(self) -> list[QuestionReview]: ...
    def list_for_item(self, item_bank_entry: ItemBankEntry) -> list[QuestionReview]: ...
    def list_for_reviewer(self, reviewer: User) -> list[QuestionReview]: ...


class QualityFindingRepository(Protocol):
    def add(self, finding: QualityFinding) -> QualityFinding: ...
    def save(self, finding: QualityFinding) -> QualityFinding: ...
    def list_for_assessment_review(self, review: AssessmentReview) -> list[QualityFinding]: ...
    def list_for_question_review(self, review: QuestionReview) -> list[QualityFinding]: ...


class ReviewDecisionRepository(Protocol):
    def add(self, decision: ReviewDecision) -> ReviewDecision: ...
    def list_for_assessment_review(self, review: AssessmentReview) -> list[ReviewDecision]: ...
    def list_for_question_review(self, review: QuestionReview) -> list[ReviewDecision]: ...


class CalibrationRepository(Protocol):
    def add(self, calibration: DifficultyCalibration) -> DifficultyCalibration: ...
    def list_for_assessment(self, assessment: Assessment) -> list[DifficultyCalibration]: ...
    def list_for_item(self, item_bank_entry: ItemBankEntry) -> list[DifficultyCalibration]: ...
    def list_recent(self, limit: int = 100) -> list[DifficultyCalibration]: ...


class ReviewerAssignmentRepository(Protocol):
    def add(self, assignment: ReviewerAssignment) -> ReviewerAssignment: ...
    def save(self, assignment: ReviewerAssignment) -> ReviewerAssignment: ...
    def list_for_reviewer(self, reviewer: User) -> list[ReviewerAssignment]: ...
    def list_active_for_reviewer(self, reviewer: User) -> list[ReviewerAssignment]: ...
    def list_for_assessment_review(self, review: AssessmentReview) -> list[ReviewerAssignment]: ...
    def list_for_question_review(self, review: QuestionReview) -> list[ReviewerAssignment]: ...


__all__ = [
    "AssessmentReviewRepository",
    "QuestionReviewRepository",
    "QualityFindingRepository",
    "ReviewDecisionRepository",
    "CalibrationRepository",
    "ReviewerAssignmentRepository",
]
