"use client";

import { useEffect, useMemo, useState } from "react";
import { ErrorState, LoadingState } from "@/components/feedback";
import { useAuth } from "@/features/auth/AuthProvider";
import { approveReview, bulkReview, decideItem, editItem, evaluateApprovalReadiness, getApprovedProjection, getEvidence, getPopulationReadiness, getReview, listFindings, listOutline, populateApprovedProjection, rejectReview, requestReprocessing, resolveFinding, startReview, submitReview, type ApprovedProjection, type PopulationReadiness, type PopulationResult, type ReviewEvidence, type ReviewFinding, type ReviewItem, type ReviewSession } from "@/services/academic-review";

const panel = "rounded-[var(--radius-lg)] border border-[var(--color-border)] bg-[var(--color-background)] p-5";
const bulkPolicies = [
  ["reject_toc", "Reject TOC-derived items"], ["reject_front_matter", "Reject front matter"], ["reject_page_markers", "Reject page markers"],
  ["reject_heading_only_concepts", "Reject heading-only concepts"], ["reject_synthetic_navigation", "Reject synthetic navigation"],
] as const;

export function AcademicReviewWorkspace({ proposalId }: { proposalId: string }) {
  const { user } = useAuth();
  const [session, setSession] = useState<ReviewSession | null>(null); const [items, setItems] = useState<ReviewItem[]>([]);
  const [findings, setFindings] = useState<ReviewFinding[]>([]); const [selected, setSelected] = useState<ReviewItem | null>(null);
  const [evidence, setEvidence] = useState<ReviewEvidence[]>([]); const [search, setSearch] = useState(""); const [filter, setFilter] = useState("all");
  const [itemCount, setItemCount] = useState(0);
  const [preview, setPreview] = useState<{ policy: string; count: number } | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const [projection, setProjection] = useState<ApprovedProjection | null>(null); const [populationReadiness, setPopulationReadiness] = useState<PopulationReadiness | null>(null);
  const [populationResult, setPopulationResult] = useState<PopulationResult | null>(null); const [populating, setPopulating] = useState(false); const [populationKey, setPopulationKey] = useState<string | null>(null);
  const roles = new Set(user?.institutions?.map((item) => item.role) ?? []); const canApprove = Boolean(user?.is_superuser || user?.is_staff || roles.has("administrator") || roles.has("institution_owner") || roles.has("system_administrator"));

  async function refresh(active = session) {
    if (!active) return;
    const [nextSession, outline, nextFindings] = await Promise.all([getReview(active.id), listOutline(active.id, search), listFindings(active.id)]);
    setSession(nextSession); setItems(outline.results); setItemCount(outline.count); setFindings(nextFindings);
  }
  useEffect(() => { let mounted = true; (async () => { try { const active = await startReview(proposalId); if (!mounted) return; setSession(active); const [outline, nextFindings] = await Promise.all([listOutline(active.id), listFindings(active.id)]); if (active.approved_projection_id) { const approved = await getApprovedProjection(active.approved_projection_id); if (approved && mounted) { setProjection(approved); setPopulationReadiness(await getPopulationReadiness(approved.id) ?? null); } } if (mounted) { setItems(outline.results); setItemCount(outline.count); setFindings(nextFindings); } } catch (cause) { if (mounted) setError(cause instanceof Error ? cause.message : "Unable to open academic review."); } finally { if (mounted) setLoading(false); } })(); return () => { mounted = false; }; }, [proposalId]);
  const visible = useMemo(() => items.filter((item) => filter === "all" || item.decision === filter), [filter, items]);
  async function choose(item: ReviewItem) { setSelected(item); setEvidence(session ? await getEvidence(session.id, item.id) : []); }
  async function loadMore() { if (!session) return; const page = await listOutline(session.id, search, items.length); setItems((current) => [...current, ...page.results]); setItemCount(page.count); }
  async function decide(decision: "accepted" | "rejected") { if (!session || !selected) return; await decideItem(session.id, selected.id, decision); await refresh(); setSelected({ ...selected, decision }); }
  async function rename() { if (!session || !selected) return; const title = window.prompt("Reviewed title", selected.edit?.title || selected.title); if (!title) return; await editItem(session.id, selected.id, { title, reason: "Reviewer title correction" }); await refresh(); }
  async function reorder() { if (!session || !selected) return; const raw = window.prompt("New position"); const ordering = Number(raw); if (!Number.isInteger(ordering) || ordering < 1) return; await editItem(session.id, selected.id, { ordering, reason: "Reviewer ordering correction" }); await refresh(); }
  async function move() { if (!session || !selected) return; const sections = items.filter((item) => item.item_type === "section" && !["pending", "rejected"].includes(item.decision)); const target = window.prompt(`Accepted section ID (${sections.map((item) => `${item.item_id}: ${item.title}`).join(", ")})`); if (!target) return; await editItem(session.id, selected.id, selected.item_type === "concept" ? { target_section_id: target, reason: "Reviewer concept move" } : { parent_section_id: target, reason: "Reviewer parent change" }); await refresh(); }
  async function runBulk(policy: string) { if (!session) return; const result = await bulkReview(session.id, policy, true); setPreview({ policy, count: result?.affected_count ?? 0 }); }
  async function applyBulk() { if (!session || !preview) return; await bulkReview(session.id, preview.policy, false); setPreview(null); await refresh(); }
  async function submit() { if (!session) return; const next = await submitReview(session.id); if (next) setSession(next); }
  async function approve() { if (!session) return; const snapshot = await evaluateApprovalReadiness(session.id, session.version); if (!snapshot?.ready) { setError(`Approval blocked: ${snapshot?.reasons.join(", ") || "readiness requirements were not met"}.`); return; } const approved = await approveReview(session.id, snapshot.id, session.version, crypto.randomUUID()); if (approved) { const nextProjection = await getApprovedProjection(approved.projection_id); if (nextProjection) { setProjection(nextProjection); setPopulationReadiness(await getPopulationReadiness(nextProjection.id) ?? null); } } await refresh(); }
  async function populate() { if (!projection || !populationReadiness?.ready || populating) return; if (!window.confirm("Create official Academic Platform sections and concepts from this immutable approved projection? Retrieval and teaching readiness remain separate later steps.")) return; const key = populationKey || crypto.randomUUID(); setPopulationKey(key); setPopulating(true); setError(null); try { const result = await populateApprovedProjection(projection.id, projection.checksum, key); if (result) { setPopulationResult(result); setPopulationReadiness(await getPopulationReadiness(projection.id) ?? null); } } catch (cause) { setError(cause instanceof Error ? cause.message : "Academic population failed."); } finally { setPopulating(false); } }
  async function reject() { if (!session) return; const reason = window.prompt("Why is this proposal rejected?"); if (!reason) return; await rejectReview(session.id, reason, session.version, crypto.randomUUID()); await refresh(); }
  async function resolve(finding: ReviewFinding, override = false) { if (!session) return; if (!override && !selected) return; const reason = window.prompt(override ? "Administrator override reason" : "Resolution note"); if (!reason) return; await resolveFinding(session.id, { validation_id: finding.id, resolution_type: override ? "override" : selected?.decision === "rejected" ? "rejection" : selected?.decision === "moved" ? "move" : "edit", item_decision_id: selected?.id, note: override ? "" : reason, override_reason: override ? reason : "" }); await refresh(); }
  async function reprocess() { if (!session) return; const reason = window.prompt("Why should this document be reprocessed?"); if (!reason) return; const next = await requestReprocessing(session.id, reason); if (next) setSession(next); }
  if (loading) return <LoadingState message="Opening academic proposal review..." />;
  if (error || !session) return <ErrorState title="Academic review unavailable" message={error || "No review session exists."} />;
  return <section className="space-y-6">
    <header className={panel}><p className="text-sm font-medium uppercase tracking-wide text-[var(--color-primary)]">Academic proposal review</p><h1 className="mt-2 text-3xl font-semibold">{session.resource.title}</h1><div className="mt-4 grid gap-3 text-sm sm:grid-cols-4"><span>Status: {session.status.replaceAll("_", " ")}</span><span>Confidence: {(session.confidence * 100).toFixed(1)}%</span><span>Pending: {session.summary.section_pending + session.summary.concept_pending}</span><span>Blocking findings: {session.summary.outstanding_findings}</span></div></header>
    <div className={`${panel} flex flex-wrap gap-3`} aria-label="Bulk review toolbar">{bulkPolicies.map(([code, label]) => <button className="rounded border px-3 py-2 text-sm" key={code} onClick={() => void runBulk(code)} type="button">{label}</button>)}{preview ? <div className="w-full rounded border border-[var(--color-warning)] p-3 text-sm">This policy will reject {preview.count} pending items. <button className="ml-3 font-semibold" onClick={() => void applyBulk()} type="button">Apply bulk rejection</button></div> : null}</div>
    <div className="grid gap-6 lg:grid-cols-[1.2fr,0.8fr]"><div className={panel}><div className="flex gap-3"><input aria-label="Search proposal" className="min-w-0 flex-1 rounded border px-3 py-2" onChange={(event) => setSearch(event.target.value)} value={search} /><button className="rounded border px-3" onClick={() => void refresh()} type="button">Search</button><select aria-label="Decision filter" className="rounded border px-3" onChange={(event) => setFilter(event.target.value)} value={filter}><option value="all">All</option><option value="pending">Pending</option><option value="accepted">Accepted</option><option value="rejected">Rejected</option><option value="edited">Edited</option></select></div><ul className="mt-4 space-y-2">{visible.map((item) => <li key={item.id}><button className="w-full rounded border p-3 text-left" onClick={() => void choose(item)} type="button"><span className="font-medium">{item.item_type === "section" ? "Section" : "Concept"}: {item.edit?.title || item.title}</span><span className="ml-3 text-xs uppercase">{item.decision}</span><span className="float-right text-xs">{(item.confidence * 100).toFixed(0)}%</span></button></li>)}</ul>{items.length < itemCount ? <button className="mt-4 rounded border px-4 py-2" onClick={() => void loadMore()} type="button">Load more proposal items</button> : null}</div>
      <aside className={`${panel} space-y-4`}><h2 className="text-xl font-semibold">Evidence and decision</h2>{selected ? <><h3 className="font-medium">{selected.title}</h3><div className="flex flex-wrap gap-2"><button className="rounded border px-3 py-2" onClick={() => void decide("accepted")} type="button">Accept</button><button className="rounded border px-3 py-2" onClick={() => void decide("rejected")} type="button">Reject</button><button className="rounded border px-3 py-2" onClick={() => void rename()} type="button">Rename</button><button className="rounded border px-3 py-2" onClick={() => void reorder()} type="button">Reorder</button><button className="rounded border px-3 py-2" onClick={() => void move()} type="button">{selected.item_type === "concept" ? "Move concept" : "Change parent"}</button></div>{evidence.map((row) => <article className="rounded border p-3 text-sm" key={row.id}><p>Pages {row.page_start ?? "?"}–{row.page_end ?? row.page_start ?? "?"} · {row.evidence_strength} · {(row.confidence * 100).toFixed(0)}%</p><p className="mt-2 text-[var(--color-muted-foreground)]">{row.supporting_text || row.hierarchy}</p></article>)}</> : <p className="text-sm text-[var(--color-muted-foreground)]">Select a section or concept to inspect its provenance.</p>}</aside></div>
    <section className={panel}><h2 className="text-xl font-semibold">Approval</h2><ul className="mt-3 space-y-2 text-sm">{findings.filter((finding) => !finding.passed).map((finding) => <li className="rounded border p-3" key={finding.id}><span>{finding.resolved ? "Resolved" : "Outstanding"}: {finding.message}</span>{!finding.resolved ? <span className="ml-3"><button className="font-medium" disabled={!selected} onClick={() => void resolve(finding)} type="button">Resolve with selected item</button>{canApprove ? <button className="ml-3 font-medium" onClick={() => void resolve(finding, true)} type="button">Override</button> : null}</span> : null}</li>)}</ul><div className="mt-4 flex flex-wrap gap-3"><button className="rounded border px-4 py-2" disabled={!session.summary.ready || session.status !== "in_progress"} onClick={() => void submit()} type="button">Submit for approval</button>{canApprove ? <button className="rounded border px-4 py-2" disabled={session.status !== "ready_for_approval"} onClick={() => void approve()} type="button">Approve and publish</button> : null}{canApprove ? <button className="rounded border px-4 py-2" onClick={() => void reject()} type="button">Reject proposal</button> : null}<button className="rounded border px-4 py-2" onClick={() => void reprocess()} type="button">Request reprocessing</button></div></section>
    {projection && populationReadiness ? <section className={panel}><h2 className="text-xl font-semibold">Academic Platform population</h2><p className="mt-2 text-sm">Status: {populationResult?.status ?? populationReadiness.status.replaceAll("_", " ")}. This creates official academic content; retrieval synchronization and teaching readiness are not included.</p><p className="mt-2 text-sm">Planned: {populationReadiness.expected_section_count} sections and {populationReadiness.expected_concept_count} concepts.</p>{populationReadiness.blockers.length ? <ul className="mt-3 text-sm">{populationReadiness.blockers.map((blocker) => <li key={blocker.code}>{blocker.code}: {blocker.message}</li>)}</ul> : null}{populationResult ? <p className="mt-3 text-sm">Created {populationResult.created_sections} sections and {populationResult.created_concepts} concepts; matched {populationResult.matched_sections} sections and {populationResult.matched_concepts} concepts.</p> : null}{canApprove && !populationResult ? <button className="mt-4 rounded border px-4 py-2" disabled={!populationReadiness.ready || populating} onClick={() => void populate()} type="button">{populating ? "Populating..." : "Populate Academic Platform"}</button> : null}</section> : null}
  </section>;
}
