from django.urls import path

from apps.study_lab.api.views import (
    StudyToolDetailView,
    StudyToolListView,
    StudyInstrumentAvailabilityView,
    StudyInstrumentDetailView,
    StudyInstrumentListView,
    StudyInstrumentCalculateView,
    StudyInstrumentConvertUnitView,
    StudyInstrumentGraphView,
    StudyWorkspaceToolLaunchView,
    StudyWorkspaceToolResumeView,
    StudyWorkspaceArtefactCompatibleToolsView,
    StudyWorkspaceArtefactDetailView,
    StudyWorkspaceArtefactExportView,
    StudyWorkspaceArtefactImportView,
    StudyWorkspaceArtefactLineageView,
    StudyWorkspaceArtefactListCreateView,
    StudyWorkspaceArtefactRevokeShareView,
    StudyWorkspaceArtefactShareView,
    StudyWorkspaceTransformationDetailView,
    StudyWorkspaceScaffoldGenerationDetailView,
    StudyWorkspaceScaffoldGenerationView,
    StudyWorkspaceTransformationRequestView,
    StudyWorkspaceActivityView,
    StudyWorkspaceAssemblyView,
    StudyWorkspaceContextView,
    StudyWorkspaceDetailView,
    StudyWorkspaceListCreateView,
    StudyWorkspaceNotesView,
    StudyWorkspaceNoteDetailView,
    StudyWorkspacePanelsView,
    StudyWorkspaceResumeStateView,
    StudyWorkspaceSnapshotView,
    StudyWorkspaceToolsView,
    StudyWorkspaceActionView,
)

app_name = "study_lab"

urlpatterns = [
    path("workspaces/", StudyWorkspaceListCreateView.as_view(), name="workspace-list-create"),
    path("workspaces/<uuid:workspace_id>/", StudyWorkspaceDetailView.as_view(), name="workspace-detail"),
    path("workspaces/<uuid:workspace_id>/context/", StudyWorkspaceContextView.as_view(), name="workspace-context"),
    path("workspaces/<uuid:workspace_id>/resume-state/", StudyWorkspaceResumeStateView.as_view(), name="workspace-resume-state"),
    path("workspaces/<uuid:workspace_id>/assembly/", StudyWorkspaceAssemblyView.as_view(), name="workspace-assembly"),
    path("workspaces/<uuid:workspace_id>/snapshot/", StudyWorkspaceSnapshotView.as_view(), name="workspace-snapshot"),
    path("workspaces/<uuid:workspace_id>/panels/", StudyWorkspacePanelsView.as_view(), name="workspace-panels"),
    path("workspaces/<uuid:workspace_id>/tools/", StudyWorkspaceToolsView.as_view(), name="workspace-tools"),
    path("workspaces/<uuid:workspace_id>/tools/<str:tool_key>/launch/", StudyWorkspaceToolLaunchView.as_view(), name="workspace-tool-launch"),
    path("workspaces/<uuid:workspace_id>/tools/<str:tool_key>/resume/", StudyWorkspaceToolResumeView.as_view(), name="workspace-tool-resume"),
    path("tools/", StudyToolListView.as_view(), name="tool-list"),
    path("tools/<str:tool_key>/", StudyToolDetailView.as_view(), name="tool-detail"),
    path("instruments/", StudyInstrumentListView.as_view(), name="instrument-list"),
    path("instruments/<str:tool_key>/", StudyInstrumentDetailView.as_view(), name="instrument-detail"),
    path("instruments/<str:tool_key>/availability/", StudyInstrumentAvailabilityView.as_view(), name="instrument-availability"),
    path("instruments/calculate/", StudyInstrumentCalculateView.as_view(), name="instrument-calculate"),
    path("instruments/convert-unit/", StudyInstrumentConvertUnitView.as_view(), name="instrument-convert-unit"),
    path("instruments/graph/", StudyInstrumentGraphView.as_view(), name="instrument-graph"),
    path("workspaces/<uuid:workspace_id>/notes/", StudyWorkspaceNotesView.as_view(), name="workspace-notes"),
    path("workspaces/<uuid:workspace_id>/notes/<uuid:note_id>/", StudyWorkspaceNoteDetailView.as_view(), name="workspace-note-detail"),
    path("workspaces/<uuid:workspace_id>/activity/", StudyWorkspaceActivityView.as_view(), name="workspace-activity"),
    path("workspaces/<uuid:workspace_id>/artefacts/", StudyWorkspaceArtefactListCreateView.as_view(), name="workspace-artefacts"),
    path("workspaces/<uuid:workspace_id>/artefacts/import/", StudyWorkspaceArtefactImportView.as_view(), name="workspace-artefact-import"),
    path("workspaces/<uuid:workspace_id>/artefacts/<uuid:artefact_id>/", StudyWorkspaceArtefactDetailView.as_view(), name="workspace-artefact-detail"),
    path("workspaces/<uuid:workspace_id>/artefacts/<uuid:artefact_id>/lineage/", StudyWorkspaceArtefactLineageView.as_view(), name="workspace-artefact-lineage"),
    path("workspaces/<uuid:workspace_id>/artefacts/<uuid:artefact_id>/compatible-tools/", StudyWorkspaceArtefactCompatibleToolsView.as_view(), name="workspace-artefact-compatible-tools"),
    path("workspaces/<uuid:workspace_id>/artefacts/<uuid:artefact_id>/export/", StudyWorkspaceArtefactExportView.as_view(), name="workspace-artefact-export"),
    path("workspaces/<uuid:workspace_id>/artefacts/<uuid:artefact_id>/share/", StudyWorkspaceArtefactShareView.as_view(), name="workspace-artefact-share"),
    path("workspaces/<uuid:workspace_id>/artefacts/<uuid:artefact_id>/revoke-share/", StudyWorkspaceArtefactRevokeShareView.as_view(), name="workspace-artefact-revoke-share"),
    path("workspaces/<uuid:workspace_id>/transformations/", StudyWorkspaceTransformationRequestView.as_view(), name="workspace-transformations"),
    path("workspaces/<uuid:workspace_id>/transformations/<uuid:request_id>/", StudyWorkspaceTransformationDetailView.as_view(), name="workspace-transformation-detail"),
    path("workspaces/<uuid:workspace_id>/scaffold-generation/", StudyWorkspaceScaffoldGenerationView.as_view(), name="workspace-scaffold-generation"),
    path("workspaces/<uuid:workspace_id>/scaffold-generation/<uuid:request_id>/", StudyWorkspaceScaffoldGenerationDetailView.as_view(), name="workspace-scaffold-generation-detail"),
    path("workspaces/<uuid:workspace_id>/<str:action>/", StudyWorkspaceActionView.as_view(), name="workspace-action"),
]
