from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyWorkspace",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("workspace_type", models.CharField(choices=[("SELF_STUDY", "Self-study"), ("INSTITUTIONAL", "Institutional"), ("HYBRID", "Hybrid"), ("PERSONAL_REVIEW", "Personal review")], default="SELF_STUDY", max_length=32)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("ACTIVE", "Active"), ("PAUSED", "Paused"), ("SUSPENDED", "Suspended"), ("COMPLETED", "Completed"), ("ARCHIVED", "Archived")], default="DRAFT", max_length=24)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("last_opened_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_study_lab_workspaces", to=settings.AUTH_USER_MODEL)),
                ("learner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="study_lab_workspaces", to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="study_lab_workspaces", to="users.institution")),
            ],
            options={"db_table": "study_lab_workspace", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="WorkspaceContext",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("active_learning_journey_id", models.UUIDField(blank=True, null=True)),
                ("active_institutional_journey_id", models.UUIDField(blank=True, null=True)),
                ("active_subject_id", models.UUIDField(blank=True, null=True)),
                ("active_course_id", models.UUIDField(blank=True, null=True)),
                ("active_programme_id", models.UUIDField(blank=True, null=True)),
                ("active_curriculum_reference_id", models.UUIDField(blank=True, null=True)),
                ("active_competency_id", models.UUIDField(blank=True, null=True)),
                ("active_concept_id", models.UUIDField(blank=True, null=True)),
                ("active_abbot_session_id", models.UUIDField(blank=True, null=True)),
                ("active_ariel_session_id", models.UUIDField(blank=True, null=True)),
                ("active_whiteboard_session_id", models.UUIDField(blank=True, null=True)),
                ("active_concept_check_id", models.UUIDField(blank=True, null=True)),
                ("source_versions", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("workspace", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="context", to="study_lab.studyworkspace")),
            ],
            options={"db_table": "study_lab_workspace_context"},
        ),
        migrations.AddField(
            model_name="studyworkspace",
            name="active_context",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="study_lab.workspacecontext"),
        ),
        migrations.CreateModel(
            name="WorkspaceResumeState",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("last_panel_key", models.CharField(choices=[("MENTOR", "Mentor"), ("WHITEBOARD", "Whiteboard"), ("RESOURCES", "Resources"), ("ARIEL", "Ariel"), ("CONCEPT_CHECK", "Concept Check"), ("PROGRESS", "Progress"), ("NOTES", "Notes"), ("JOURNEY", "Journey"), ("ACTIVITY", "Activity")], max_length=32)),
                ("last_tool_key", models.CharField(blank=True, choices=[("ABBOT_MENTOR", "Abbot Mentor"), ("ARIEL_TEACH", "Ariel Teach"), ("STRUCTURED_WHITEBOARD", "Structured Whiteboard"), ("RESOURCE_VIEWER", "Resource Viewer"), ("CONCEPT_CHECK", "Concept Check"), ("LEARNER_NOTES", "Learner Notes"), ("PROGRESS_VIEW", "Progress View"), ("JOURNEY_MAP", "Journey Map"), ("RESUME_SESSION", "Resume Session")], max_length=32, null=True)),
                ("last_activity_type", models.CharField(choices=[("WORKSPACE_CREATED", "Workspace created"), ("WORKSPACE_OPENED", "Workspace opened"), ("WORKSPACE_ACTIVATED", "Workspace activated"), ("WORKSPACE_PAUSED", "Workspace paused"), ("WORKSPACE_RESUMED", "Workspace resumed"), ("WORKSPACE_COMPLETED", "Workspace completed"), ("WORKSPACE_ARCHIVED", "Workspace archived"), ("SUBJECT_SELECTED", "Subject selected"), ("CONCEPT_SELECTED", "Concept selected"), ("PANEL_OPENED", "Panel opened"), ("TOOL_INVOKED", "Tool invoked"), ("RESOURCE_OPENED", "Resource opened"), ("ABBOT_SESSION_RESUMED", "Abbot session resumed"), ("ARIEL_SESSION_STARTED", "Ariel session started"), ("WHITEBOARD_RESUMED", "Whiteboard resumed"), ("CONCEPT_CHECK_STARTED", "Concept check started"), ("NOTE_CREATED", "Note created"), ("NOTE_UPDATED", "Note updated"), ("CONTEXT_CHANGED", "Context changed"), ("RESUME_POINT_UPDATED", "Resume point updated")], max_length=48)),
                ("last_subject_id", models.UUIDField(blank=True, null=True)),
                ("last_concept_id", models.UUIDField(blank=True, null=True)),
                ("last_session_reference", models.CharField(blank=True, max_length=128)),
                ("unfinished_activity_reference", models.CharField(blank=True, max_length=128)),
                ("whiteboard_reference", models.CharField(blank=True, max_length=128)),
                ("next_action_key", models.CharField(choices=[("CONTINUE_TEACHING", "Continue teaching"), ("REVIEW_CONCEPT", "Review concept"), ("TEACH_ARIEL", "Teach Ariel"), ("COMPLETE_CONCEPT_CHECK", "Complete concept check"), ("OPEN_RESOURCE", "Open resource"), ("RESUME_WHITEBOARD", "Resume whiteboard"), ("RETURN_TO_JOURNEY", "Return to journey"), ("START_NEXT_CONCEPT", "Start next concept"), ("WAIT_FOR_CONTENT_READINESS", "Wait for content readiness"), ("NO_RECOMMENDATION", "No recommendation")], default="NO_RECOMMENDATION", max_length=48)),
                ("next_action_reference", models.CharField(blank=True, max_length=128)),
                ("resume_reason", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("workspace", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="resume_state", to="study_lab.studyworkspace")),
            ],
            options={"db_table": "study_lab_resume_state"},
        ),
        migrations.CreateModel(
            name="WorkspacePanelDefinition",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("panel_key", models.CharField(choices=[("MENTOR", "Mentor"), ("WHITEBOARD", "Whiteboard"), ("RESOURCES", "Resources"), ("ARIEL", "Ariel"), ("CONCEPT_CHECK", "Concept Check"), ("PROGRESS", "Progress"), ("NOTES", "Notes"), ("JOURNEY", "Journey"), ("ACTIVITY", "Activity")], max_length=32, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("provider_context", models.CharField(choices=[("ABBOT", "Abbot"), ("ARIEL", "Ariel"), ("WHITEBOARD", "Whiteboard"), ("RESOURCE", "Resource"), ("CONCEPT_CHECK", "Concept Check"), ("PROGRESS", "Progress"), ("JOURNEY", "Journey"), ("STUDY_LAB", "Study Lab")], max_length=32)),
                ("required_capability", models.CharField(blank=True, max_length=64)),
                ("supported_workspace_types", models.JSONField(blank=True, default=list)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("SUSPENDED", "Suspended"), ("RETIRED", "Retired")], default="ACTIVE", max_length=24)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "study_lab_panel_definition", "ordering": ["sort_order", "panel_key"]},
        ),
        migrations.CreateModel(
            name="StudyToolDefinition",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tool_key", models.CharField(choices=[("ABBOT_MENTOR", "Abbot Mentor"), ("ARIEL_TEACH", "Ariel Teach"), ("STRUCTURED_WHITEBOARD", "Structured Whiteboard"), ("RESOURCE_VIEWER", "Resource Viewer"), ("CONCEPT_CHECK", "Concept Check"), ("LEARNER_NOTES", "Learner Notes"), ("PROGRESS_VIEW", "Progress View"), ("JOURNEY_MAP", "Journey Map"), ("RESUME_SESSION", "Resume Session")], max_length=32, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(choices=[("TEACHING", "Teaching"), ("LEARNING", "Learning"), ("REVIEW", "Review"), ("ORGANIZATION", "Organization"), ("ASSESSMENT", "Assessment")], max_length=32)),
                ("provider_context", models.CharField(choices=[("ABBOT", "Abbot"), ("ARIEL", "Ariel"), ("WHITEBOARD", "Whiteboard"), ("RESOURCE", "Resource"), ("CONCEPT_CHECK", "Concept Check"), ("PROGRESS", "Progress"), ("JOURNEY", "Journey"), ("STUDY_LAB", "Study Lab")], max_length=32)),
                ("required_capability", models.CharField(blank=True, max_length=64)),
                ("supported_workspace_types", models.JSONField(blank=True, default=list)),
                ("policy_key", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("SUSPENDED", "Suspended"), ("RETIRED", "Retired")], default="ACTIVE", max_length=24)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "study_lab_tool_definition", "ordering": ["tool_key"]},
        ),
        migrations.CreateModel(
            name="WorkspaceToolAvailability",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("available", models.BooleanField(default=False)),
                ("reason_code", models.CharField(choices=[("AVAILABLE", "Available"), ("WORKSPACE_NOT_ACTIVE", "Workspace not active"), ("WORKSPACE_SUSPENDED", "Workspace suspended"), ("WORKSPACE_ARCHIVED", "Workspace archived"), ("CAPABILITY_REQUIRED", "Capability required"), ("INSTITUTION_POLICY_RESTRICTED", "Institution policy restricted"), ("LEARNER_NOT_ELIGIBLE", "Learner not eligible"), ("ARIEL_NOT_ACTIVATED", "Ariel not activated"), ("NO_ACTIVE_SUBJECT", "No active subject"), ("NO_ACTIVE_JOURNEY", "No active journey"), ("TEACHING_NOT_READY", "Teaching not ready"), ("RESOURCE_NOT_READY", "Resource not ready"), ("RETRIEVAL_NOT_READY", "Retrieval not ready"), ("CONCEPT_CHECK_NOT_AVAILABLE", "Concept check not available"), ("WHITEBOARD_NOT_AVAILABLE", "Whiteboard not available"), ("CONSENT_REQUIRED", "Consent required"), ("AGE_POLICY_RESTRICTED", "Age policy restricted"), ("TENANT_MISMATCH", "Tenant mismatch"), ("PROVIDER_UNAVAILABLE", "Provider unavailable")], default="AVAILABLE", max_length=48)),
                ("reason_detail", models.CharField(blank=True, max_length=280)),
                ("evaluated_at", models.DateTimeField(auto_now_add=True)),
                ("source_versions", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("tool_definition", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="workspace_availabilities", to="study_lab.studytooldefinition")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tool_availabilities", to="study_lab.studyworkspace")),
            ],
            options={"db_table": "study_lab_tool_availability", "ordering": ["workspace", "tool_definition"]},
        ),
        migrations.CreateModel(
            name="WorkspaceToolInvocation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider_context", models.CharField(choices=[("ABBOT", "Abbot"), ("ARIEL", "Ariel"), ("WHITEBOARD", "Whiteboard"), ("RESOURCE", "Resource"), ("CONCEPT_CHECK", "Concept Check"), ("PROGRESS", "Progress"), ("JOURNEY", "Journey"), ("STUDY_LAB", "Study Lab")], max_length=32)),
                ("provider_reference", models.CharField(blank=True, max_length=128)),
                ("status", models.CharField(choices=[("REQUESTED", "Requested"), ("ACCEPTED", "Accepted"), ("COMPLETED", "Completed"), ("REJECTED", "Rejected"), ("FAILED", "Failed"), ("CANCELLED", "Cancelled")], default="REQUESTED", max_length=24)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("reason_code", models.CharField(blank=True, max_length=48)),
                ("idempotency_key", models.CharField(blank=True, max_length=128)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("learner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="study_lab_tool_invocations", to=settings.AUTH_USER_MODEL)),
                ("tool_definition", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="invocations", to="study_lab.studytooldefinition")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tool_invocations", to="study_lab.studyworkspace")),
            ],
            options={"db_table": "study_lab_tool_invocation", "ordering": ["-requested_at"]},
        ),
        migrations.CreateModel(
            name="WorkspaceSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("snapshot_version", models.PositiveIntegerField(default=1)),
                ("assembled_at", models.DateTimeField(auto_now_add=True)),
                ("workspace_version", models.PositiveIntegerField(default=1)),
                ("context_version", models.PositiveIntegerField(default=1)),
                ("resume_version", models.PositiveIntegerField(default=1)),
                ("source_versions", models.JSONField(blank=True, default=dict)),
                ("panel_projection", models.JSONField(blank=True, default=list)),
                ("tool_projection", models.JSONField(blank=True, default=list)),
                ("session_projection", models.JSONField(blank=True, default=dict)),
                ("journey_projection", models.JSONField(blank=True, default=dict)),
                ("progress_projection", models.JSONField(blank=True, default=dict)),
                ("resource_projection", models.JSONField(blank=True, default=dict)),
                ("next_action_projection", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("CURRENT", "Current"), ("STALE", "Stale"), ("SUPERSEDED", "Superseded"), ("FAILED", "Failed")], default="CURRENT", max_length=24)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="snapshots", to="study_lab.studyworkspace")),
            ],
            options={"db_table": "study_lab_snapshot", "ordering": ["-assembled_at"]},
        ),
        migrations.CreateModel(
            name="LearnerWorkspaceNote",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("subject_id", models.UUIDField(blank=True, null=True)),
                ("concept_id", models.UUIDField(blank=True, null=True)),
                ("session_reference", models.CharField(blank=True, max_length=128)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("ARCHIVED", "Archived"), ("DELETED", "Deleted")], default="ACTIVE", max_length=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("learner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="study_lab_notes", to=settings.AUTH_USER_MODEL)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notes", to="study_lab.studyworkspace")),
            ],
            options={"db_table": "study_lab_note", "ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="WorkspaceActivity",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("activity_type", models.CharField(choices=[("WORKSPACE_CREATED", "Workspace created"), ("WORKSPACE_OPENED", "Workspace opened"), ("WORKSPACE_ACTIVATED", "Workspace activated"), ("WORKSPACE_PAUSED", "Workspace paused"), ("WORKSPACE_RESUMED", "Workspace resumed"), ("WORKSPACE_COMPLETED", "Workspace completed"), ("WORKSPACE_ARCHIVED", "Workspace archived"), ("SUBJECT_SELECTED", "Subject selected"), ("CONCEPT_SELECTED", "Concept selected"), ("PANEL_OPENED", "Panel opened"), ("TOOL_INVOKED", "Tool invoked"), ("RESOURCE_OPENED", "Resource opened"), ("ABBOT_SESSION_RESUMED", "Abbot session resumed"), ("ARIEL_SESSION_STARTED", "Ariel session started"), ("WHITEBOARD_RESUMED", "Whiteboard resumed"), ("CONCEPT_CHECK_STARTED", "Concept check started"), ("NOTE_CREATED", "Note created"), ("NOTE_UPDATED", "Note updated"), ("CONTEXT_CHANGED", "Context changed"), ("RESUME_POINT_UPDATED", "Resume point updated")], max_length=48)),
                ("provider_context", models.CharField(blank=True, choices=[("ABBOT", "Abbot"), ("ARIEL", "Ariel"), ("WHITEBOARD", "Whiteboard"), ("RESOURCE", "Resource"), ("CONCEPT_CHECK", "Concept Check"), ("PROGRESS", "Progress"), ("JOURNEY", "Journey"), ("STUDY_LAB", "Study Lab")], max_length=32, null=True)),
                ("provider_reference", models.CharField(blank=True, max_length=128)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("learner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="study_lab_activities", to=settings.AUTH_USER_MODEL)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="study_lab.studyworkspace")),
            ],
            options={"db_table": "study_lab_activity", "ordering": ["-occurred_at"]},
        ),
        migrations.AddIndex(model_name="studyworkspace", index=models.Index(fields=["learner", "status"], name="sl_ws_learner_status_idx")),
        migrations.AddIndex(model_name="studyworkspace", index=models.Index(fields=["tenant", "status"], name="sl_ws_tenant_status_idx")),
        migrations.AddIndex(model_name="studyworkspace", index=models.Index(fields=["workspace_type", "status"], name="sl_ws_type_status_idx")),
        migrations.AddIndex(model_name="studyworkspace", index=models.Index(fields=["last_opened_at"], name="sl_ws_last_opened_idx")),
        migrations.AddConstraint(model_name="studyworkspace", constraint=models.CheckConstraint(condition=(Q(workspace_type="SELF_STUDY") & Q(tenant__isnull=True)) | (Q(workspace_type="PERSONAL_REVIEW") & Q(tenant__isnull=True)) | (Q(workspace_type="INSTITUTIONAL") & Q(tenant__isnull=False)) | (Q(workspace_type="HYBRID") & Q(tenant__isnull=False)), name="sl_ws_tenant_required_by_type")),
        migrations.AddConstraint(model_name="studyworkspace", constraint=models.CheckConstraint(condition=Q(workspace_type__in=["SELF_STUDY", "INSTITUTIONAL", "HYBRID", "PERSONAL_REVIEW"]), name="sl_ws_type_valid")),
        migrations.AddConstraint(model_name="studyworkspace", constraint=models.CheckConstraint(condition=Q(status__in=["DRAFT", "ACTIVE", "PAUSED", "SUSPENDED", "COMPLETED", "ARCHIVED"]), name="sl_ws_status_valid")),
        migrations.AddConstraint(model_name="workspacetoolavailability", constraint=models.UniqueConstraint(fields=("workspace", "tool_definition"), name="sl_ta_unique_workspace_tool")),
        migrations.AddConstraint(model_name="workspacetoolinvocation", constraint=models.UniqueConstraint(condition=~Q(idempotency_key=""), fields=("idempotency_key",), name="sl_inv_unique_idem")),
        migrations.AddIndex(model_name="workspacetoolinvocation", index=models.Index(fields=["workspace", "requested_at"], name="sl_inv_ws_time_idx")),
        migrations.AddIndex(model_name="workspacetoolinvocation", index=models.Index(fields=["learner", "requested_at"], name="sl_inv_learner_time_idx")),
        migrations.AddIndex(model_name="workspacetoolinvocation", index=models.Index(fields=["tool_definition", "status"], name="sl_inv_tool_status_idx")),
        migrations.AddIndex(model_name="workspacetoolinvocation", index=models.Index(fields=["idempotency_key"], name="sl_inv_idem_idx")),
        migrations.AddConstraint(model_name="workspacesnapshot", constraint=models.UniqueConstraint(fields=("workspace", "snapshot_version"), name="sl_snap_unique_ws_version")),
        migrations.AddIndex(model_name="workspacesnapshot", index=models.Index(fields=["workspace", "status"], name="sl_snap_ws_status_idx")),
        migrations.AddIndex(model_name="workspacesnapshot", index=models.Index(fields=["workspace", "snapshot_version"], name="sl_snap_ws_version_idx")),
        migrations.AddIndex(model_name="learnerworkspacenote", index=models.Index(fields=["workspace", "status"], name="sl_note_ws_status_idx")),
        migrations.AddIndex(model_name="learnerworkspacenote", index=models.Index(fields=["learner", "status"], name="sl_note_learner_status_idx")),
        migrations.AddIndex(model_name="learnerworkspacenote", index=models.Index(fields=["workspace", "subject_id"], name="sl_note_ws_subject_idx")),
        migrations.AddIndex(model_name="workspaceactivity", index=models.Index(fields=["workspace", "occurred_at"], name="sl_act_ws_time_idx")),
        migrations.AddIndex(model_name="workspaceactivity", index=models.Index(fields=["learner", "occurred_at"], name="sl_act_learner_time_idx")),
        migrations.AddIndex(model_name="workspaceactivity", index=models.Index(fields=["activity_type"], name="sl_act_type_idx")),
    ]
