from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("study_lab", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyToolManifest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("manifest_version", models.CharField(default="1.0", max_length=32)),
                ("supported_artefact_inputs", models.JSONField(blank=True, default=list)),
                ("supported_artefact_outputs", models.JSONField(blank=True, default=list)),
                ("supports_resume", models.BooleanField(default=False)),
                ("supports_transformation", models.BooleanField(default=False)),
                ("supports_import", models.BooleanField(default=False)),
                ("supports_export", models.BooleanField(default=False)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("SUSPENDED", "Suspended"), ("RETIRED", "Retired")], default="ACTIVE", max_length=24)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tool_definition", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="manifest", to="study_lab.studytooldefinition")),
            ],
            options={"db_table": "study_lab_tool_manifest", "ordering": ["tool_definition__tool_key"]},
        ),
        migrations.CreateModel(
            name="WorkspaceToolSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider_context", models.CharField(choices=[("ABBOT", "Abbot"), ("ARIEL", "Ariel"), ("WHITEBOARD", "Whiteboard"), ("RESOURCE", "Resource"), ("CONCEPT_CHECK", "Concept Check"), ("PROGRESS", "Progress"), ("JOURNEY", "Journey"), ("STUDY_LAB", "Study Lab")], max_length=32)),
                ("provider_reference", models.CharField(blank=True, max_length=128)),
                ("resume_reference", models.CharField(blank=True, max_length=128)),
                ("status", models.CharField(choices=[("OPEN", "Open"), ("SUSPENDED", "Suspended"), ("COMPLETED", "Completed"), ("FAILED", "Failed"), ("ABANDONED", "Abandoned")], default="OPEN", max_length=24)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("learner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="study_lab_tool_sessions", to=settings.AUTH_USER_MODEL)),
                ("tool_definition", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="workspace_sessions", to="study_lab.studytooldefinition")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tool_sessions", to="study_lab.studyworkspace")),
            ],
            options={"db_table": "study_lab_tool_session", "ordering": ["-opened_at"]},
        ),
        migrations.CreateModel(
            name="StudyArtefact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("artefact_type", models.CharField(choices=[("TEXT_NOTE", "Text note"), ("FLASHCARD_SET", "Flashcard set"), ("FORMULA_SHEET", "Formula sheet"), ("REVISION_SUMMARY", "Revision summary"), ("WHITEBOARD_SNAPSHOT", "Whiteboard snapshot"), ("RESOURCE_EXCERPT", "Resource excerpt"), ("SESSION_SUMMARY", "Session summary"), ("LESSON_REFERENCE", "Lesson reference"), ("CONCEPT_REFERENCE", "Concept reference"), ("CONCEPT_MAP", "Concept map"), ("LEARNER_EXPLANATION", "Learner explanation"), ("ARIEL_TEACHING_ARTEFACT", "Ariel teaching artefact"), ("ABBOT_LESSON_REFERENCE", "Abbot lesson reference"), ("CONCEPT_CHECK_RECEIPT", "Concept check receipt")], max_length=48)),
                ("provider_context", models.CharField(blank=True, choices=[("ABBOT", "Abbot"), ("ARIEL", "Ariel"), ("WHITEBOARD", "Whiteboard"), ("RESOURCE", "Resource"), ("CONCEPT_CHECK", "Concept Check"), ("PROGRESS", "Progress"), ("JOURNEY", "Journey"), ("STUDY_LAB", "Study Lab")], max_length=32, null=True)),
                ("provider_reference", models.CharField(blank=True, max_length=128)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("summary", models.CharField(blank=True, max_length=500)),
                ("version", models.PositiveIntegerField(default=1)),
                ("visibility", models.CharField(choices=[("PRIVATE", "Private"), ("WORKSPACE", "Workspace"), ("INSTITUTION_SHARED", "Institution shared"), ("EXPLICIT_RECIPIENTS", "Explicit recipients")], default="PRIVATE", max_length=32)),
                ("lifecycle", models.CharField(choices=[("DRAFT", "Draft"), ("ACTIVE", "Active"), ("ARCHIVED", "Archived"), ("SUPERSEDED", "Superseded")], default="DRAFT", max_length=24)),
                ("schema_version", models.CharField(default="1", max_length=32)),
                ("creation_source", models.CharField(choices=[("NATIVE", "Native"), ("REFERENCED", "Referenced"), ("IMPORTED", "Imported"), ("EXPORTED", "Exported"), ("TRANSFORMED", "Transformed")], default="NATIVE", max_length=24)),
                ("invocation_reference", models.CharField(blank=True, max_length=128)),
                ("native_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("learner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="study_lab_artefacts", to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="study_lab_artefacts", to="users.institution")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="artefacts", to="study_lab.studyworkspace")),
            ],
            options={"db_table": "study_lab_artefact", "ordering": ["-updated_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="StudyArtefactLineage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("relation_type", models.CharField(choices=[("DERIVED_FROM", "Derived from"), ("TRANSFORMED_FROM", "Transformed from"), ("SUMMARISES", "Summarises"), ("ANNOTATES", "Annotates"), ("EXTRACTED_FROM", "Extracted from"), ("COMBINED_FROM", "Combined from"), ("SUPERSEDES", "Supersedes"), ("SHARED_WITH", "Shared with"), ("EXPORTED_TO", "Exported to")], max_length=32)),
                ("provider_context", models.CharField(blank=True, choices=[("ABBOT", "Abbot"), ("ARIEL", "Ariel"), ("WHITEBOARD", "Whiteboard"), ("RESOURCE", "Resource"), ("CONCEPT_CHECK", "Concept Check"), ("PROGRESS", "Progress"), ("JOURNEY", "Journey"), ("STUDY_LAB", "Study Lab")], max_length=32, null=True)),
                ("provider_reference", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("source_artefact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="outgoing_lineage", to="study_lab.studyartefact")),
                ("target_artefact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="incoming_lineage", to="study_lab.studyartefact")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="artefact_lineage", to="study_lab.studyworkspace")),
            ],
            options={"db_table": "study_lab_artefact_lineage", "ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="StudyArtefactTransformationDefinition",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("transformation_key", models.CharField(max_length=64, unique=True)),
                ("source_artefact_types", models.JSONField(blank=True, default=list)),
                ("destination_type", models.CharField(choices=[("TEXT_NOTE", "Text note"), ("FLASHCARD_SET", "Flashcard set"), ("FORMULA_SHEET", "Formula sheet"), ("REVISION_SUMMARY", "Revision summary"), ("WHITEBOARD_SNAPSHOT", "Whiteboard snapshot"), ("RESOURCE_EXCERPT", "Resource excerpt"), ("SESSION_SUMMARY", "Session summary"), ("LESSON_REFERENCE", "Lesson reference"), ("CONCEPT_REFERENCE", "Concept reference"), ("CONCEPT_MAP", "Concept map"), ("LEARNER_EXPLANATION", "Learner explanation"), ("ARIEL_TEACHING_ARTEFACT", "Ariel teaching artefact"), ("ABBOT_LESSON_REFERENCE", "Abbot lesson reference"), ("CONCEPT_CHECK_RECEIPT", "Concept check receipt")], max_length=48)),
                ("deterministic", models.BooleanField(default=True)),
                ("provider_context", models.CharField(blank=True, choices=[("ABBOT", "Abbot"), ("ARIEL", "Ariel"), ("WHITEBOARD", "Whiteboard"), ("RESOURCE", "Resource"), ("CONCEPT_CHECK", "Concept Check"), ("PROGRESS", "Progress"), ("JOURNEY", "Journey"), ("STUDY_LAB", "Study Lab")], max_length=32, null=True)),
                ("required_capability", models.CharField(blank=True, max_length=64)),
                ("learner_approval_required", models.BooleanField(default=False)),
                ("supported_schema_versions", models.JSONField(blank=True, default=list)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("SUSPENDED", "Suspended"), ("RETIRED", "Retired")], default="ACTIVE", max_length=24)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "study_lab_artefact_transformation_definition", "ordering": ["transformation_key"]},
        ),
        migrations.CreateModel(
            name="ArtefactTransformationRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("REQUESTED", "Requested"), ("VALIDATING", "Validating"), ("READY", "Ready"), ("PROCESSING", "Processing"), ("COMPLETED", "Completed"), ("FAILED", "Failed"), ("CANCELLED", "Cancelled")], default="REQUESTED", max_length=24)),
                ("idempotency_key", models.CharField(blank=True, max_length=128)),
                ("failure_reason", models.CharField(blank=True, max_length=280)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("validating_at", models.DateTimeField(blank=True, null=True)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("processing_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("definition", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="requests", to="study_lab.studyartefacttransformationdefinition")),
                ("learner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="study_lab_transformation_requests", to=settings.AUTH_USER_MODEL)),
                ("output_artefact", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="producing_transformations", to="study_lab.studyartefact")),
                ("source_artefact", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="transformation_requests", to="study_lab.studyartefact")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="transformation_requests", to="study_lab.studyworkspace")),
            ],
            options={"db_table": "study_lab_artefact_transformation_request", "ordering": ["-requested_at"]},
        ),
        migrations.AddIndex(model_name="workspacetoolsession", index=models.Index(fields=["workspace", "status"], name="sl_ts_ws_status_idx")),
        migrations.AddIndex(model_name="workspacetoolsession", index=models.Index(fields=["tool_definition", "status"], name="sl_ts_tool_status_idx")),
        migrations.AddIndex(model_name="studyartefact", index=models.Index(fields=["workspace", "lifecycle"], name="sl_art_ws_life_idx")),
        migrations.AddIndex(model_name="studyartefact", index=models.Index(fields=["learner", "visibility"], name="sl_art_learner_vis_idx")),
        migrations.AddIndex(model_name="studyartefact", index=models.Index(fields=["artefact_type", "schema_version"], name="sl_art_type_schema_idx")),
        migrations.AddIndex(model_name="studyartefactlineage", index=models.Index(fields=["workspace", "relation_type"], name="sl_al_ws_rel_idx")),
        migrations.AddIndex(model_name="studyartefactlineage", index=models.Index(fields=["source_artefact", "relation_type"], name="sl_al_source_rel_idx")),
        migrations.AddIndex(model_name="studyartefactlineage", index=models.Index(fields=["target_artefact", "relation_type"], name="sl_al_target_rel_idx")),
        migrations.AddIndex(model_name="artefacttransformationrequest", index=models.Index(fields=["workspace", "status"], name="sl_atr_ws_status_idx")),
        migrations.AddIndex(model_name="artefacttransformationrequest", index=models.Index(fields=["definition", "status"], name="sl_atr_def_status_idx")),
        migrations.AddIndex(model_name="artefacttransformationrequest", index=models.Index(fields=["idempotency_key"], name="sl_atr_idem_idx")),
        migrations.AddConstraint(model_name="artefacttransformationrequest", constraint=models.UniqueConstraint(fields=("idempotency_key",), condition=~Q(idempotency_key=""), name="sl_atr_unique_idem")),
    ]
