from django.db import migrations, models


TOOL_CHOICES = [
    ("ABBOT_MENTOR", "Abbot Mentor"),
    ("ARIEL_TEACH", "Ariel Teach"),
    ("STRUCTURED_WHITEBOARD", "Structured Whiteboard"),
    ("RESOURCE_VIEWER", "Resource Viewer"),
    ("CONCEPT_CHECK", "Concept Check"),
    ("LEARNER_NOTES", "Learner Notes"),
    ("PROGRESS_VIEW", "Progress View"),
    ("JOURNEY_MAP", "Journey Map"),
    ("RESUME_SESSION", "Resume Session"),
    ("STANDARD_CALCULATOR", "Standard Calculator"),
    ("SCIENTIFIC_CALCULATOR", "Scientific Calculator"),
    ("GRAPHING_CALCULATOR", "Graphing Calculator"),
    ("UNIT_CONVERTER", "Unit Converter"),
    ("EQUATION_WORKSPACE", "Equation Workspace"),
    ("FORMULA_SHEET", "Formula Sheet"),
    ("MATH_SCRATCHPAD", "Math Scratchpad"),
    ("TABLE_BUILDER", "Table Builder"),
    ("DIAGRAM_STUDIO", "Diagram Studio"),
    ("CONCEPT_MAP", "Concept Map"),
    ("FLOWCHART", "Flowchart"),
    ("TIMELINE", "Timeline"),
    ("COMPARISON_TABLE", "Comparison Table"),
    ("FLASHCARD_WORKSPACE", "Flashcard Workspace"),
    ("STRUCTURED_SCRATCHPAD", "Structured Scratchpad"),
    ("NOTE_CARDS", "Note Cards"),
    ("CHECKLIST", "Checklist"),
    ("CODE_EDITOR", "Code Editor"),
]


ARTEFACT_CHOICES = [
    ("TEXT_NOTE", "Text note"),
    ("FLASHCARD_SET", "Flashcard set"),
    ("FLASHCARD", "Flashcard"),
    ("FORMULA_SHEET", "Formula sheet"),
    ("EQUATION_ARTEFACT", "Equation artefact"),
    ("GRAPH_ARTEFACT", "Graph artefact"),
    ("REVISION_SUMMARY", "Revision summary"),
    ("WHITEBOARD_SNAPSHOT", "Whiteboard snapshot"),
    ("RESOURCE_EXCERPT", "Resource excerpt"),
    ("SESSION_SUMMARY", "Session summary"),
    ("LESSON_REFERENCE", "Lesson reference"),
    ("CONCEPT_REFERENCE", "Concept reference"),
    ("CONCEPT_MAP", "Concept map"),
    ("FLOWCHART", "Flowchart"),
    ("TIMELINE", "Timeline"),
    ("COMPARISON_TABLE", "Comparison table"),
    ("DIAGRAM_ARTEFACT", "Diagram artefact"),
    ("LEARNER_EXPLANATION", "Learner explanation"),
    ("ARIEL_TEACHING_ARTEFACT", "Ariel teaching artefact"),
    ("ABBOT_LESSON_REFERENCE", "Abbot lesson reference"),
    ("CONCEPT_CHECK_RECEIPT", "Concept check receipt"),
    ("SCRATCHPAD_ARTEFACT", "Scratchpad artefact"),
    ("NOTE_CARD_SET", "Note card set"),
    ("DATA_TABLE", "Data table"),
    ("CODE_ARTEFACT", "Code artefact"),
]


def _seed_instruments(apps, schema_editor):
    StudyToolDefinition = apps.get_model("study_lab", "StudyToolDefinition")
    StudyToolManifest = apps.get_model("study_lab", "StudyToolManifest")

    definitions = [
        {
            "tool_key": "STANDARD_CALCULATOR",
            "display_name": "Standard Calculator",
            "instrument_family": "COMPUTATIONAL",
            "category": "LEARNING",
            "provider_context": "STUDY_LAB",
            "supported_artefact_outputs": [],
            "supports_transform": False,
            "supports_import": False,
            "supports_export": False,
            "requires_runtime": False,
            "offline_capable": True,
        },
        {
            "tool_key": "SCIENTIFIC_CALCULATOR",
            "display_name": "Scientific Calculator",
            "instrument_family": "COMPUTATIONAL",
            "category": "LEARNING",
            "provider_context": "STUDY_LAB",
            "supported_artefact_outputs": [],
            "supports_transform": False,
            "supports_import": False,
            "supports_export": False,
            "requires_runtime": False,
            "offline_capable": True,
        },
        {
            "tool_key": "GRAPHING_CALCULATOR",
            "display_name": "Graphing Calculator",
            "instrument_family": "GRAPHING",
            "category": "LEARNING",
            "provider_context": "STUDY_LAB",
            "supported_artefact_outputs": ["GRAPH_ARTEFACT"],
            "supports_transform": True,
            "supports_import": False,
            "supports_export": True,
            "requires_runtime": False,
            "offline_capable": True,
        },
        {
            "tool_key": "UNIT_CONVERTER",
            "display_name": "Unit Converter",
            "instrument_family": "COMPUTATIONAL",
            "category": "LEARNING",
            "provider_context": "STUDY_LAB",
            "supported_artefact_outputs": [],
            "supports_transform": False,
            "supports_import": False,
            "supports_export": False,
            "requires_runtime": False,
            "offline_capable": True,
        },
        {
            "tool_key": "EQUATION_WORKSPACE",
            "display_name": "Equation Workspace",
            "instrument_family": "MATHEMATICAL_CONSTRUCTION",
            "category": "LEARNING",
            "provider_context": "STUDY_LAB",
            "supported_artefact_outputs": ["EQUATION_ARTEFACT", "FORMULA_SHEET"],
            "supports_transform": True,
            "supports_import": True,
            "supports_export": True,
            "requires_runtime": False,
            "offline_capable": True,
        },
        {
            "tool_key": "FORMULA_SHEET",
            "display_name": "Formula Sheet",
            "instrument_family": "MEMORY_AND_REVIEW",
            "category": "REVIEW",
            "provider_context": "STUDY_LAB",
            "supported_artefact_outputs": ["FORMULA_SHEET"],
            "supports_transform": True,
            "supports_import": True,
            "supports_export": True,
            "requires_runtime": False,
            "offline_capable": True,
        },
        {
            "tool_key": "MATH_SCRATCHPAD",
            "display_name": "Math Scratchpad",
            "instrument_family": "GENERAL_THINKING",
            "category": "LEARNING",
            "provider_context": "STUDY_LAB",
            "supported_artefact_outputs": ["SCRATCHPAD_ARTEFACT"],
            "supports_transform": True,
            "supports_import": True,
            "supports_export": True,
            "requires_runtime": False,
            "offline_capable": True,
        },
        {
            "tool_key": "TABLE_BUILDER",
            "display_name": "Table Builder",
            "instrument_family": "GENERAL_THINKING",
            "category": "LEARNING",
            "provider_context": "STUDY_LAB",
            "supported_artefact_outputs": ["DATA_TABLE"],
            "supports_transform": True,
            "supports_import": True,
            "supports_export": True,
            "requires_runtime": False,
            "offline_capable": True,
        },
        {
            "tool_key": "DIAGRAM_STUDIO",
            "display_name": "Diagram Studio",
            "instrument_family": "VISUAL_REASONING",
            "category": "LEARNING",
            "provider_context": "STUDY_LAB",
            "supported_artefact_outputs": ["DIAGRAM_ARTEFACT"],
            "supports_transform": True,
            "supports_import": True,
            "supports_export": True,
            "requires_runtime": False,
            "offline_capable": True,
        },
        {
            "tool_key": "CONCEPT_MAP",
            "display_name": "Concept Map",
            "instrument_family": "VISUAL_REASONING",
            "category": "LEARNING",
            "provider_context": "STUDY_LAB",
            "supported_artefact_outputs": ["CONCEPT_MAP"],
            "supports_transform": True,
            "supports_import": True,
            "supports_export": True,
            "requires_runtime": False,
            "offline_capable": True,
        },
        {
            "tool_key": "FLOWCHART",
            "display_name": "Flowchart",
            "instrument_family": "VISUAL_REASONING",
            "category": "LEARNING",
            "provider_context": "STUDY_LAB",
            "supported_artefact_outputs": ["FLOWCHART"],
            "supports_transform": True,
            "supports_import": True,
            "supports_export": True,
            "requires_runtime": False,
            "offline_capable": True,
        },
        {
            "tool_key": "TIMELINE",
            "display_name": "Timeline",
            "instrument_family": "VISUAL_REASONING",
            "category": "LEARNING",
            "provider_context": "STUDY_LAB",
            "supported_artefact_outputs": ["TIMELINE"],
            "supports_transform": True,
            "supports_import": True,
            "supports_export": True,
            "requires_runtime": False,
            "offline_capable": True,
        },
        {
            "tool_key": "COMPARISON_TABLE",
            "display_name": "Comparison Table",
            "instrument_family": "GENERAL_THINKING",
            "category": "LEARNING",
            "provider_context": "STUDY_LAB",
            "supported_artefact_outputs": ["COMPARISON_TABLE"],
            "supports_transform": True,
            "supports_import": True,
            "supports_export": True,
            "requires_runtime": False,
            "offline_capable": True,
        },
        {
            "tool_key": "FLASHCARD_WORKSPACE",
            "display_name": "Flashcard Workspace",
            "instrument_family": "MEMORY_AND_REVIEW",
            "category": "REVIEW",
            "provider_context": "STUDY_LAB",
            "supported_artefact_outputs": ["FLASHCARD_SET"],
            "supports_transform": True,
            "supports_import": True,
            "supports_export": True,
            "requires_runtime": False,
            "offline_capable": True,
        },
        {
            "tool_key": "STRUCTURED_SCRATCHPAD",
            "display_name": "Structured Scratchpad",
            "instrument_family": "GENERAL_THINKING",
            "category": "LEARNING",
            "provider_context": "STUDY_LAB",
            "supported_artefact_outputs": ["SCRATCHPAD_ARTEFACT"],
            "supports_transform": True,
            "supports_import": True,
            "supports_export": True,
            "requires_runtime": False,
            "offline_capable": True,
        },
        {
            "tool_key": "NOTE_CARDS",
            "display_name": "Note Cards",
            "instrument_family": "MEMORY_AND_REVIEW",
            "category": "REVIEW",
            "provider_context": "STUDY_LAB",
            "supported_artefact_outputs": ["NOTE_CARD_SET"],
            "supports_transform": True,
            "supports_import": True,
            "supports_export": True,
            "requires_runtime": False,
            "offline_capable": True,
        },
        {
            "tool_key": "CHECKLIST",
            "display_name": "Checklist",
            "instrument_family": "GENERAL_THINKING",
            "category": "LEARNING",
            "provider_context": "STUDY_LAB",
            "supported_artefact_outputs": ["CHECKLIST"],
            "supports_transform": False,
            "supports_import": False,
            "supports_export": True,
            "requires_runtime": False,
            "offline_capable": True,
        },
        {
            "tool_key": "CODE_EDITOR",
            "display_name": "Code Editor",
            "instrument_family": "TECHNICAL",
            "category": "LEARNING",
            "provider_context": "STUDY_LAB",
            "supported_artefact_outputs": ["CODE_ARTEFACT"],
            "supports_transform": True,
            "supports_import": True,
            "supports_export": True,
            "requires_runtime": True,
            "offline_capable": False,
        },
    ]

    for definition in definitions:
        tool, _ = StudyToolDefinition.objects.update_or_create(
            tool_key=definition["tool_key"],
            defaults={
                "display_name": definition["display_name"],
                "description": f"{definition['display_name']} instrument.",
                "category": definition["category"],
                "provider_context": definition["provider_context"],
                "instrument_family": definition["instrument_family"],
                "required_capability": "",
                "input_artefact_types": [],
                "output_artefact_types": definition["supported_artefact_outputs"],
                "supported_workspace_types": [],
                "schema_versions": ["1"],
                "policy_key": definition["tool_key"].lower(),
                "status": "ACTIVE",
                "version": 1,
                "supports_transform": definition["supports_transform"],
                "supports_import": definition["supports_import"],
                "supports_export": definition["supports_export"],
                "requires_runtime": definition["requires_runtime"],
                "runtime_provider": "",
                "offline_capable": definition["offline_capable"],
            },
        )
        StudyToolManifest.objects.update_or_create(
            tool_definition=tool,
            defaults={
                "manifest_version": "1.0",
                "supported_artefact_inputs": [],
                "supported_artefact_outputs": definition["supported_artefact_outputs"],
                "supported_schema_versions": ["1"],
                "supports_resume": False,
                "supports_transformation": definition["supports_transform"],
                "supports_import": definition["supports_import"],
                "supports_export": definition["supports_export"],
                "status": "ACTIVE",
                "version": 1,
            },
        )


def _unseed_instruments(apps, schema_editor):
    StudyToolDefinition = apps.get_model("study_lab", "StudyToolDefinition")
    StudyToolDefinition.objects.filter(tool_key__in=[
        "STANDARD_CALCULATOR",
        "SCIENTIFIC_CALCULATOR",
        "GRAPHING_CALCULATOR",
        "UNIT_CONVERTER",
        "EQUATION_WORKSPACE",
        "FORMULA_SHEET",
        "MATH_SCRATCHPAD",
        "TABLE_BUILDER",
        "DIAGRAM_STUDIO",
        "CONCEPT_MAP",
        "FLOWCHART",
        "TIMELINE",
        "COMPARISON_TABLE",
        "FLASHCARD_WORKSPACE",
        "STRUCTURED_SCRATCHPAD",
        "NOTE_CARDS",
        "CHECKLIST",
        "CODE_EDITOR",
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("study_lab", "0004_instrument_suite_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studytooldefinition",
            name="tool_key",
            field=models.CharField(choices=TOOL_CHOICES, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="workspaceresumestate",
            name="last_tool_key",
            field=models.CharField(blank=True, choices=TOOL_CHOICES, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="studyartefact",
            name="artefact_type",
            field=models.CharField(choices=ARTEFACT_CHOICES, max_length=48),
        ),
        migrations.AlterField(
            model_name="studyartefacttransformationdefinition",
            name="destination_type",
            field=models.CharField(choices=ARTEFACT_CHOICES, max_length=48),
        ),
        migrations.RunPython(_seed_instruments, _unseed_instruments),
    ]
