from __future__ import annotations

from typing import Protocol

from apps.academic.domain.models import LearningResource
from apps.content_intelligence.domain.models import (
    ContentExtractionResult,
    ContentImportJob,
    ContentValidationFinding,
    ParsedConceptCandidate,
    ParsedDocument,
    ParsedSection,
    ParserPipelineRun,
)


class ContentImportJobRepository(Protocol):
    def add(self, job: ContentImportJob) -> ContentImportJob: ...
    def save(self, job: ContentImportJob) -> ContentImportJob: ...
    def get(self, job_id: str) -> ContentImportJob: ...
    def list_all(self) -> list[ContentImportJob]: ...
    def list_for_resource(self, learning_resource: LearningResource) -> list[ContentImportJob]: ...


class ParsedDocumentRepository(Protocol):
    def save_document(self, parsed_document: ParsedDocument) -> ParsedDocument: ...
    def get_for_job(self, job: ContentImportJob) -> ParsedDocument | None: ...
    def replace_sections(self, parsed_document: ParsedDocument, sections: list[ParsedSection]) -> list[ParsedSection]: ...
    def replace_concepts(self, parsed_section: ParsedSection, concepts: list[ParsedConceptCandidate]) -> list[ParsedConceptCandidate]: ...


class ContentExtractionResultRepository(Protocol):
    def save_result(self, result: ContentExtractionResult) -> ContentExtractionResult: ...
    def get_for_job(self, job: ContentImportJob) -> ContentExtractionResult | None: ...


class ValidationFindingRepository(Protocol):
    def replace_for_job(self, job: ContentImportJob, findings: list[ContentValidationFinding]) -> list[ContentValidationFinding]: ...
    def list_for_job(self, job: ContentImportJob) -> list[ContentValidationFinding]: ...


class ParserPipelineRunRepository(Protocol):
    def add(self, run: ParserPipelineRun) -> ParserPipelineRun: ...
    def save(self, run: ParserPipelineRun) -> ParserPipelineRun: ...
    def list_for_job(self, job: ContentImportJob) -> list[ParserPipelineRun]: ...
