# Generated by Django 5.2.15 on 2026-06-30 09:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("school", "School"),
                            ("university", "University"),
                            ("company", "Company"),
                            ("training_provider", "Training Provider"),
                            ("government_academy", "Government Academy"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "institution",
                "verbose_name_plural": "institutions",
            },
        ),
        migrations.CreateModel(
            name="InstitutionMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("teacher", "Teacher"),
                            ("reviewer", "Reviewer"),
                            ("administrator", "Administrator"),
                            ("institution_owner", "Institution Owner"),
                            ("system_administrator", "System Administrator"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.institution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "institution membership",
                "verbose_name_plural": "institution memberships",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "institution", "role"),
                        name="unique_user_institution_role",
                    )
                ],
            },
        ),
    ]
