# Generated by Django 5.2.15 on 2026-06-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_institution_institutionmembership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="institution_type",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("school", "School"),
                    ("university", "University"),
                    ("company", "Company"),
                    ("training_provider", "Training Provider"),
                    ("government_academy", "Government Academy"),
                ],
                default="individual",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="institutionmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("reviewer", "Reviewer"),
                    ("administrator", "Administrator"),
                    ("institution_owner", "Institution Owner"),
                    ("system_administrator", "System Administrator"),
                ],
                default="student",
                max_length=50,
            ),
        ),
    ]
