from .subscribers import EventSubscriber


class EventRegistry:
    def __init__(self) -> None:
        self._subscribers: dict[str, list[EventSubscriber]] = {}

    def subscribe(self, event_name: str, subscriber: EventSubscriber) -> None:
        self._subscribers.setdefault(event_name, []).append(subscriber)

    def get_subscribers(self, event_name: str) -> list[EventSubscriber]:
        return list(self._subscribers.get(event_name, []))

    def clear(self) -> None:
        self._subscribers.clear()


default_event_registry = EventRegistry()

# Known platform and domain event names. Empty subscriber lists make event names
# discoverable even before asynchronous subscribers are attached.
for event_name in [
    "settings.user_setting_changed",
    "settings.user_setting_deleted",
    "settings.institution_setting_changed",
    "settings.institution_setting_deleted",
    "audit.entry_recorded",
    "academic.subject_created",
    "academic.subject_updated",
    "academic.subject_archived",
    "academic.curriculum_created",
    "academic.curriculum_updated",
    "academic.curriculum_archived",
    "academic.curriculum_unit_created",
    "academic.curriculum_unit_updated",
    "academic.curriculum_unit_archived",
    "academic.learning_resource_created",
    "academic.learning_resource_updated",
    "academic.learning_resource_activated",
    "academic.learning_resource_archived",
    "academic.learning_resource_deleted",
    "academic.content_section_created",
    "academic.content_section_updated",
    "academic.content_section_archived",
    "academic.content_section_deleted",
    "academic.content_concept_created",
    "academic.content_concept_updated",
    "academic.content_concept_archived",
    "academic.content_concept_deleted",
    "academic.content_section_submitted_for_review",
    "academic.content_section_approved",
    "academic.content_section_rejected",
    "academic.content_section_quality_marked",
    "academic.content_concept_submitted_for_review",
    "academic.content_concept_approved",
    "academic.content_concept_rejected",
    "academic.content_concept_quality_marked",
    "academic.manual_section_created",
    "academic.manual_section_updated",
    "academic.manual_section_archived",
    "academic.manual_section_reordered",
    "academic.manual_concept_created",
    "academic.manual_concept_updated",
    "academic.manual_concept_archived",
    "academic.manual_concept_reordered",
    "academic.resource_ingestion_job_created",
    "academic.resource_ingestion_job_started",
    "academic.resource_ingestion_job_completed",
    "academic.resource_ingestion_job_failed",
    "academic.resource_ingestion_job_cancelled",
    "pedagogy.session_created",
    "pedagogy.session_started",
    "pedagogy.session_paused",
    "pedagogy.session_resumed",
    "pedagogy.session_completed",
    "pedagogy.session_abandoned",
    "pedagogy.message_added",
    "learning.context_assembled",
    "learning.grounding_package_created",
    "learning.grounding_validated",
    "learning.strategy_selected",
    "learning.strategy_validated",
    "learning.conversation_initialized",
    "learning.turn_added",
    "learning.window_trimmed",
    "learning.abbot_request_prepared",
    "learning.abbot_response_generated",
    "learning.abbot_response_validated",
    "learning.companion_registered",
    "learning.companion_activated",
    "learning.companion_deactivated",
    "learning.companion_response_generated",
    "assessment.created",
    "assessment.item_added",
    "assessment.attempt_started",
    "assessment.response_submitted",
    "assessment.attempt_completed",
    "assessment.learning_evidence_recorded",
    "assessment.mastery_decision_created",
    "assessment.mastery_profile_updated",
    "assessment.strategy_selected",
    "assessment.blueprint_built",
    "assessment.strategy_validated",
    "assessment.blueprint_validated",
    "assessment.item_bank_entry_created",
    "assessment.item_bank_entry_updated",
    "assessment.item_bank_entry_archived",
    "assessment.item_bank_entry_submitted_for_review",
    "assessment.item_bank_entry_approved",
    "assessment.item_bank_entry_rejected",
    "assessment.item_bank_entry_quality_marked",
    "assessment.item_option_added",
    "assessment.item_option_updated",
    "assessment.item_option_removed",
    "assessment.item_added_to_assessment",
    "assessment.item_removed_from_assessment",
    "assessment.delivery_session_created",
    "assessment.delivery_session_started",
    "assessment.delivery_item_presented",
    "assessment.delivery_response_submitted",
    "assessment.delivery_session_submitted",
    "assessment.delivery_session_completed",
    "assessment.delivery_session_abandoned",
    "assessment.response_evaluated",
    "assessment.attempt_evaluated",
    "assessment.result_created",
    "assessment.result_updated",
    "assessment.evaluation_integrated_as_evidence",
    "assessment.result_integrated_as_evidence",
    "assessment.attempt_integrated_as_evidence",
    "remediation.planned",
    "remediation.started",
    "remediation.completed",
    "remediation.escalated",
    "remediation.cancelled",
    "remediation.closed",
    "assessment_review.started",
    "assessment_review.question_reviewed",
    "assessment_review.difficulty_calibrated",
    "assessment_review.assessment_approved",
    "assessment_review.assessment_rejected",
    "assessment_review.assessment_needs_revision",
    "content_intelligence.import_started",
    "content_intelligence.extraction_completed",
    "content_intelligence.ocr_requested",
    "content_intelligence.ocr_completed",
    "content_intelligence.sections_detected",
    "content_intelligence.concepts_extracted",
    "content_intelligence.import_validated",
    "content_intelligence.academic_population_completed",
    "content_intelligence.import_completed",
    "content_intelligence.import_failed",
    "content_intelligence.deletion_requested",
    "content_intelligence.deleted",
    "content_intelligence.stored_file_deletion_failed",
    "retrieval.resource_retired",
    "storage.file_contents_deleted",
    "content_processing.job_created",
    "content_processing.job_queued",
    "content_processing.attempt_started",
    "content_processing.stage_started",
    "content_processing.stage_progressed",
    "content_processing.stage_completed",
    "content_processing.diagnostic_recorded",
    "content_processing.job_failed",
    "content_processing.retry_requested",
    "content_processing.job_cancel_requested",
    "content_processing.job_cancelled",
    "content_processing.ready_for_review",
    "content_processing.ready_for_teaching",
    "content_processing.job_deleted",
    "academic_import.proposal_created",
    "academic_import.validation_completed",
    "academic_import.blocking_findings_recorded",
    "academic_import.automatic_acceptance_evaluated",
    "academic_import.automatic_acceptance_denied",
    "academic_import.automatically_approved",
    "academic_import.review_required",
    "academic_import.review_started",
    "academic_import.approved",
    "academic_import.rejected",
    "academic_import.superseded",
    "academic_population.started",
    "academic_population.planned",
    "academic_population.completed",
    "academic_population.failed",
    "academic_population.retried",
    "approved_proposal.populated",
    "academic_review.started",
    "academic_review.item_decided",
    "academic_review.item_edited",
    "academic_review.bulk_action",
    "academic_review.override",
    "academic_review.submitted",
    "academic_review.approved",
    "academic_review.rejected",
    "academic_review.reprocessing_requested",
    "academic_review.population_requested",
    "academic_review.approval_readiness_evaluated",
    "academic_review.approval_blocked",
    "academic_review.proposal_approved",
    "academic_review.proposal_approved_with_edits",
    "academic_review.proposal_rejected",
    "academic_review.approved_projection_created",
    "academic_review.ready_for_population",
    "retrieval.chunk_collection_created",
    "retrieval.index_started",
    "retrieval.embedding_completed",
    "retrieval.index_completed",
    "retrieval.index_failed",
    "retrieval.readiness_changed",
    "grounding.package_created",
    "retrieval_synchronization.planned",
    "retrieval_synchronization.started",
    "retrieval_synchronization.completed",
    "retrieval_synchronization.failed",
    "retrieval_generation.promoted",
    "retrieval_generation.superseded",
]:
    default_event_registry._subscribers.setdefault(event_name, [])
