# Generated by Django 5.2.16 on 2026-08-11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0003_institution_institutionmembership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessEventRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=160)),
                ("source_entity_type", models.CharField(blank=True, default="", max_length=160)),
                ("source_entity_id", models.CharField(blank=True, default="", max_length=160)),
                ("safe_payload", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField()),
                ("correlation_id", models.UUIDField(blank=True, null=True)),
                ("causation_event_id", models.UUIDField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="business_events",
                        to="users.institution",
                    ),
                ),
            ],
            options={
                "db_table": "core_business_event",
                "ordering": ["-occurred_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BusinessEventDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("consumer_key", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("FAILED_RETRYABLE", "Failed retryable"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED_TERMINAL", "Failed terminal"),
                        ],
                        default="PENDING",
                        max_length=24,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("failure_code", models.CharField(blank=True, default="", max_length=96)),
                ("failure_detail_safe", models.CharField(blank=True, default="", max_length=500)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="core.businesseventrecord",
                    ),
                ),
            ],
            options={
                "db_table": "core_business_event_delivery",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="businesseventdelivery",
            constraint=models.UniqueConstraint(
                fields=("event", "consumer_key"),
                name="uniq_evt_consumer_delivery",
            ),
        ),
        migrations.AddIndex(
            model_name="businesseventrecord",
            index=models.Index(fields=["event_type", "occurred_at"], name="core_evt_type_occur_idx"),
        ),
        migrations.AddIndex(
            model_name="businesseventrecord",
            index=models.Index(fields=["source_entity_type", "source_entity_id"], name="core_evt_src_idx"),
        ),
        migrations.AddIndex(
            model_name="businesseventrecord",
            index=models.Index(fields=["tenant", "occurred_at"], name="core_evt_tenant_idx"),
        ),
        migrations.AddIndex(
            model_name="businesseventdelivery",
            index=models.Index(fields=["status", "next_attempt_at"], name="core_evt_del_retry_idx"),
        ),
        migrations.AddIndex(
            model_name="businesseventdelivery",
            index=models.Index(fields=["status", "processing_started_at"], name="core_evt_del_proc_idx"),
        ),
    ]
