import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("learning_identity", "0003_declaration_synchronization"),
        ("users", "0004_alter_institution_institution_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningIdentityObservation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("observation_type", models.CharField(choices=[("DIAGNOSTIC_COMPLETED", "Diagnostic completed"), ("LEARNING_SESSION_COMPLETED", "Learning session completed"), ("LEARNING_SESSION_RESUMED", "Learning session resumed"), ("EXPLANATION_REVISITED", "Explanation revisited"), ("STUDY_ACTIVITY_RECORDED", "Study activity recorded")], max_length=48)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("CONTESTED", "Contested"), ("HIDDEN", "Hidden"), ("STALE", "Stale"), ("WITHDRAWN", "Withdrawn"), ("INVALIDATED", "Invalidated"), ("SUPERSEDED", "Superseded")], default="ACTIVE", max_length=16)),
                ("source_domain", models.CharField(choices=[("IDENTITY", "Identity"), ("SELF_STUDY", "Self-study"), ("ACADEMIC", "Academic"), ("LEARNING", "Learning"), ("ASSESSMENT", "Assessment"), ("DIAGNOSTIC", "Diagnostic"), ("INSTITUTION", "Institution"), ("LEARNING_IDENTITY", "Learning identity")], max_length=32)),
                ("source_type", models.CharField(choices=[("LEARNER_DECLARATION", "Learner declaration"), ("ONBOARDING_CONTEXT", "Onboarding context"), ("INSTITUTIONAL_MEMBERSHIP", "Institutional membership"), ("DIAGNOSTIC_ATTEMPT", "Diagnostic attempt"), ("DIAGNOSTIC_EVIDENCE", "Diagnostic evidence"), ("ASSESSMENT_ATTEMPT", "Assessment attempt"), ("ASSESSMENT_EVIDENCE", "Assessment evidence"), ("MASTERY_EVIDENCE", "Mastery evidence"), ("LEARNING_SESSION", "Learning session"), ("LEARNING_TURN", "Learning turn"), ("PROFILE_CORRECTION", "Profile correction")], max_length=48)),
                ("source_identifier", models.CharField(max_length=128)),
                ("source_revision", models.CharField(max_length=80)),
                ("semantic_key", models.CharField(max_length=160)),
                ("authority_class", models.CharField(choices=[("DECLARATIVE", "Declarative"), ("INSTITUTIONAL", "Institutional"), ("ASSESSMENT", "Assessment"), ("DIAGNOSTIC", "Diagnostic"), ("OBSERVATIONAL", "Observational"), ("DERIVED", "Derived"), ("INVALIDATED", "Invalidated"), ("SUPERSEDED", "Superseded")], max_length=24)),
                ("occurred_at", models.DateTimeField()),
                ("learner_visible", models.BooleanField(default=True)),
                ("mentor_context_eligible", models.BooleanField(default=False)),
                ("safe_title", models.CharField(max_length=160)),
                ("safe_summary", models.CharField(blank=True, max_length=280)),
                ("controlled_payload", models.JSONField(blank=True, default=dict)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("contested_at", models.DateTimeField(blank=True, null=True)),
                ("hidden_at", models.DateTimeField(blank=True, null=True)),
                ("stale_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("invalidated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("learner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="learning_identity_observations", to=settings.AUTH_USER_MODEL)),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="observations", to="learning_identity.learnerlearningprofile")),
                ("superseded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="superseded_observations", to="learning_identity.learningidentityobservation")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="learning_identity_observations", to="users.institution")),
            ],
            options={"ordering": ["-occurred_at", "-created_at", "id"]},
        ),
        migrations.CreateModel(
            name="LearningIdentityObservationSynchronization",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_domain", models.CharField(choices=[("IDENTITY", "Identity"), ("SELF_STUDY", "Self-study"), ("ACADEMIC", "Academic"), ("LEARNING", "Learning"), ("ASSESSMENT", "Assessment"), ("DIAGNOSTIC", "Diagnostic"), ("INSTITUTION", "Institution"), ("LEARNING_IDENTITY", "Learning identity")], max_length=32)),
                ("source_type", models.CharField(choices=[("LEARNER_DECLARATION", "Learner declaration"), ("ONBOARDING_CONTEXT", "Onboarding context"), ("INSTITUTIONAL_MEMBERSHIP", "Institutional membership"), ("DIAGNOSTIC_ATTEMPT", "Diagnostic attempt"), ("DIAGNOSTIC_EVIDENCE", "Diagnostic evidence"), ("ASSESSMENT_ATTEMPT", "Assessment attempt"), ("ASSESSMENT_EVIDENCE", "Assessment evidence"), ("MASTERY_EVIDENCE", "Mastery evidence"), ("LEARNING_SESSION", "Learning session"), ("LEARNING_TURN", "Learning turn"), ("PROFILE_CORRECTION", "Profile correction")], max_length=48)),
                ("source_identifier", models.CharField(max_length=128)),
                ("source_revision", models.CharField(max_length=80)),
                ("payload_fingerprint", models.CharField(max_length=64)),
                ("status", models.CharField(choices=[("APPLIED", "Applied"), ("UNCHANGED", "Unchanged"), ("BLOCKED", "Blocked"), ("FAILED", "Failed")], max_length=16)),
                ("result_code", models.CharField(choices=[("CREATED", "Created"), ("UPDATED", "Updated"), ("UNCHANGED", "Unchanged"), ("DUPLICATE", "Duplicate"), ("STALE_SOURCE_REVISION", "Stale source revision"), ("UNSUPPORTED_SOURCE_TYPE", "Unsupported source type"), ("SOURCE_UNAVAILABLE", "Source unavailable"), ("SOURCE_WITHDRAWN", "Source withdrawn"), ("INVALID_PROVENANCE", "Invalid provenance"), ("BLOCKED_BY_POLICY", "Blocked by policy"), ("REJECTED_UNSAFE_PAYLOAD", "Rejected unsafe payload"), ("PUBLICATION_DEFERRED", "Publication deferred")], max_length=64)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("idempotency_key", models.CharField(blank=True, max_length=128)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("blocked_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("learner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="learning_identity_observation_synchronizations", to=settings.AUTH_USER_MODEL)),
                ("observation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="synchronizations", to="learning_identity.learningidentityobservation")),
                ("profile", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="observation_synchronizations", to="learning_identity.learnerlearningprofile")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="learning_identity_observation_synchronizations", to="users.institution")),
            ],
            options={"ordering": ["-created_at", "source_domain", "source_type", "source_identifier"]},
        ),
        migrations.CreateModel(
            name="LearningIdentityCorrectionRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action", models.CharField(choices=[("REPLACE_DECLARATION", "Replace declaration"), ("WITHDRAW_DECLARATION", "Withdraw declaration"), ("CONTEST_OBSERVATION", "Contest observation"), ("REQUEST_CORRECTION", "Request correction"), ("HIDE_OBSERVATION", "Hide observation")], max_length=32)),
                ("reason_code", models.CharField(max_length=64)),
                ("learner_note", models.CharField(blank=True, max_length=500)),
                ("status", models.CharField(choices=[("OPEN", "Open"), ("RESOLVED", "Resolved"), ("REJECTED", "Rejected"), ("CANCELLED", "Cancelled")], default="OPEN", max_length=16)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_code", models.CharField(blank=True, max_length=64)),
                ("idempotency_key", models.CharField(blank=True, max_length=128)),
                ("learner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="learning_identity_correction_requests", to=settings.AUTH_USER_MODEL)),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="correction_requests", to="learning_identity.learnerlearningprofile")),
                ("resolved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="resolved_learning_identity_corrections", to=settings.AUTH_USER_MODEL)),
                ("resulting_profile_version", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="correction_requests", to="learning_identity.learningprofileversion")),
                ("target_attribute", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="correction_requests", to="learning_identity.learningidentityattribute")),
                ("target_observation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="correction_requests", to="learning_identity.learningidentityobservation")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="learning_identity_correction_requests", to="users.institution")),
            ],
            options={"ordering": ["-requested_at", "id"]},
        ),
        migrations.CreateModel(
            name="LearnerPreferenceSelection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("preference_key", models.CharField(choices=[("EXPLANATION_MODE", "Explanation mode"), ("TEACHING_PACE", "Teaching pace"), ("INTERFACE_LANGUAGE", "Interface language"), ("SESSION_LENGTH", "Session length"), ("REDUCED_MOTION", "Reduced motion"), ("HIGH_CONTRAST", "High contrast"), ("LARGER_TEXT", "Larger text"), ("CAPTIONS", "Captions")], max_length=40)),
                ("value", models.JSONField()),
                ("value_schema_version", models.PositiveSmallIntegerField(default=1)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("WITHDRAWN", "Withdrawn"), ("SUPERSEDED", "Superseded")], default="ACTIVE", max_length=16)),
                ("explicit", models.BooleanField(default=True)),
                ("mentor_context_eligible", models.BooleanField(default=False)),
                ("teaching_context_eligible", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawal_reason_code", models.CharField(blank=True, max_length=64)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_learning_identity_preferences", to=settings.AUTH_USER_MODEL)),
                ("learner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="learning_identity_preferences", to=settings.AUTH_USER_MODEL)),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="preferences", to="learning_identity.learnerlearningprofile")),
                ("supersedes", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="successor_preferences", to="learning_identity.learnerpreferenceselection")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="learning_identity_preferences", to="users.institution")),
            ],
            options={"ordering": ["preference_key", "-created_at", "id"]},
        ),
        migrations.AddIndex("learningidentityobservation", models.Index(fields=["tenant", "learner", "status"], name="li_obs_tenant_learner_idx")),
        migrations.AddIndex("learningidentityobservation", models.Index(fields=["profile", "status"], name="li_obs_profile_status_idx")),
        migrations.AddIndex("learningidentityobservation", models.Index(fields=["source_domain", "source_type", "source_identifier"], name="li_obs_source_idx")),
        migrations.AddIndex("learningidentityobservation", models.Index(fields=["semantic_key"], name="li_obs_semantic_idx")),
        migrations.AddIndex("learningidentityobservation", models.Index(fields=["mentor_context_eligible", "status"], name="li_obs_mentor_idx")),
        migrations.AddConstraint("learningidentityobservation", models.UniqueConstraint(fields=("source_domain", "source_type", "source_identifier", "source_revision"), name="li_obs_unique_source_rev")),
        migrations.AddConstraint("learningidentityobservation", models.CheckConstraint(condition=Q(observation_type__in=["DIAGNOSTIC_COMPLETED", "LEARNING_SESSION_COMPLETED", "LEARNING_SESSION_RESUMED", "EXPLANATION_REVISITED", "STUDY_ACTIVITY_RECORDED"]), name="li_obs_type_valid")),
        migrations.AddConstraint("learningidentityobservation", models.CheckConstraint(condition=Q(status__in=["ACTIVE", "CONTESTED", "HIDDEN", "STALE", "WITHDRAWN", "INVALIDATED", "SUPERSEDED"]), name="li_obs_status_valid")),
        migrations.AddConstraint("learningidentityobservation", models.CheckConstraint(condition=Q(source_domain__in=["IDENTITY", "SELF_STUDY", "ACADEMIC", "LEARNING", "ASSESSMENT", "DIAGNOSTIC", "INSTITUTION", "LEARNING_IDENTITY"]), name="li_obs_domain_valid")),
        migrations.AddConstraint("learningidentityobservation", models.CheckConstraint(condition=Q(source_type__in=["LEARNER_DECLARATION", "ONBOARDING_CONTEXT", "INSTITUTIONAL_MEMBERSHIP", "DIAGNOSTIC_ATTEMPT", "DIAGNOSTIC_EVIDENCE", "ASSESSMENT_ATTEMPT", "ASSESSMENT_EVIDENCE", "MASTERY_EVIDENCE", "LEARNING_SESSION", "LEARNING_TURN", "PROFILE_CORRECTION"]), name="li_obs_source_type_valid")),
        migrations.AddConstraint("learningidentityobservation", models.CheckConstraint(condition=Q(authority_class__in=["DECLARATIVE", "INSTITUTIONAL", "ASSESSMENT", "DIAGNOSTIC", "OBSERVATIONAL", "DERIVED", "INVALIDATED", "SUPERSEDED"]), name="li_obs_authority_valid")),
        migrations.AddIndex("learningidentityobservationsynchronization", models.Index(fields=["tenant", "learner"], name="li_obssync_tenant_idx")),
        migrations.AddIndex("learningidentityobservationsynchronization", models.Index(fields=["source_domain", "source_type", "source_identifier"], name="li_obssync_source_idx")),
        migrations.AddIndex("learningidentityobservationsynchronization", models.Index(fields=["profile", "status"], name="li_obssync_profile_idx")),
        migrations.AddConstraint("learningidentityobservationsynchronization", models.UniqueConstraint(fields=("source_domain", "source_type", "source_identifier", "source_revision"), name="li_obssync_src_once")),
        migrations.AddConstraint("learningidentityobservationsynchronization", models.UniqueConstraint(fields=("idempotency_key",), condition=~Q(idempotency_key=""), name="li_obssync_idem_once")),
        migrations.AddConstraint("learningidentityobservationsynchronization", models.CheckConstraint(condition=Q(status__in=["APPLIED", "UNCHANGED", "BLOCKED", "FAILED"]), name="li_obssync_status_valid")),
        migrations.AddConstraint("learningidentityobservationsynchronization", models.CheckConstraint(condition=Q(result_code__in=["CREATED", "UPDATED", "UNCHANGED", "DUPLICATE", "STALE_SOURCE_REVISION", "UNSUPPORTED_SOURCE_TYPE", "SOURCE_UNAVAILABLE", "SOURCE_WITHDRAWN", "INVALID_PROVENANCE", "BLOCKED_BY_POLICY", "REJECTED_UNSAFE_PAYLOAD", "PUBLICATION_DEFERRED"]), name="li_obssync_result_valid")),
        migrations.AddConstraint("learningidentityobservationsynchronization", models.CheckConstraint(condition=Q(payload_fingerprint__regex="^[0-9a-f]{64}$"), name="li_obssync_fp_valid")),
        migrations.AddIndex("learningidentitycorrectionrequest", models.Index(fields=["tenant", "learner", "status"], name="li_corr_tenant_status_idx")),
        migrations.AddIndex("learningidentitycorrectionrequest", models.Index(fields=["profile", "status"], name="li_corr_profile_status_idx")),
        migrations.AddIndex("learningidentitycorrectionrequest", models.Index(fields=["action", "status"], name="li_corr_action_status_idx")),
        migrations.AddConstraint("learningidentitycorrectionrequest", models.UniqueConstraint(fields=("idempotency_key",), condition=~Q(idempotency_key=""), name="li_corr_idem_once")),
        migrations.AddConstraint("learningidentitycorrectionrequest", models.CheckConstraint(condition=Q(action__in=["REPLACE_DECLARATION", "WITHDRAW_DECLARATION", "CONTEST_OBSERVATION", "REQUEST_CORRECTION", "HIDE_OBSERVATION"]), name="li_corr_action_valid")),
        migrations.AddConstraint("learningidentitycorrectionrequest", models.CheckConstraint(condition=Q(status__in=["OPEN", "RESOLVED", "REJECTED", "CANCELLED"]), name="li_corr_status_valid")),
        migrations.AddConstraint("learningidentitycorrectionrequest", models.CheckConstraint(condition=(Q(target_attribute__isnull=False) & Q(target_observation__isnull=True)) | (Q(target_attribute__isnull=True) & Q(target_observation__isnull=False)), name="li_corr_one_target")),
        migrations.AddIndex("learnerpreferenceselection", models.Index(fields=["tenant", "learner", "status"], name="li_pref_tenant_status_idx")),
        migrations.AddIndex("learnerpreferenceselection", models.Index(fields=["profile", "preference_key", "status"], name="li_pref_profile_key_idx")),
        migrations.AddIndex("learnerpreferenceselection", models.Index(fields=["mentor_context_eligible", "status"], name="li_pref_mentor_idx")),
        migrations.AddConstraint("learnerpreferenceselection", models.UniqueConstraint(fields=("profile", "preference_key"), condition=Q(status="ACTIVE"), name="li_pref_one_active_key")),
        migrations.AddConstraint("learnerpreferenceselection", models.CheckConstraint(condition=Q(preference_key__in=["EXPLANATION_MODE", "TEACHING_PACE", "INTERFACE_LANGUAGE", "SESSION_LENGTH", "REDUCED_MOTION", "HIGH_CONTRAST", "LARGER_TEXT", "CAPTIONS"]), name="li_pref_key_valid")),
        migrations.AddConstraint("learnerpreferenceselection", models.CheckConstraint(condition=Q(status__in=["ACTIVE", "WITHDRAWN", "SUPERSEDED"]), name="li_pref_status_valid")),
        migrations.AddConstraint("learnerpreferenceselection", models.CheckConstraint(condition=Q(value_schema_version__gt=0), name="li_pref_schema_positive")),
    ]
