import uuid
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q

class MappingRunStatus(models.TextChoices):
 PENDING="PENDING","Pending";BUILDING_EVIDENCE="BUILDING_EVIDENCE","Building evidence";EVIDENCE_READY="EVIDENCE_READY","Evidence ready";MAPPING="MAPPING","Mapping";MAPPINGS_READY="MAPPINGS_READY","Mappings ready";EVALUATING_COVERAGE="EVALUATING_COVERAGE","Evaluating coverage";COMPLETED="COMPLETED","Completed";FAILED="FAILED","Failed";STALE="STALE","Stale";INVALIDATED="INVALIDATED","Invalidated";SUPERSEDED="SUPERSEDED","Superseded"
class EvidenceType(models.TextChoices):
 HEADING="HEADING","Heading";PROSE="PROSE","Prose";DEFINITION="DEFINITION","Definition";EXAMPLE="EXAMPLE","Example";PROCEDURE="PROCEDURE","Procedure";TABLE="TABLE","Table";FIGURE_CAPTION="FIGURE_CAPTION","Figure caption";FORMULA="FORMULA","Formula";QUESTION="QUESTION","Question";ANSWER_EXPLANATION="ANSWER_EXPLANATION","Answer explanation";REFERENCE="REFERENCE","Reference";OTHER="OTHER","Other"
class MappingClass(models.TextChoices):
 DIRECT="DIRECT","Direct";SUPPORTING="SUPPORTING","Supporting";PREREQUISITE_SUPPORT="PREREQUISITE_SUPPORT","Prerequisite support";ASSESSMENT_SUPPORT="ASSESSMENT_SUPPORT","Assessment support";SUPPLEMENTARY="SUPPLEMENTARY","Supplementary";CONFLICTING="CONFLICTING","Conflicting";OUT_OF_SCOPE="OUT_OF_SCOPE","Out of scope"
class MappingStatus(models.TextChoices):PROPOSED="PROPOSED","Proposed";ACCEPTED="ACCEPTED","Accepted";REJECTED="REJECTED","Rejected";STALE="STALE","Stale";INVALIDATED="INVALIDATED","Invalidated"
class CoverageStatus(models.TextChoices):PENDING="PENDING","Pending";RUNNING="RUNNING","Running";COMPLETED="COMPLETED","Completed";FAILED="FAILED","Failed";STALE="STALE","Stale";INVALIDATED="INVALIDATED","Invalidated";SUPERSEDED="SUPERSEDED","Superseded"
class CoverageState(models.TextChoices):UNEVALUATED="UNEVALUATED","Unevaluated";COVERED="COVERED","Covered";PARTIAL="PARTIAL","Partial";MISSING="MISSING","Missing";CONFLICTING="CONFLICTING","Conflicting";OUT_OF_SCOPE="OUT_OF_SCOPE","Out of scope";SUPPLEMENTARY="SUPPLEMENTARY","Supplementary";NOT_APPLICABLE="NOT_APPLICABLE","Not applicable"

class EvidenceMappingRun(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False);tenant=models.ForeignKey("users.Institution",on_delete=models.PROTECT,related_name="evidence_mapping_runs");intent=models.ForeignKey("self_study.SelfStudyIntent",on_delete=models.PROTECT,related_name="evidence_mapping_runs");graph_version=models.ForeignKey("self_study.CurriculumGraphVersion",on_delete=models.PROTECT,related_name="evidence_mapping_runs");status=models.CharField(max_length=32,choices=MappingRunStatus.choices,default=MappingRunStatus.PENDING);stage=models.CharField(max_length=32,default="CREATED");input_manifest=models.JSONField();run_fingerprint=models.CharField(max_length=128);algorithm_versions=models.JSONField();policy_version=models.CharField(max_length=64);requested_by=models.ForeignKey("users.User",on_delete=models.PROTECT,related_name="requested_evidence_mapping_runs");failure_code=models.CharField(max_length=96,blank=True);failure_detail=models.CharField(max_length=500,blank=True);predecessor=models.ForeignKey("self",null=True,blank=True,on_delete=models.PROTECT,related_name="successors");version=models.PositiveIntegerField(default=1);created_at=models.DateTimeField(auto_now_add=True);updated_at=models.DateTimeField(auto_now=True);completed_at=models.DateTimeField(null=True,blank=True)
 resources=models.ManyToManyField("academic.LearningResource",through="EvidenceMappingRunResource")
 class Meta:db_table="self_study_evidence_mapping_run";constraints=[models.UniqueConstraint(fields=["tenant","run_fingerprint"],condition=~Q(status__in=["INVALIDATED","SUPERSEDED"]),name="ssi_mapping_run_fingerprint_unique")];indexes=[models.Index(fields=["intent","status"],name="ssi_mapping_run_status_idx")]
 def save(self,*a,**kw):
  if self.pk:
   old=type(self).objects.filter(pk=self.pk).first()
   frozen=("tenant_id","intent_id","graph_version_id","input_manifest","run_fingerprint","algorithm_versions","policy_version","requested_by_id")
   if old and old.status in {MappingRunStatus.COMPLETED,MappingRunStatus.FAILED,MappingRunStatus.STALE,MappingRunStatus.INVALIDATED,MappingRunStatus.SUPERSEDED} and any(getattr(old,x)!=getattr(self,x) for x in frozen):raise ValidationError("Terminal mapping inputs are immutable.",code="MAPPING_INPUT_MANIFEST_INVALID")
  super().save(*a,**kw)
class EvidenceMappingRunResource(models.Model):
 run=models.ForeignKey(EvidenceMappingRun,on_delete=models.PROTECT,related_name="resource_inputs");resource=models.ForeignKey("academic.LearningResource",on_delete=models.PROTECT);stored_file=models.ForeignKey("storage.StoredFile",on_delete=models.PROTECT);processing_job=models.ForeignKey("content_processing.ContentProcessingJob",on_delete=models.PROTECT);extraction=models.ForeignKey("content_processing.DocumentExtraction",on_delete=models.PROTECT);ordinal=models.PositiveIntegerField();source_status=models.CharField(max_length=32);licence_disposition=models.CharField(max_length=32);safety_disposition=models.CharField(max_length=32)
 class Meta:db_table="self_study_mapping_run_resource";constraints=[models.UniqueConstraint(fields=["run","resource","extraction"],name="ssi_mapping_run_resource_unique")]
class ContentEvidenceUnit(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False);tenant=models.ForeignKey("users.Institution",on_delete=models.PROTECT);run=models.ForeignKey(EvidenceMappingRun,on_delete=models.PROTECT,related_name="evidence_units");source_input=models.ForeignKey(EvidenceMappingRunResource,on_delete=models.PROTECT,related_name="evidence_units");source_block=models.ForeignKey("content_processing.ExtractedBlock",on_delete=models.PROTECT,related_name="curriculum_evidence_units");ordinal=models.PositiveIntegerField();page_reference=models.JSONField();evidence_type=models.CharField(max_length=32,choices=EvidenceType.choices);structural_role=models.CharField(max_length=64);original_language=models.CharField(max_length=16,blank=True);normalized_language=models.CharField(max_length=16,blank=True);source_text=models.TextField();source_text_digest=models.CharField(max_length=128);normalized_text_digest=models.CharField(max_length=128);extraction_confidence=models.DecimalField(max_digits=5,decimal_places=4);citation_snapshot=models.JSONField();licence_disposition=models.CharField(max_length=32);safety_disposition=models.CharField(max_length=32);duplicate_cluster=models.CharField(max_length=128,blank=True);identity_fingerprint=models.CharField(max_length=128);is_substantive=models.BooleanField(default=True);created_at=models.DateTimeField(auto_now_add=True)
 class Meta:db_table="self_study_content_evidence_unit";constraints=[models.UniqueConstraint(fields=["run","identity_fingerprint"],name="ssi_evidence_identity_unique")];indexes=[models.Index(fields=["run","ordinal"],name="ssi_evidence_run_order_idx"),models.Index(fields=["duplicate_cluster"],name="ssi_evidence_duplicate_idx")]
 def save(self,*a,**kw):
  if self.pk and type(self).objects.filter(pk=self.pk).exists():raise ValidationError("Evidence units are immutable.",code="MAPPING_INPUT_MANIFEST_INVALID")
  super().save(*a,**kw)
class EvidenceMappingCandidate(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False);tenant=models.ForeignKey("users.Institution",on_delete=models.PROTECT);run=models.ForeignKey(EvidenceMappingRun,on_delete=models.PROTECT,related_name="candidates");evidence_unit=models.ForeignKey(ContentEvidenceUnit,on_delete=models.PROTECT,related_name="candidates");graph_node=models.ForeignKey("self_study.CurriculumNode",on_delete=models.PROTECT,related_name="evidence_candidates");graph_node_type=models.CharField(max_length=32);method=models.CharField(max_length=32);lexical_score=models.DecimalField(max_digits=6,decimal_places=5);semantic_score=models.DecimalField(max_digits=6,decimal_places=5,null=True);structural_score=models.DecimalField(max_digits=6,decimal_places=5);combined_score=models.DecimalField(max_digits=6,decimal_places=5);rank=models.PositiveSmallIntegerField();rationale_codes=models.JSONField();algorithm_version=models.CharField(max_length=64);candidate_fingerprint=models.CharField(max_length=128);disposition=models.CharField(max_length=32,default="ADVISORY");created_at=models.DateTimeField(auto_now_add=True)
 class Meta:db_table="self_study_evidence_candidate";constraints=[models.UniqueConstraint(fields=["run","candidate_fingerprint"],name="ssi_candidate_fingerprint_unique")];indexes=[models.Index(fields=["run","evidence_unit","rank"],name="ssi_candidate_rank_idx")]
 def save(self,*a,**kw):
  if self.pk and type(self).objects.filter(pk=self.pk).exists():raise ValidationError("Candidates are immutable.",code="MAPPING_INVALIDATED")
  super().save(*a,**kw)
class CurriculumEvidenceMapping(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False);tenant=models.ForeignKey("users.Institution",on_delete=models.PROTECT);run=models.ForeignKey(EvidenceMappingRun,on_delete=models.PROTECT,related_name="mappings");candidate=models.ForeignKey(EvidenceMappingCandidate,null=True,on_delete=models.PROTECT,related_name="decisions");evidence_unit=models.ForeignKey(ContentEvidenceUnit,on_delete=models.PROTECT,related_name="mappings");graph_node=models.ForeignKey("self_study.CurriculumNode",on_delete=models.PROTECT,related_name="evidence_mappings");graph_node_type=models.CharField(max_length=32);classification=models.CharField(max_length=32,choices=MappingClass.choices);status=models.CharField(max_length=16,choices=MappingStatus.choices);confidence_band=models.CharField(max_length=16);scores=models.JSONField();rule_codes=models.JSONField();rationale_codes=models.JSONField();citation_snapshot=models.JSONField();algorithm_version=models.CharField(max_length=64);policy_version=models.CharField(max_length=64);decided_by=models.ForeignKey("users.User",null=True,on_delete=models.PROTECT);mapping_fingerprint=models.CharField(max_length=128);predecessor=models.ForeignKey("self",null=True,on_delete=models.PROTECT,related_name="successors");decided_at=models.DateTimeField(auto_now_add=True)
 class Meta:db_table="self_study_curriculum_evidence_mapping";constraints=[models.UniqueConstraint(fields=["run","mapping_fingerprint"],name="ssi_mapping_fingerprint_unique")];indexes=[models.Index(fields=["run","status"],name="ssi_mapping_status_idx")]
 def save(self,*a,**kw):
  if self.pk and type(self).objects.filter(pk=self.pk).exists():raise ValidationError("Mapping decisions are immutable.",code="MAPPING_INVALIDATED")
  super().save(*a,**kw)
class CurriculumCoverageEvaluation(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False);tenant=models.ForeignKey("users.Institution",on_delete=models.PROTECT);run=models.ForeignKey(EvidenceMappingRun,on_delete=models.PROTECT,related_name="coverage_evaluations");graph_version=models.ForeignKey("self_study.CurriculumGraphVersion",on_delete=models.PROTECT);mapping_set_fingerprint=models.CharField(max_length=128);algorithm_version=models.CharField(max_length=64);policy_version=models.CharField(max_length=64);status=models.CharField(max_length=16,choices=CoverageStatus.choices);evaluation_fingerprint=models.CharField(max_length=128,unique=True);input_summary=models.JSONField();gap_set_fingerprint=models.CharField(max_length=128,blank=True);predecessor=models.ForeignKey("self",null=True,on_delete=models.PROTECT,related_name="successors");created_at=models.DateTimeField(auto_now_add=True);completed_at=models.DateTimeField(null=True)
 class Meta:db_table="self_study_curriculum_coverage";indexes=[models.Index(fields=["run","status"],name="ssi_coverage_status_idx")]
 def save(self,*a,**kw):
  if self.pk and type(self).objects.filter(pk=self.pk,status__in=[CoverageStatus.COMPLETED,CoverageStatus.INVALIDATED,CoverageStatus.SUPERSEDED]).exists():raise ValidationError("Coverage evaluations are immutable.",code="COVERAGE_POLICY_CHANGED")
  super().save(*a,**kw)
class CurriculumNodeCoverage(models.Model):
 evaluation=models.ForeignKey(CurriculumCoverageEvaluation,on_delete=models.PROTECT,related_name="node_results");graph_node=models.ForeignKey("self_study.CurriculumNode",on_delete=models.PROTECT);node_type=models.CharField(max_length=32);state=models.CharField(max_length=16,choices=CoverageState.choices);sufficiency_score=models.DecimalField(max_digits=5,decimal_places=4);direct_count=models.PositiveIntegerField(default=0);supporting_count=models.PositiveIntegerField(default=0);prerequisite_count=models.PositiveIntegerField(default=0);assessment_count=models.PositiveIntegerField(default=0);conflicting_count=models.PositiveIntegerField(default=0);distinct_source_count=models.PositiveIntegerField(default=0);accepted_mapping_count=models.PositiveIntegerField(default=0);excluded_count=models.PositiveIntegerField(default=0);rationale_codes=models.JSONField();blocker_count=models.PositiveIntegerField(default=0);citation_set_fingerprint=models.CharField(max_length=128)
 class Meta:db_table="self_study_curriculum_node_coverage";constraints=[models.UniqueConstraint(fields=["evaluation","graph_node"],name="ssi_node_coverage_unique")]
class CoverageFinding(models.Model):
 evaluation=models.ForeignKey(CurriculumCoverageEvaluation,on_delete=models.PROTECT,related_name="findings");code=models.CharField(max_length=96);severity=models.CharField(max_length=16);blocking=models.BooleanField();scope_type=models.CharField(max_length=32);scope_identifier=models.CharField(max_length=128);graph_node=models.ForeignKey("self_study.CurriculumNode",null=True,on_delete=models.PROTECT);details=models.JSONField();algorithm_version=models.CharField(max_length=64);policy_version=models.CharField(max_length=64);created_at=models.DateTimeField(auto_now_add=True)
 class Meta:db_table="self_study_coverage_finding";indexes=[models.Index(fields=["evaluation","severity"],name="ssi_coverage_finding_idx")]
