from __future__ import annotations

from typing import Protocol, Sequence

from .models import ChunkProjection
from .queries import RetrievalFilter, RetrievalQuery, RetrievalResult


class EmbeddingProvider(Protocol):
    version: str

    def supports(self, purpose: str) -> bool: ...
    def embed(self, text: str) -> Sequence[float]: ...
    def embed_batch(self, texts: Sequence[str]) -> list[Sequence[float]]: ...


class RetrievalIndex(Protocol):
    version: str

    def index(self, chunks: Sequence[ChunkProjection], embeddings: Sequence[Sequence[float]]) -> int: ...
    def update(self, chunk: ChunkProjection, embedding: Sequence[float]) -> None: ...
    def delete(self, chunk_ids: Sequence[str]) -> int: ...
    def search(self, query: RetrievalQuery, embedding: Sequence[float]) -> list[RetrievalResult]: ...
    def filter(self, filters: RetrievalFilter) -> list[RetrievalResult]: ...
    def health(self) -> dict[str, object]: ...


class ChunkRepository(Protocol):
    def replace_collection(self, collection, chunks: Sequence[ChunkProjection]): ...


class CollectionRepository(Protocol):
    def get_by_population(self, population_job_id: str): ...


class IndexJobRepository(Protocol):
    def get_or_create(self, population_job_id: str, retrieval_version: str, embedding_version: str): ...
    def save(self, job): ...


class GroundingPackageRepository(Protocol):
    def save(self, package, citations): ...


class GroundingCitationRepository(Protocol):
    def list_by_package(self, package_id: str): ...
