from __future__ import annotations

from typing import Protocol

from apps.content_processing.domain.models import (
    ContentProcessingJob,
    ProcessingAttempt,
    ProcessingDiagnostic,
    ProcessingStageResult,
)


class ContentProcessingJobRepository(Protocol):
    def get(self, job_id: str) -> ContentProcessingJob: ...
    def get_for_update(self, job_id: str) -> ContentProcessingJob: ...
    def find_active_by_identity(self, resource_id: str, stored_file_id: str | None, pipeline_version: str) -> ContentProcessingJob | None: ...
    def save(self, job: ContentProcessingJob) -> ContentProcessingJob: ...
    def list_for_resource(self, resource_id: str) -> list[ContentProcessingJob]: ...


class ProcessingAttemptRepository(Protocol):
    def append(self, attempt: ProcessingAttempt) -> ProcessingAttempt: ...
    def get_active(self, job_id: str) -> ProcessingAttempt | None: ...
    def get_by_id(self, attempt_id: str) -> ProcessingAttempt: ...
    def list_for_job(self, job_id: str) -> list[ProcessingAttempt]: ...
    def save(self, attempt: ProcessingAttempt) -> ProcessingAttempt: ...


class ProcessingDiagnosticRepository(Protocol):
    def append(self, diagnostic: ProcessingDiagnostic) -> ProcessingDiagnostic: ...
    def list_for_job(self, job_id: str) -> list[ProcessingDiagnostic]: ...
    def list_for_attempt(self, attempt_id: str) -> list[ProcessingDiagnostic]: ...
    def count_warnings(self, job_id: str) -> int: ...


class ProcessingStageResultRepository(Protocol):
    def get(self, job_id: str, attempt_id: str, stage: str, result_version: int) -> ProcessingStageResult | None: ...
    def exists(self, job_id: str, attempt_id: str, stage: str, result_version: int) -> bool: ...
    def save(self, result: ProcessingStageResult) -> ProcessingStageResult: ...


class DocumentHierarchyRepository(Protocol):
    def get_by_id(self, hierarchy_id: str): ...
    def get_for_job_attempt(self, job_id: str, attempt_id: str): ...
    def find_existing(self, **identity): ...
    def save(self, hierarchy): ...


class DocumentSegmentationRepository(Protocol):
    def get_by_id(self, segmentation_id: str): ...
    def get_for_job_attempt(self, job_id: str, attempt_id: str): ...
    def find_existing(self, **identity): ...
    def save(self, segmentation): ...


class SemanticSegmentRepository(Protocol):
    def list_for_segmentation(self, segmentation_id: str): ...
    def list_for_node(self, node_id: str): ...
    def get_in_order(self, segmentation_id: str): ...


class AcademicImportProposalRepository(Protocol):
    def get_by_id(self, proposal_id: str): ...
    def get_for_job_attempt(self, job_id: str, attempt_id: str): ...
    def find_existing(self, **identity): ...
    def save(self, proposal): ...


class AcademicPopulationJobRepository(Protocol):
    def get_for_proposal(self, proposal_id: str): ...
    def find_existing(self, **identity): ...
    def save(self, population_job): ...
