# Generated by Django 5.2.15 on 2026-07-04 19:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoredFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=512)),
                ("stored_filename", models.CharField(max_length=512)),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("size_bytes", models.BigIntegerField()),
                ("checksum", models.CharField(blank=True, max_length=128, null=True)),
                ("provider", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "storage_storedfile",
                "ordering": ["-created_at"],
            },
        ),
    ]
