# Generated by Django 5.2.16 on 2026-08-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
        ("users", "0003_institution_institutionmembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="storedfile",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stored_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="storedfile",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stored_files",
                to="users.institution",
            ),
        ),
        migrations.AddField(
            model_name="storedfile",
            name="security_scope",
            field=models.CharField(
                choices=[
                    ("private_learner", "Private learner"),
                    ("institution_shared", "Institution shared"),
                    ("system_managed", "System managed"),
                    ("legacy_restricted", "Legacy restricted"),
                ],
                default="private_learner",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="storedfile",
            index=models.Index(fields=["owner", "security_scope"], name="storedfile_owner_scope_idx"),
        ),
        migrations.AddIndex(
            model_name="storedfile",
            index=models.Index(fields=["tenant", "security_scope"], name="storedfile_tenant_scope_idx"),
        ),
    ]
