from __future__ import annotations

from typing import Protocol

from apps.assessments.domain.models import LearningEvidence
from apps.remediation.domain.models import RemediationActivity, RemediationAttempt, RemediationOutcome, RemediationPlan, RemediationRecommendation
from apps.users.domain.models import User


class RemediationPlanRepository(Protocol):
    def add(self, plan: RemediationPlan) -> RemediationPlan: ...
    def save(self, plan: RemediationPlan) -> RemediationPlan: ...
    def get(self, plan_id: str) -> RemediationPlan: ...
    def list_for_learner(self, learner: User) -> list[RemediationPlan]: ...
    def list_by_status(self, status: str) -> list[RemediationPlan]: ...


class RecommendationRepository(Protocol):
    def add(self, recommendation: RemediationRecommendation) -> RemediationRecommendation: ...
    def list_for_plan(self, plan: RemediationPlan) -> list[RemediationRecommendation]: ...


class ActivityRepository(Protocol):
    def add(self, activity: RemediationActivity) -> RemediationActivity: ...
    def save(self, activity: RemediationActivity) -> RemediationActivity: ...
    def list_for_plan(self, plan: RemediationPlan) -> list[RemediationActivity]: ...


class AttemptRepository(Protocol):
    def add(self, attempt: RemediationAttempt) -> RemediationAttempt: ...
    def save(self, attempt: RemediationAttempt) -> RemediationAttempt: ...
    def list_for_activity(self, activity: RemediationActivity) -> list[RemediationAttempt]: ...


class OutcomeRepository(Protocol):
    def add(self, outcome: RemediationOutcome) -> RemediationOutcome: ...
    def list_for_plan(self, plan: RemediationPlan) -> list[RemediationOutcome]: ...


class EvidenceRepository(Protocol):
    def list_for_learner(self, learner: User) -> list[LearningEvidence]: ...
    def list_remediation_candidates_for_learner(self, learner: User) -> list[LearningEvidence]: ...


__all__ = [
    "RemediationPlanRepository",
    "RecommendationRepository",
    "ActivityRepository",
    "AttemptRepository",
    "OutcomeRepository",
    "EvidenceRepository",
]
