import uuid
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

STRUCTURAL_ROLES = [(value, value.replace("_", " ").title()) for value in ("root","body","front_matter","back_matter","navigation","title_page","copyright","dedication","preface","foreword","acknowledgements","table_of_contents","list_of_figures","list_of_tables","glossary","bibliography","references","index","appendix","summary","exercise","assessment","boilerplate","probable_noise","unclassified")]
HIERARCHY_STRENGTHS = [("source_explicit","Source Explicit"),("strongly_inferred","Strongly Inferred"),("heuristically_inferred","Heuristically Inferred"),("fallback_generated","Fallback Generated"),("unresolved","Unresolved")]
DISPOSITIONS = [(value, value.replace("_", " ").title()) for value in ("included","excluded","review_required","unresolved")]
NODE_BLOCK_ROLES = [(value, value.title()) for value in ("heading","body","caption","table","figure","list","supporting","excluded","unresolved")]
SEGMENT_TYPES = [(value, value.replace("_", " ").title()) for value in ("overview","definition","explanation","example","procedure","case_study","theorem","proof","formula","table","figure","summary","exercise","question","answer","reference","list","paragraph_group","mixed_content","unknown")]
SEGMENT_STRENGTHS = [("source_explicit","Source Explicit"),("structure_derived","Structure Derived"),("lexically_inferred","Lexically Inferred"),("fallback_generated","Fallback Generated"),("unresolved","Unresolved")]
SEGMENT_BLOCK_ROLES = [(value, value.replace("_", " ").title()) for value in ("title","body","table","figure","caption","list","formula","supporting_context")]


class Migration(migrations.Migration):
    dependencies = [("content_processing", "0002_layout_aware_extraction")]
    operations = [
        migrations.CreateModel(name="DocumentHierarchy", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("pipeline_version", models.CharField(max_length=100)),
            ("reconstructor_name", models.CharField(max_length=128)), ("reconstructor_version", models.CharField(max_length=64)), ("configuration_version", models.CharField(max_length=64)),
            ("node_count", models.PositiveIntegerField(default=0)), ("maximum_depth", models.PositiveIntegerField(default=0)), ("front_matter_detected", models.BooleanField(default=False)),
            ("back_matter_detected", models.BooleanField(default=False)), ("navigation_content_detected", models.BooleanField(default=False)), ("noise_candidates_detected", models.BooleanField(default=False)),
            ("unresolved_block_count", models.PositiveIntegerField(default=0)), ("review_recommended", models.BooleanField(default=False)), ("confidence", models.FloatField(default=0)),
            ("warning_count", models.PositiveIntegerField(default=0)), ("result_checksum", models.CharField(max_length=128)), ("created_at", models.DateTimeField(auto_now_add=True)), ("completed_at", models.DateTimeField(default=django.utils.timezone.now)),
            ("attempt", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="document_hierarchies", to="content_processing.processingattempt")),
            ("document_extraction", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="hierarchies", to="content_processing.documentextraction")),
            ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="document_hierarchies", to="content_processing.contentprocessingjob")),
            ("resource", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="document_hierarchies", to="academic.learningresource")),
            ("source_document_profile", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="hierarchies", to="content_processing.sourcedocumentprofile")),
            ("stored_file", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="document_hierarchies", to="storage.storedfile")),
        ], options={"db_table": "content_processing_document_hierarchy"}),
        migrations.CreateModel(name="DocumentHierarchyNode", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ("node_type", models.CharField(choices=[("document","Document"),("part","Part"),("chapter","Chapter"),("section","Section"),("subsection","Subsection"),("topic_group","Topic Group"),("paragraph_group","Paragraph Group"),("list_group","List Group"),("table_group","Table Group"),("figure_group","Figure Group"),("appendix","Appendix"),("reference_group","Reference Group"),("exercise_group","Exercise Group"),("unknown","Unknown")], max_length=32)),
            ("structural_role", models.CharField(choices=STRUCTURAL_ROLES, max_length=32)), ("title", models.CharField(blank=True, max_length=512)), ("normalized_title", models.CharField(blank=True, max_length=512)),
            ("depth", models.PositiveIntegerField()), ("ordinal", models.PositiveIntegerField()), ("path", models.CharField(max_length=512)), ("start_sequence", models.PositiveIntegerField()), ("end_sequence", models.PositiveIntegerField()),
            ("source_page_start", models.PositiveIntegerField(blank=True, null=True)), ("source_page_end", models.PositiveIntegerField(blank=True, null=True)), ("content_block_count", models.PositiveIntegerField(default=0)),
            ("confidence", models.FloatField(default=0)), ("evidence_strength", models.CharField(choices=HIERARCHY_STRENGTHS, max_length=32)), ("evidence", models.JSONField(blank=True, default=dict)), ("metadata", models.JSONField(blank=True, default=dict)), ("created_at", models.DateTimeField(auto_now_add=True)),
            ("attempt", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hierarchy_nodes", to="content_processing.processingattempt")),
            ("document_hierarchy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="nodes", to="content_processing.documenthierarchy")),
            ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hierarchy_nodes", to="content_processing.contentprocessingjob")),
            ("parent_node", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="children", to="content_processing.documenthierarchynode")),
        ], options={"db_table": "content_processing_hierarchy_node", "ordering": ["ordinal"]}),
        migrations.AddField(model_name="documenthierarchy", name="root_node", field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="root_for_hierarchy", to="content_processing.documenthierarchynode")),
        migrations.CreateModel(name="HierarchyNodeBlock", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("relationship_role", models.CharField(choices=NODE_BLOCK_ROLES, max_length=32)), ("ordinal", models.PositiveIntegerField()), ("included_in_content", models.BooleanField(default=True)), ("classification_reason", models.CharField(max_length=128)), ("confidence", models.FloatField(default=0)), ("created_at", models.DateTimeField(auto_now_add=True)),
            ("document_hierarchy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="node_block_relationships", to="content_processing.documenthierarchy")), ("extracted_block", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="hierarchy_relationships", to="content_processing.extractedblock")), ("node", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="block_relationships", to="content_processing.documenthierarchynode")),
        ], options={"db_table": "content_processing_hierarchy_node_block"}),
        migrations.CreateModel(name="HierarchyBlockClassification", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("disposition", models.CharField(choices=DISPOSITIONS, max_length=32)), ("structural_role", models.CharField(choices=STRUCTURAL_ROLES, max_length=32)), ("reason_code", models.CharField(max_length=128)), ("confidence", models.FloatField(default=0)), ("evidence", models.JSONField(blank=True, default=dict)), ("created_at", models.DateTimeField(auto_now_add=True)),
            ("document_hierarchy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="block_classifications", to="content_processing.documenthierarchy")), ("extracted_block", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="structural_classifications", to="content_processing.extractedblock")),
        ], options={"db_table": "content_processing_hierarchy_block_classification"}),
        migrations.CreateModel(name="DocumentSegmentation", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("pipeline_version", models.CharField(max_length=100)), ("segmenter_name", models.CharField(max_length=128)), ("segmenter_version", models.CharField(max_length=64)), ("configuration_version", models.CharField(max_length=64)),
            ("segment_count", models.PositiveIntegerField(default=0)), ("body_segment_count", models.PositiveIntegerField(default=0)), ("excluded_region_count", models.PositiveIntegerField(default=0)), ("unresolved_content_count", models.PositiveIntegerField(default=0)), ("review_recommended", models.BooleanField(default=False)), ("confidence", models.FloatField(default=0)), ("warning_count", models.PositiveIntegerField(default=0)), ("result_checksum", models.CharField(max_length=128)), ("created_at", models.DateTimeField(auto_now_add=True)), ("completed_at", models.DateTimeField(default=django.utils.timezone.now)),
            ("attempt", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="document_segmentations", to="content_processing.processingattempt")), ("document_extraction", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="segmentations", to="content_processing.documentextraction")), ("document_hierarchy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="segmentations", to="content_processing.documenthierarchy")), ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="document_segmentations", to="content_processing.contentprocessingjob")), ("resource", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="document_segmentations", to="academic.learningresource")), ("stored_file", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="document_segmentations", to="storage.storedfile")),
        ], options={"db_table": "content_processing_document_segmentation"}),
        migrations.CreateModel(name="SemanticSegment", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("segment_type", models.CharField(choices=SEGMENT_TYPES, max_length=32)), ("title", models.CharField(blank=True, max_length=512)), ("normalized_text", models.TextField(blank=True)), ("ordinal", models.PositiveIntegerField()), ("source_block_start", models.PositiveIntegerField()), ("source_block_end", models.PositiveIntegerField()), ("source_page_start", models.PositiveIntegerField(blank=True, null=True)), ("source_page_end", models.PositiveIntegerField(blank=True, null=True)), ("character_count", models.PositiveIntegerField(default=0)), ("word_count", models.PositiveIntegerField(default=0)), ("token_estimate", models.PositiveIntegerField(default=0)), ("confidence", models.FloatField(default=0)), ("evidence_strength", models.CharField(choices=SEGMENT_STRENGTHS, max_length=32)), ("evidence", models.JSONField(blank=True, default=dict)), ("metadata", models.JSONField(blank=True, default=dict)), ("created_at", models.DateTimeField(auto_now_add=True)),
            ("attempt", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="semantic_segments", to="content_processing.processingattempt")), ("document_hierarchy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="semantic_segments", to="content_processing.documenthierarchy")), ("document_segmentation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="segments", to="content_processing.documentsegmentation")), ("hierarchy_node", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="semantic_segments", to="content_processing.documenthierarchynode")), ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="semantic_segments", to="content_processing.contentprocessingjob")), ("resource", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="semantic_segments", to="academic.learningresource")),
        ], options={"db_table": "content_processing_semantic_segment", "ordering": ["ordinal"]}),
        migrations.CreateModel(name="SemanticSegmentBlock", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("relationship_role", models.CharField(choices=SEGMENT_BLOCK_ROLES, max_length=32)), ("ordinal", models.PositiveIntegerField()), ("created_at", models.DateTimeField(auto_now_add=True)),
            ("document_segmentation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="segment_block_relationships", to="content_processing.documentsegmentation")), ("extracted_block", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="semantic_relationships", to="content_processing.extractedblock")), ("semantic_segment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="block_relationships", to="content_processing.semanticsegment")),
        ], options={"db_table": "content_processing_semantic_segment_block"}),
        migrations.AddConstraint(model_name="documenthierarchy", constraint=models.UniqueConstraint(fields=("job","attempt","document_extraction","pipeline_version","reconstructor_version","configuration_version"), name="cp_hierarchy_identity_unique")),
        migrations.AddConstraint(model_name="documenthierarchy", constraint=models.CheckConstraint(condition=models.Q(confidence__gte=0, confidence__lte=1), name="cp_hierarchy_confidence_range")),
        migrations.AddConstraint(model_name="documenthierarchynode", constraint=models.UniqueConstraint(fields=("document_hierarchy","ordinal"), name="cp_hierarchy_node_ordinal_unique")),
        migrations.AddConstraint(model_name="documenthierarchynode", constraint=models.UniqueConstraint(fields=("document_hierarchy","path"), name="cp_hierarchy_node_path_unique")),
        migrations.AddConstraint(model_name="documenthierarchynode", constraint=models.UniqueConstraint(condition=models.Q(structural_role="root"), fields=("document_hierarchy",), name="cp_hierarchy_one_root")),
        migrations.AddConstraint(model_name="documenthierarchynode", constraint=models.CheckConstraint(condition=models.Q(confidence__gte=0, confidence__lte=1), name="cp_hierarchy_node_confidence_range")),
        migrations.AddConstraint(model_name="documenthierarchynode", constraint=models.CheckConstraint(condition=models.Q(end_sequence__gte=models.F("start_sequence")), name="cp_hierarchy_node_range_valid")),
        migrations.AddConstraint(model_name="hierarchynodeblock", constraint=models.UniqueConstraint(fields=("node","extracted_block","relationship_role"), name="cp_node_block_unique")),
        migrations.AddConstraint(model_name="hierarchyblockclassification", constraint=models.UniqueConstraint(fields=("document_hierarchy","extracted_block"), name="cp_block_classification_unique")),
        migrations.AddConstraint(model_name="documentsegmentation", constraint=models.UniqueConstraint(fields=("job","attempt","document_hierarchy","pipeline_version","segmenter_version","configuration_version"), name="cp_segmentation_identity_unique")),
        migrations.AddConstraint(model_name="documentsegmentation", constraint=models.CheckConstraint(condition=models.Q(confidence__gte=0, confidence__lte=1), name="cp_segmentation_confidence_range")),
        migrations.AddConstraint(model_name="semanticsegment", constraint=models.UniqueConstraint(fields=("document_segmentation","ordinal"), name="cp_segment_ordinal_unique")),
        migrations.AddConstraint(model_name="semanticsegment", constraint=models.CheckConstraint(condition=models.Q(source_block_end__gte=models.F("source_block_start")), name="cp_segment_range_valid")),
        migrations.AddConstraint(model_name="semanticsegment", constraint=models.CheckConstraint(condition=models.Q(confidence__gte=0, confidence__lte=1), name="cp_segment_confidence_range")),
        migrations.AddConstraint(model_name="semanticsegmentblock", constraint=models.UniqueConstraint(fields=("semantic_segment","extracted_block","relationship_role"), name="cp_segment_block_unique")),
    ]
