import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

REVIEW_STATES = [(value, value.replace("_", " ").title()) for value in ("draft","ready_for_review","under_review","approved","approved_with_edits","rejected","superseded","archived")]
DECISIONS = [(value, value.replace("_", " ").title()) for value in ("pending","approved","approved_with_edits","rejected","superseded")]
POPULATION_STATES = [(value, value.replace("_", " ").title()) for value in ("not_ready","ready_for_population","population_in_progress","populated","population_failed")]
POPULATION_JOB_STATES = [(value, value.replace("_", " ").title()) for value in ("ready_for_population","population_in_progress","populated","population_failed")]


class Migration(migrations.Migration):
    dependencies = [("content_processing", "0003_hierarchy_and_segmentation"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="AcademicImportProposal", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("pipeline_version", models.CharField(max_length=100)), ("proposal_engine", models.CharField(max_length=128)), ("proposal_version", models.CharField(max_length=64)), ("configuration_version", models.CharField(max_length=64)),
            ("review_state", models.CharField(choices=REVIEW_STATES, default="draft", max_length=32)), ("decision", models.CharField(choices=DECISIONS, default="pending", max_length=32)), ("population_state", models.CharField(choices=POPULATION_STATES, default="not_ready", max_length=32)), ("confidence", models.FloatField(default=0)), ("statistics", models.JSONField(blank=True, default=dict)), ("warnings", models.JSONField(blank=True, default=list)), ("review_required", models.BooleanField(default=True)), ("result_checksum", models.CharField(max_length=128)), ("created_at", models.DateTimeField(auto_now_add=True)), ("completed_at", models.DateTimeField(default=django.utils.timezone.now)),
            ("attempt", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="academic_import_proposals", to="content_processing.processingattempt")), ("document_hierarchy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="academic_import_proposals", to="content_processing.documenthierarchy")), ("document_segmentation", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="academic_import_proposals", to="content_processing.documentsegmentation")), ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="academic_import_proposals", to="content_processing.contentprocessingjob")), ("resource", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="academic_import_proposals", to="academic.learningresource")),
        ], options={"db_table": "content_processing_academic_import_proposal"}),
        migrations.CreateModel(name="ProposedSection", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=255)), ("normalized_title", models.CharField(max_length=255)), ("parent_reference", models.CharField(blank=True, max_length=128)), ("ordering", models.PositiveIntegerField()), ("source_page_start", models.PositiveIntegerField(blank=True, null=True)), ("source_page_end", models.PositiveIntegerField(blank=True, null=True)), ("confidence", models.FloatField(default=0)), ("warnings", models.JSONField(blank=True, default=list)), ("evidence", models.JSONField(blank=True, default=dict)), ("created_at", models.DateTimeField(auto_now_add=True)),
            ("hierarchy_node", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="proposed_sections", to="content_processing.documenthierarchynode")), ("populated_section", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="source_proposal_section", to="academic.contentsection")), ("proposal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="proposed_sections", to="content_processing.academicimportproposal")),
        ], options={"db_table": "content_processing_proposed_section"}),
        migrations.CreateModel(name="ProposedConcept", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=255)), ("normalized_title", models.CharField(max_length=255)), ("supporting_text", models.TextField()), ("explanation", models.TextField()), ("ordering", models.PositiveIntegerField()), ("source_page_start", models.PositiveIntegerField(blank=True, null=True)), ("source_page_end", models.PositiveIntegerField(blank=True, null=True)), ("confidence", models.FloatField(default=0)), ("warnings", models.JSONField(blank=True, default=list)), ("evidence", models.JSONField(blank=True, default=dict)), ("created_at", models.DateTimeField(auto_now_add=True)),
            ("populated_concept", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="source_proposal_concept", to="academic.contentconcept")), ("proposal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="proposed_concepts", to="content_processing.academicimportproposal")), ("proposed_section", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="proposed_concepts", to="content_processing.proposedsection")), ("semantic_segment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="proposed_concepts", to="content_processing.semanticsegment")),
        ], options={"db_table": "content_processing_proposed_concept"}),
        migrations.CreateModel(name="ProposalEvidence", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("item_type", models.CharField(choices=[("section","Section"),("concept","Concept")], max_length=16)), ("source_page_start", models.PositiveIntegerField(blank=True, null=True)), ("source_page_end", models.PositiveIntegerField(blank=True, null=True)), ("evidence_strength", models.CharField(max_length=32)), ("confidence", models.FloatField(default=0)), ("reasoning_metadata", models.JSONField(blank=True, default=dict)), ("created_at", models.DateTimeField(auto_now_add=True)),
            ("extracted_block", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="proposal_evidence", to="content_processing.extractedblock")), ("hierarchy_node", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="proposal_evidence", to="content_processing.documenthierarchynode")), ("proposal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evidence_records", to="content_processing.academicimportproposal")), ("proposed_concept", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="evidence_records", to="content_processing.proposedconcept")), ("proposed_section", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="evidence_records", to="content_processing.proposedsection")), ("semantic_segment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="proposal_evidence", to="content_processing.semanticsegment")),
        ], options={"db_table": "content_processing_proposal_evidence"}),
        migrations.CreateModel(name="ProposalValidation", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("code", models.CharField(max_length=128)), ("severity", models.CharField(max_length=16)), ("passed", models.BooleanField(default=True)), ("public_message", models.TextField()), ("details", models.JSONField(blank=True, default=dict)), ("created_at", models.DateTimeField(auto_now_add=True)), ("proposal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="validations", to="content_processing.academicimportproposal")),
        ], options={"db_table": "content_processing_proposal_validation"}),
        migrations.CreateModel(name="ProposalDecision", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("decision", models.CharField(choices=DECISIONS, max_length=32)), ("reason", models.TextField(blank=True)), ("metadata", models.JSONField(blank=True, default=dict)), ("created_at", models.DateTimeField(auto_now_add=True)), ("decided_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="academic_import_decisions", to=settings.AUTH_USER_MODEL)), ("proposal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="decisions", to="content_processing.academicimportproposal")),
        ], options={"db_table": "content_processing_proposal_decision", "ordering": ["created_at"]}),
        migrations.CreateModel(name="ProposalRevision", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("revision_number", models.PositiveIntegerField()), ("changes", models.JSONField(default=dict)), ("reason", models.TextField(blank=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("changed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="academic_import_revisions", to=settings.AUTH_USER_MODEL)), ("proposal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="revisions", to="content_processing.academicimportproposal")),
        ], options={"db_table": "content_processing_proposal_revision"}),
        migrations.CreateModel(name="AcademicPopulationJob", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("population_version", models.CharField(max_length=64)), ("academic_schema_version", models.CharField(max_length=64)), ("status", models.CharField(choices=POPULATION_JOB_STATES, default="ready_for_population", max_length=32)), ("created_sections", models.PositiveIntegerField(default=0)), ("updated_sections", models.PositiveIntegerField(default=0)), ("created_concepts", models.PositiveIntegerField(default=0)), ("updated_concepts", models.PositiveIntegerField(default=0)), ("warnings", models.JSONField(blank=True, default=list)), ("statistics", models.JSONField(blank=True, default=dict)), ("failure_code", models.CharField(blank=True, max_length=128)), ("checksum", models.CharField(blank=True, max_length=128)), ("started_at", models.DateTimeField(blank=True, null=True)), ("completed_at", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)),
            ("attempt", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="academic_population_jobs", to="content_processing.processingattempt")), ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="academic_population_jobs", to="content_processing.contentprocessingjob")), ("proposal", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="population_jobs", to="content_processing.academicimportproposal")),
        ], options={"db_table": "content_processing_academic_population_job"}),
        migrations.AddConstraint(model_name="academicimportproposal", constraint=models.UniqueConstraint(fields=("job","attempt","document_hierarchy","document_segmentation","proposal_version","pipeline_version"), name="cp_proposal_identity_unique")),
        migrations.AddConstraint(model_name="academicimportproposal", constraint=models.CheckConstraint(condition=models.Q(confidence__gte=0, confidence__lte=1), name="cp_proposal_confidence_range")),
        migrations.AddConstraint(model_name="proposedsection", constraint=models.UniqueConstraint(fields=("proposal","ordering"), name="cp_proposed_section_order_unique")),
        migrations.AddConstraint(model_name="proposedsection", constraint=models.UniqueConstraint(fields=("proposal","normalized_title"), name="cp_proposed_section_title_unique")),
        migrations.AddConstraint(model_name="proposedsection", constraint=models.CheckConstraint(condition=models.Q(confidence__gte=0, confidence__lte=1), name="cp_proposed_section_confidence_range")),
        migrations.AddConstraint(model_name="proposedsection", constraint=models.CheckConstraint(condition=models.Q(ordering__gte=1), name="cp_proposed_section_order_gte_1")),
        migrations.AddConstraint(model_name="proposedconcept", constraint=models.UniqueConstraint(fields=("proposed_section","ordering"), name="cp_proposed_concept_order_unique")),
        migrations.AddConstraint(model_name="proposedconcept", constraint=models.UniqueConstraint(fields=("proposed_section","normalized_title"), name="cp_proposed_concept_title_unique")),
        migrations.AddConstraint(model_name="proposedconcept", constraint=models.CheckConstraint(condition=models.Q(confidence__gte=0, confidence__lte=1), name="cp_proposed_concept_confidence_range")),
        migrations.AddConstraint(model_name="proposedconcept", constraint=models.CheckConstraint(condition=models.Q(ordering__gte=1), name="cp_proposed_concept_order_gte_1")),
        migrations.AddConstraint(model_name="proposalevidence", constraint=models.UniqueConstraint(fields=("proposal","item_type","proposed_section","proposed_concept","semantic_segment","extracted_block"), name="cp_proposal_evidence_unique")),
        migrations.AddConstraint(model_name="proposalevidence", constraint=models.CheckConstraint(condition=models.Q(confidence__gte=0, confidence__lte=1), name="cp_proposal_evidence_confidence_range")),
        migrations.AddConstraint(model_name="proposalrevision", constraint=models.UniqueConstraint(fields=("proposal","revision_number"), name="cp_proposal_revision_unique")),
        migrations.AddConstraint(model_name="academicpopulationjob", constraint=models.UniqueConstraint(fields=("proposal","population_version","academic_schema_version"), name="cp_population_identity_unique")),
    ]
