# Generated by Django's migration system for PI-8C.1
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ("users", "0003_institution_institutionmembership"),
        ("academic", "0006_content_review_fields"),
    ]

    operations = [
        # Educational Organization
        migrations.CreateModel(
            name="EducationalOrganization",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("organization_type", models.CharField(max_length=100)),
                ("status", models.CharField(choices=[("active", "Active"), ("suspended", "Suspended"), ("archived", "Archived")], default="active", max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("institution", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="educational_organizations", to="users.institution")),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="children", to="educational_organization.educationalorganization")),
            ],
            options={
                "db_table": "educational_organization",
            },
        ),
        # Academic Unit
        migrations.CreateModel(
            name="AcademicUnit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("unit_type", models.CharField(max_length=100)),
                ("status", models.CharField(choices=[("active", "Active"), ("suspended", "Suspended"), ("archived", "Archived")], default="active", max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("institution", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="academic_units", to="users.institution")),
                ("educational_organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="academic_units", to="educational_organization.educationalorganization")),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="children", to="educational_organization.academicunit")),
            ],
            options={
                "db_table": "academic_unit",
            },
        ),
        # Programme
        migrations.CreateModel(
            name="Programme",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("qualification", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("suspended", "Suspended"), ("archived", "Archived")], default="draft", max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("institution", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="programmes", to="users.institution")),
                ("educational_organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="programmes", to="educational_organization.educationalorganization")),
                ("academic_unit", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="programmes", to="educational_organization.academicunit")),
            ],
            options={
                "db_table": "programme",
            },
        ),
        # Academic Period
        migrations.CreateModel(
            name="AcademicPeriod",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("period_type", models.CharField(max_length=100)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("status", models.CharField(choices=[("upcoming", "Upcoming"), ("open", "Open"), ("closed", "Closed"), ("archived", "Archived")], default="upcoming", max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("institution", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="academic_periods", to="users.institution")),
                ("educational_organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="academic_periods", to="educational_organization.educationalorganization")),
            ],
            options={
                "db_table": "academic_period",
            },
        ),
        # Course Offering
        migrations.CreateModel(
            name="CourseOffering",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("suspended", "Suspended"), ("archived", "Archived")], default="draft", max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("institution", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="course_offerings", to="users.institution")),
                ("educational_organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="course_offerings", to="educational_organization.educationalorganization")),
                ("academic_unit", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="course_offerings", to="educational_organization.academicunit")),
                ("programme", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="course_offerings", to="educational_organization.programme")),
                ("academic_period", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="course_offerings", to="educational_organization.academicperiod")),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="course_offerings", to="academic.subject")),
            ],
            options={
                "db_table": "course_offering",
            },
        ),
        # Class Group
        migrations.CreateModel(
            name="ClassGroup",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("suspended", "Suspended"), ("archived", "Archived"), ("completed", "Completed")], default="draft", max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("institution", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="class_groups", to="users.institution")),
                ("educational_organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="class_groups", to="educational_organization.educationalorganization")),
                ("academic_unit", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="class_groups", to="educational_organization.academicunit")),
                ("course_offering", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="class_groups", to="educational_organization.courseoffering")),
            ],
            options={
                "db_table": "class_group",
            },
        ),
        # Teaching Assignment
        migrations.CreateModel(
            name="TeachingAssignment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ("effective_from", models.DateTimeField()),
                ("effective_until", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("active", "Active"), ("suspended", "Suspended"), ("expired", "Expired")], default="pending", max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("institution", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_assignments", to="users.institution")),
                ("teacher", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_assignments", to="users.user")),
                ("class_group", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_assignments", to="educational_organization.classgroup")),
                ("course_offering", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_assignments", to="educational_organization.courseoffering")),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_assignments", to="academic.subject")),
            ],
            options={
                "db_table": "teaching_assignment",
            },
        ),
        # User Capability
        migrations.CreateModel(
            name="UserCapability",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ("capability_code", models.CharField(max_length=128)),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("granted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="granted_capabilities", to="users.user")),
                ("institution", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_capabilities", to="users.institution")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="capabilities", to="users.user")),
            ],
            options={
                "db_table": "user_capability",
            },
        ),
        # Add indexes after all fields are created
        migrations.AddIndex(
            model_name="educationalorganization",
            index=models.Index(fields=["institution", "status"], name="edu_org_inst_status_idx"),
        ),
        migrations.AddIndex(
            model_name="educationalorganization",
            index=models.Index(fields=["parent"], name="edu_org_parent_idx"),
        ),
        migrations.AddIndex(
            model_name="educationalorganization",
            index=models.Index(fields=["slug"], name="edu_org_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="academicunit",
            index=models.Index(fields=["institution", "status"], name="acad_unit_inst_status_idx"),
        ),
        migrations.AddIndex(
            model_name="academicunit",
            index=models.Index(fields=["educational_organization", "status"], name="acad_unit_org_status_idx"),
        ),
        migrations.AddIndex(
            model_name="academicunit",
            index=models.Index(fields=["parent"], name="acad_unit_parent_idx"),
        ),
        migrations.AddIndex(
            model_name="academicunit",
            index=models.Index(fields=["slug"], name="acad_unit_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="programme",
            index=models.Index(fields=["institution", "status"], name="prog_inst_status_idx"),
        ),
        migrations.AddIndex(
            model_name="programme",
            index=models.Index(fields=["academic_unit", "status"], name="prog_unit_status_idx"),
        ),
        migrations.AddIndex(
            model_name="programme",
            index=models.Index(fields=["slug"], name="prog_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="academicperiod",
            index=models.Index(fields=["institution", "status"], name="acad_period_inst_status_idx"),
        ),
        migrations.AddIndex(
            model_name="academicperiod",
            index=models.Index(fields=["educational_organization", "status"], name="acad_period_org_status_idx"),
        ),
        migrations.AddIndex(
            model_name="academicperiod",
            index=models.Index(fields=["slug"], name="acad_period_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="courseoffering",
            index=models.Index(fields=["institution", "status"], name="co_inst_status_idx"),
        ),
        migrations.AddIndex(
            model_name="courseoffering",
            index=models.Index(fields=["programme", "status"], name="co_prog_status_idx"),
        ),
        migrations.AddIndex(
            model_name="courseoffering",
            index=models.Index(fields=["academic_period", "status"], name="co_period_status_idx"),
        ),
        migrations.AddIndex(
            model_name="courseoffering",
            index=models.Index(fields=["subject"], name="co_subject_idx"),
        ),
        migrations.AddIndex(
            model_name="courseoffering",
            index=models.Index(fields=["slug"], name="co_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="classgroup",
            index=models.Index(fields=["institution", "status"], name="cg_inst_status_idx"),
        ),
        migrations.AddIndex(
            model_name="classgroup",
            index=models.Index(fields=["course_offering", "status"], name="cg_co_status_idx"),
        ),
        migrations.AddIndex(
            model_name="classgroup",
            index=models.Index(fields=["slug"], name="cg_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="teachingassignment",
            index=models.Index(fields=["institution", "status"], name="ta_inst_status_idx"),
        ),
        migrations.AddIndex(
            model_name="teachingassignment",
            index=models.Index(fields=["teacher", "status"], name="ta_teacher_status_idx"),
        ),
        migrations.AddIndex(
            model_name="teachingassignment",
            index=models.Index(fields=["class_group", "status"], name="ta_cg_status_idx"),
        ),
        migrations.AddIndex(
            model_name="teachingassignment",
            index=models.Index(fields=["course_offering", "status"], name="ta_co_status_idx"),
        ),
        migrations.AddIndex(
            model_name="usercapability",
            index=models.Index(fields=["user", "capability_code"], name="uc_user_cap_idx"),
        ),
        migrations.AddIndex(
            model_name="usercapability",
            index=models.Index(fields=["institution", "capability_code"], name="uc_inst_cap_idx"),
        ),
        # Add constraints
        migrations.AddConstraint(
            model_name="usercapability",
            constraint=models.UniqueConstraint(fields=["user", "institution", "capability_code"], name="unique_user_institution_capability"),
        ),
        migrations.AddConstraint(
            model_name="teachingassignment",
            constraint=models.UniqueConstraint(fields=["teacher", "class_group", "effective_from"], name="unique_teacher_class_effective_from"),
        ),
        migrations.AddConstraint(
            model_name="classgroup",
            constraint=models.UniqueConstraint(fields=["course_offering", "slug"], name="unique_cg_co_slug"),
        ),
        migrations.AddConstraint(
            model_name="classgroup",
            constraint=models.UniqueConstraint(fields=["course_offering", "name"], name="unique_cg_co_name"),
        ),
        migrations.AddConstraint(
            model_name="courseoffering",
            constraint=models.UniqueConstraint(fields=["programme", "academic_period", "subject"], name="unique_co_programme_period_subject"),
        ),
        migrations.AddConstraint(
            model_name="courseoffering",
            constraint=models.UniqueConstraint(fields=["programme", "slug"], name="unique_co_programme_slug"),
        ),
        migrations.AddConstraint(
            model_name="programme",
            constraint=models.UniqueConstraint(fields=["academic_unit", "slug"], name="unique_programme_unit_slug"),
        ),
        migrations.AddConstraint(
            model_name="programme",
            constraint=models.UniqueConstraint(fields=["academic_unit", "name"], name="unique_programme_unit_name"),
        ),
        migrations.AddConstraint(
            model_name="academicperiod",
            constraint=models.UniqueConstraint(fields=["educational_organization", "slug"], name="unique_acad_period_org_slug"),
        ),
        migrations.AddConstraint(
            model_name="academicperiod",
            constraint=models.UniqueConstraint(fields=["educational_organization", "name"], name="unique_acad_period_org_name"),
        ),
        migrations.AddConstraint(
            model_name="academicperiod",
            constraint=models.CheckConstraint(condition=models.Q(ends_at__gt=models.F("starts_at")), name="acad_period_end_after_start"),
        ),
        migrations.AddConstraint(
            model_name="academicunit",
            constraint=models.UniqueConstraint(fields=["educational_organization", "slug"], name="unique_acad_unit_org_slug"),
        ),
        migrations.AddConstraint(
            model_name="academicunit",
            constraint=models.UniqueConstraint(fields=["educational_organization", "name"], name="unique_acad_unit_org_name"),
        ),
        migrations.AddConstraint(
            model_name="educationalorganization",
            constraint=models.UniqueConstraint(fields=["institution", "slug"], name="unique_edu_org_institution_slug"),
        ),
        migrations.AddConstraint(
            model_name="educationalorganization",
            constraint=models.UniqueConstraint(fields=["institution", "name"], name="unique_edu_org_institution_name"),
        ),
    ]