import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("self_study", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="CurriculumAuthority",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("canonical_key", models.SlugField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("authority_type", models.CharField(choices=[("GOVERNMENT", "Government"), ("NATIONAL_CURRICULUM_BODY", "National curriculum body"), ("ACCREDITATION_BODY", "Accreditation body"), ("PROFESSIONAL_BODY", "Professional body"), ("QUALIFICATION_PROVIDER", "Qualification provider"), ("ACCREDITED_INSTITUTION", "Accredited institution"), ("APPROVED_PUBLISHER", "Approved publisher"), ("OPEN_EDUCATION_PROVIDER", "Open education provider"), ("ABBOT_CURATED", "Abbot curated"), ("LEARNER_SUPPLIED", "Learner supplied")], max_length=48)),
                ("jurisdictions", models.JSONField(blank=True, default=list)),
                ("canonical_domain", models.CharField(blank=True, max_length=255)),
                ("verification_status", models.CharField(choices=[("UNVERIFIED", "Unverified"), ("PENDING", "Pending"), ("VERIFIED", "Verified"), ("REJECTED", "Rejected"), ("SUSPENDED", "Suspended")], default="UNVERIFIED", max_length=16)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("SUSPENDED", "Suspended"), ("ARCHIVED", "Archived")], default="ACTIVE", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="curriculum_authorities", to="users.institution")),
                ("verified_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="verified_curriculum_authorities", to="users.user")),
            ],
            options={"db_table": "self_study_curriculum_authority"},
        ),
        migrations.CreateModel(
            name="CurriculumReference",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("canonical_key", models.SlugField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("subject_area", models.CharField(max_length=255)),
                ("source_classification", models.CharField(choices=[("LEARNER_SUPPLIED_OFFICIAL", "Learner supplied official"), ("INSTITUTION_OR_QUALIFICATION", "Institution or qualification"), ("NATIONAL_OR_REGIONAL", "National or regional"), ("PROFESSIONAL_OR_ACCREDITATION", "Professional or accreditation"), ("CURATED_REFERENCE", "Curated reference"), ("COMPOSITE", "Composite")], max_length=48)),
                ("jurisdiction", models.CharField(blank=True, max_length=64)),
                ("education_stage", models.CharField(blank=True, max_length=64)),
                ("qualification_type", models.CharField(blank=True, max_length=64)),
                ("credential_identifier", models.CharField(blank=True, max_length=255)),
                ("language", models.CharField(max_length=16)),
                ("delivery_context", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("SUSPENDED", "Suspended"), ("ARCHIVED", "Archived")], default="ACTIVE", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("authority", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="curricula", to="self_study.curriculumauthority")),
                ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="curriculum_references", to="users.institution")),
            ],
            options={"db_table": "self_study_curriculum_reference"},
        ),
        migrations.AddConstraint(
            model_name="curriculumreference",
            constraint=models.UniqueConstraint(fields=("tenant", "canonical_key"), name="self_study_curriculum_key_tenant_unique"),
        ),
        migrations.AddConstraint(
            model_name="curriculumreference",
            constraint=models.UniqueConstraint(condition=models.Q(tenant__isnull=True), fields=("canonical_key",), name="self_study_global_curriculum_key_unique"),
        ),
        migrations.CreateModel(
            name="CurriculumVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version_label", models.CharField(max_length=64)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_until", models.DateField(blank=True, null=True)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("UNDER_REVIEW", "Under review"), ("ACTIVE", "Active"), ("SUPERSEDED", "Superseded"), ("WITHDRAWN", "Withdrawn"), ("SUSPENDED", "Suspended")], default="DRAFT", max_length=16)),
                ("canonical_source_uri", models.URLField(max_length=2048)),
                ("source_document_id", models.UUIDField(blank=True, null=True)),
                ("content_hash", models.CharField(max_length=128)),
                ("licence_identifier", models.CharField(max_length=128)),
                ("licence_uri", models.URLField(blank=True, max_length=2048)),
                ("provenance_status", models.CharField(choices=[("COMPLETE", "Complete"), ("INCOMPLETE", "Incomplete"), ("CONFLICTING", "Conflicting"), ("UNVERIFIED", "Unverified")], default="INCOMPLETE", max_length=16)),
                ("language", models.CharField(max_length=16)),
                ("official_translation_languages", models.JSONField(blank=True, default=list)),
                ("generated_translation_permitted", models.BooleanField(default=False)),
                ("jurisdiction", models.CharField(blank=True, max_length=64)),
                ("education_stage", models.CharField(blank=True, max_length=64)),
                ("qualification_type", models.CharField(blank=True, max_length=64)),
                ("credential_identifier", models.CharField(blank=True, max_length=255)),
                ("subject_taxonomy", models.JSONField(blank=True, default=list)),
                ("target_outcomes_summary", models.TextField(blank=True)),
                ("entry_expectations_summary", models.TextField(blank=True)),
                ("estimated_duration_hours", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_curriculum_versions", to="users.user")),
                ("curriculum_reference", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="versions", to="self_study.curriculumreference")),
                ("supersedes", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="superseded_by", to="self_study.curriculumversion")),
            ],
            options={"db_table": "self_study_curriculum_version"},
        ),
        migrations.AddConstraint(
            model_name="curriculumversion",
            constraint=models.UniqueConstraint(fields=("curriculum_reference", "version_label"), name="self_study_curriculum_version_label_unique"),
        ),
        migrations.AddField(
            model_name="curriculumreference",
            name="current_version",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="self_study.curriculumversion"),
        ),
        migrations.CreateModel(
            name="CurriculumResolutionAttempt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("intent_version", models.PositiveIntegerField()),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("EVALUATING", "Evaluating"), ("SELECTED", "Selected"), ("AWAITING_APPROVAL", "Awaiting approval"), ("FAILED", "Failed"), ("CANCELLED", "Cancelled"), ("SUPERSEDED", "Superseded")], default="PENDING", max_length=24)),
                ("goal_snapshot", models.TextField()),
                ("target_credential", models.CharField(blank=True, max_length=255)),
                ("preferred_authority", models.CharField(blank=True, max_length=255)),
                ("jurisdiction", models.CharField(blank=True, max_length=64)),
                ("preferred_language", models.CharField(max_length=16)),
                ("requested_depth", models.CharField(max_length=32)),
                ("education_context", models.CharField(blank=True, max_length=64)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("algorithm_version", models.CharField(max_length=32)),
                ("registry_snapshot_identifier", models.CharField(blank=True, max_length=128)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("intent", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="curriculum_resolution_attempts", to="self_study.selfstudyintent")),
                ("policy_snapshot", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="curriculum_resolution_attempts", to="self_study.effectivelearningpolicysnapshot")),
                ("requested_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="curriculum_resolution_attempts", to="users.user")),
                ("requested_version", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="requested_by_attempts", to="self_study.curriculumversion")),
            ],
            options={"db_table": "self_study_curriculum_resolution_attempt"},
        ),
        migrations.AddConstraint(
            model_name="curriculumresolutionattempt",
            constraint=models.UniqueConstraint(fields=("intent", "intent_version", "algorithm_version"), name="self_study_one_resolution_per_intent_version"),
        ),
        migrations.AddConstraint(
            model_name="curriculumresolutionattempt",
            constraint=models.UniqueConstraint(fields=("intent", "idempotency_key"), name="self_study_resolution_idempotency_unique"),
        ),
        migrations.CreateModel(
            name="CurriculumResolutionCandidate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("hierarchy_rank", models.PositiveSmallIntegerField()),
                ("eligibility", models.CharField(choices=[("ELIGIBLE", "Eligible"), ("INELIGIBLE", "Ineligible"), ("REQUIRES_REVIEW", "Requires review")], max_length=24)),
                ("match_classification", models.CharField(choices=[("EXACT", "Exact"), ("STRONG", "Strong"), ("PARTIAL", "Partial"), ("WEAK", "Weak"), ("INCOMPATIBLE", "Incompatible")], max_length=16)),
                ("language_disposition", models.CharField(choices=[("NATIVE_LANGUAGE", "Native language"), ("OFFICIAL_TRANSLATION", "Official translation"), ("GENERATED_TRANSLATION_REQUIRED", "Generated translation required")], max_length=40)),
                ("score_components", models.JSONField(default=dict)),
                ("total_score", models.DecimalField(decimal_places=2, max_digits=6)),
                ("confidence", models.DecimalField(decimal_places=4, max_digits=5)),
                ("requires_approval", models.BooleanField(default=False)),
                ("rejection_reasons", models.JSONField(blank=True, default=list)),
                ("version_status_snapshot", models.CharField(max_length=16)),
                ("authority_verification_snapshot", models.CharField(max_length=16)),
                ("evaluated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("attempt", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="candidates", to="self_study.curriculumresolutionattempt")),
                ("curriculum_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="resolution_candidates", to="self_study.curriculumversion")),
            ],
            options={"db_table": "self_study_curriculum_resolution_candidate"},
        ),
        migrations.AddConstraint(
            model_name="curriculumresolutioncandidate",
            constraint=models.UniqueConstraint(fields=("attempt", "curriculum_version"), name="self_study_resolution_candidate_unique"),
        ),
        migrations.CreateModel(
            name="CurriculumSelectionDecision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("decision_type", models.CharField(choices=[("AUTOMATIC_SELECTION", "Automatic selection"), ("LEARNER_CONFIRMED_SELECTION", "Learner confirmed selection"), ("INSTITUTIONAL_SELECTION", "Institutional selection"), ("INSTITUTIONAL_OVERRIDE", "Institutional override"), ("COMPOSITE_PROPOSED", "Composite proposed")], max_length=40)),
                ("hierarchy_rank", models.PositiveSmallIntegerField()),
                ("match_classification", models.CharField(choices=[("EXACT", "Exact"), ("STRONG", "Strong"), ("PARTIAL", "Partial"), ("WEAK", "Weak"), ("INCOMPATIBLE", "Incompatible")], max_length=16)),
                ("language_disposition", models.CharField(choices=[("NATIVE_LANGUAGE", "Native language"), ("OFFICIAL_TRANSLATION", "Official translation"), ("GENERATED_TRANSLATION_REQUIRED", "Generated translation required")], max_length=40)),
                ("confidence", models.DecimalField(decimal_places=4, max_digits=5)),
                ("score_components", models.JSONField(default=dict)),
                ("reason_codes", models.JSONField(default=list)),
                ("override_reason", models.TextField(blank=True)),
                ("requires_approval", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("algorithm_version", models.CharField(max_length=32)),
                ("registry_snapshot_identifier", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="approved_curriculum_selections", to="users.user")),
                ("attempt", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="selection", to="self_study.curriculumresolutionattempt")),
                ("curriculum_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="selection_decisions", to="self_study.curriculumversion")),
                ("intent", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="curriculum_selections", to="self_study.selfstudyintent")),
            ],
            options={"db_table": "self_study_curriculum_selection_decision"},
        ),
        migrations.CreateModel(
            name="CompositeCurriculumProposal",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("PROPOSED", "Proposed"), ("APPROVED", "Approved"), ("REJECTED", "Rejected"), ("INVALIDATED", "Invalidated")], default="PROPOSED", max_length=16)),
                ("rationale_codes", models.JSONField(default=list)),
                ("requires_approval", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="approved_composite_curricula", to="users.user")),
                ("attempt", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="composite_proposal", to="self_study.curriculumresolutionattempt")),
            ],
            options={"db_table": "self_study_composite_curriculum_proposal"},
        ),
        migrations.CreateModel(
            name="CompositeCurriculumComponent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("PRIMARY", "Primary"), ("PREREQUISITE", "Prerequisite"), ("SUPPLEMENTARY", "Supplementary"), ("SPECIALIZATION", "Specialization"), ("ASSESSMENT_STANDARD", "Assessment standard")], max_length=24)),
                ("priority", models.PositiveSmallIntegerField()),
                ("scope_description", models.TextField()),
                ("curriculum_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="composite_components", to="self_study.curriculumversion")),
                ("proposal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="components", to="self_study.compositecurriculumproposal")),
            ],
            options={"db_table": "self_study_composite_curriculum_component"},
        ),
        migrations.AddConstraint(
            model_name="compositecurriculumcomponent",
            constraint=models.UniqueConstraint(fields=("proposal", "curriculum_version"), name="self_study_composite_component_unique"),
        ),
        migrations.AddConstraint(
            model_name="compositecurriculumcomponent",
            constraint=models.UniqueConstraint(fields=("proposal", "priority"), name="self_study_composite_priority_unique"),
        ),
        migrations.AddField(
            model_name="curriculumresolutionfailure",
            name="algorithm_version",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="curriculumresolutionfailure",
            name="attempt",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="resolution_failure", to="self_study.curriculumresolutionattempt"),
        ),
        migrations.AddField(
            model_name="curriculumresolutionfailure",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="curriculumresolutionfailure",
            name="policy_snapshot",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="curriculum_resolution_failures", to="self_study.effectivelearningpolicysnapshot"),
        ),
        migrations.AddField(
            model_name="curriculumresolutionfailure",
            name="registry_snapshot_identifier",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
