# Generated by Django 5.2.16 on 2026-07-20 20:46

import apps.self_study.graph_models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("self_study", "0002_curriculum_registry_and_resolver"),
        ("users", "0004_alter_institution_institution_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CurriculumGraph",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("BUILDING", "Building"),
                            ("VALIDATING", "Validating"),
                            ("READY_FOR_PUBLICATION", "Ready for publication"),
                            ("PUBLISHED", "Published"),
                            ("BLOCKED", "Blocked"),
                            ("SUPERSEDED", "Superseded"),
                            ("INVALIDATED", "Invalidated"),
                        ],
                        default="DRAFT",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "composite_proposal",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_graph",
                        to="self_study.compositecurriculumproposal",
                    ),
                ),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_graphs",
                        to="self_study.selfstudyintent",
                    ),
                ),
                (
                    "selection_decision",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_graph",
                        to="self_study.curriculumselectiondecision",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_graphs",
                        to="users.institution",
                    ),
                ),
            ],
            options={
                "db_table": "self_study_curriculum_graph",
            },
        ),
        migrations.CreateModel(
            name="CurriculumGraphVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("BUILDING", "Building"),
                            ("VALIDATING", "Validating"),
                            ("VALID", "Valid"),
                            ("INVALID", "Invalid"),
                            ("PUBLISHED", "Published"),
                            ("SUPERSEDED", "Superseded"),
                            ("INVALIDATED", "Invalidated"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("source_selection_fingerprint", models.CharField(max_length=128)),
                ("graph_fingerprint", models.CharField(blank=True, max_length=128)),
                ("builder_algorithm_version", models.CharField(max_length=32)),
                ("validation_algorithm_version", models.CharField(max_length=32)),
                ("stable_key_algorithm_version", models.CharField(max_length=32)),
                ("source_language", models.CharField(max_length=16)),
                (
                    "construction_method",
                    models.CharField(
                        choices=[
                            ("STRUCTURED_IMPORT", "Structured import"),
                            ("GOVERNED_EXTRACTION", "Governed extraction"),
                            ("CURATED_AUTHORING", "Curated authoring"),
                            ("COMPOSITE_ASSEMBLY", "Composite assembly"),
                        ],
                        max_length=32,
                    ),
                ),
                ("node_count", models.PositiveIntegerField(default=0)),
                ("edge_count", models.PositiveIntegerField(default=0)),
                ("root_count", models.PositiveIntegerField(default=0)),
                ("outcome_count", models.PositiveIntegerField(default=0)),
                ("validation_summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("invalidated_at", models.DateTimeField(blank=True, null=True)),
                ("invalidation_reason", models.CharField(blank=True, max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_curriculum_graph_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="self_study.curriculumgraph",
                    ),
                ),
                (
                    "invalidated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invalidated_curriculum_graph_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_curriculum_graph_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="self_study.curriculumgraphversion",
                    ),
                ),
            ],
            options={
                "db_table": "self_study_curriculum_graph_version",
            },
        ),
        migrations.CreateModel(
            name="CurriculumGraphValidationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("algorithm_version", models.CharField(max_length=32)),
                ("graph_fingerprint", models.CharField(max_length=128)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "graph_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validation_runs",
                        to="self_study.curriculumgraphversion",
                    ),
                ),
            ],
            options={
                "db_table": "self_study_curriculum_graph_validation_run",
            },
        ),
        migrations.CreateModel(
            name="CurriculumGraphSpecificationRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payload", models.JSONField()),
                ("specification_checksum", models.CharField(max_length=128)),
                ("producer", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_graph_specifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "graph_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="specification",
                        to="self_study.curriculumgraphversion",
                    ),
                ),
            ],
            options={
                "db_table": "self_study_curriculum_graph_specification",
            },
        ),
        migrations.AddField(
            model_name="curriculumgraph",
            name="current_version",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="self_study.curriculumgraphversion",
            ),
        ),
        migrations.CreateModel(
            name="CurriculumEdge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("stable_key", models.CharField(max_length=128)),
                (
                    "edge_type",
                    models.CharField(
                        choices=[
                            ("PART_OF", "Part of"),
                            ("REQUIRES", "Requires"),
                            ("SATISFIES", "Satisfies"),
                            ("ASSESSED_BY", "Assessed by"),
                            ("PRECEDES", "Precedes"),
                            ("EQUIVALENT_TO", "Equivalent to"),
                            ("SPECIALIZES", "Specializes"),
                            ("BRIDGES_TO", "Bridges to"),
                            ("CONFLICTS_WITH", "Conflicts with"),
                        ],
                        max_length=24,
                    ),
                ),
                ("ordinal", models.PositiveIntegerField()),
                (
                    "requirement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REQUIRED", "Required"),
                            ("RECOMMENDED", "Recommended"),
                            ("OPTIONAL", "Optional"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "strength",
                    models.DecimalField(decimal_places=4, default=1, max_digits=5),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_curriculum_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="graph_edges",
                        to="self_study.curriculumversion",
                    ),
                ),
                (
                    "graph_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges",
                        to="self_study.curriculumgraphversion",
                    ),
                ),
            ],
            options={
                "db_table": "self_study_curriculum_edge",
            },
            bases=(
                apps.self_study.graph_models.ImmutableGraphContentMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="CurriculumNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("stable_key", models.CharField(max_length=128)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("CURRICULUM_ROOT", "Curriculum root"),
                            ("STAGE", "Stage"),
                            ("OUTCOME", "Outcome"),
                            ("MODULE", "Module"),
                            ("TOPIC", "Topic"),
                            ("CONCEPT", "Concept"),
                            ("COMPETENCY", "Competency"),
                            ("ASSESSMENT_OBJECTIVE", "Assessment objective"),
                            ("EXTERNAL_PREREQUISITE", "External prerequisite"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("ordinal", models.PositiveIntegerField()),
                ("depth", models.PositiveIntegerField(default=0)),
                ("authority_namespace", models.CharField(max_length=255)),
                ("external_identifier", models.CharField(blank=True, max_length=255)),
                (
                    "external_prerequisite_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UNRESOLVED", "Unresolved"),
                            (
                                "MATCHED_TO_REGISTERED_NODE",
                                "Matched to registered node",
                            ),
                            (
                                "REQUIRES_CURRICULUM_EXTENSION",
                                "Requires curriculum extension",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "graph_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="self_study.curriculumgraphversion",
                    ),
                ),
                (
                    "source_curriculum_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="graph_nodes",
                        to="self_study.curriculumversion",
                    ),
                ),
            ],
            options={
                "db_table": "self_study_curriculum_node",
            },
            bases=(
                apps.self_study.graph_models.ImmutableGraphContentMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="CurriculumGraphFinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("BLOCKER", "Blocker"),
                        ],
                        max_length=16,
                    ),
                ),
                ("message", models.CharField(max_length=500)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                (
                    "edge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validation_findings",
                        to="self_study.curriculumedge",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolved_graph_findings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="self_study.curriculumgraphvalidationrun",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validation_findings",
                        to="self_study.curriculumnode",
                    ),
                ),
                (
                    "related_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="related_validation_findings",
                        to="self_study.curriculumnode",
                    ),
                ),
            ],
            options={
                "db_table": "self_study_curriculum_graph_finding",
            },
        ),
        migrations.CreateModel(
            name="CurriculumGraphCitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_document_id", models.UUIDField(blank=True, null=True)),
                ("source_uri", models.URLField(max_length=2048)),
                ("source_locator", models.JSONField(default=dict)),
                ("normalized_excerpt", models.TextField(blank=True)),
                ("source_language", models.CharField(max_length=16)),
                (
                    "citation_type",
                    models.CharField(
                        choices=[
                            ("EXPLICIT", "Explicit"),
                            ("STRUCTURAL", "Structural"),
                            ("DERIVED", "Derived"),
                            ("CURATED", "Curated"),
                            ("COMPOSITE_ALIGNMENT", "Composite alignment"),
                        ],
                        max_length=32,
                    ),
                ),
                ("confidence", models.DecimalField(decimal_places=4, max_digits=5)),
                ("rationale", models.TextField(blank=True)),
                ("builder_algorithm_version", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "curriculum_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="graph_citations",
                        to="self_study.curriculumversion",
                    ),
                ),
                (
                    "edge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="self_study.curriculumedge",
                    ),
                ),
                (
                    "graph_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="self_study.curriculumgraphversion",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="self_study.curriculumnode",
                    ),
                ),
            ],
            options={
                "db_table": "self_study_curriculum_graph_citation",
            },
            bases=(
                apps.self_study.graph_models.ImmutableGraphContentMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="curriculumedge",
            name="source_node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_edges",
                to="self_study.curriculumnode",
            ),
        ),
        migrations.AddField(
            model_name="curriculumedge",
            name="target_node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_edges",
                to="self_study.curriculumnode",
            ),
        ),
        migrations.AddIndex(
            model_name="curriculumgraphversion",
            index=models.Index(
                fields=["graph", "status"], name="ssi_graph_version_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumgraphversion",
            constraint=models.UniqueConstraint(
                fields=("graph", "version_number"),
                name="self_study_graph_version_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="curriculumgraphvalidationrun",
            index=models.Index(
                fields=["graph_version", "status"], name="ssi_graph_validation_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumgraphvalidationrun",
            constraint=models.UniqueConstraint(
                fields=("graph_version", "graph_fingerprint", "algorithm_version"),
                name="self_study_graph_validation_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumgraph",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("composite_proposal__isnull", True),
                        ("selection_decision__isnull", False),
                    ),
                    models.Q(
                        ("composite_proposal__isnull", False),
                        ("selection_decision__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="self_study_graph_one_authoritative_source",
            ),
        ),
        migrations.AddIndex(
            model_name="curriculumnode",
            index=models.Index(
                fields=["graph_version", "node_type"], name="ssi_graph_node_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="curriculumnode",
            index=models.Index(
                fields=["graph_version", "ordinal"], name="ssi_graph_node_order_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumnode",
            constraint=models.UniqueConstraint(
                fields=("graph_version", "stable_key"),
                name="self_study_graph_node_key_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumnode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_identifier", ""), _negated=True),
                fields=("graph_version", "authority_namespace", "external_identifier"),
                name="self_study_graph_external_id_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="curriculumgraphfinding",
            index=models.Index(
                fields=["validation_run", "severity"], name="ssi_graph_finding_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="curriculumgraphcitation",
            index=models.Index(
                fields=["graph_version", "citation_type"],
                name="ssi_graph_citation_type_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumgraphcitation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("edge__isnull", True), ("node__isnull", False)),
                    models.Q(("edge__isnull", False), ("node__isnull", True)),
                    _connector="OR",
                ),
                name="self_study_graph_citation_one_target",
            ),
        ),
        migrations.AddIndex(
            model_name="curriculumedge",
            index=models.Index(
                fields=["graph_version", "edge_type"], name="ssi_graph_edge_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="curriculumedge",
            index=models.Index(
                fields=["graph_version", "source_node"],
                name="ssi_graph_edge_source_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="curriculumedge",
            index=models.Index(
                fields=["graph_version", "target_node"],
                name="ssi_graph_edge_target_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumedge",
            constraint=models.UniqueConstraint(
                fields=("graph_version", "stable_key"),
                name="self_study_graph_edge_key_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumedge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_node", models.F("target_node")), _negated=True
                ),
                name="self_study_graph_no_self_edge",
            ),
        ),
    ]
