# Generated by Django 5.2.16 on 2026-07-20 21:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("self_study", "0003_curriculumgraph_curriculumgraphversion_and_more"),
        ("users", "0004_alter_institution_institution_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosticBlueprint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("graph_fingerprint", models.CharField(max_length=128)),
                ("algorithm_version", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("VALIDATING", "Validating"),
                            ("VALID", "Valid"),
                            ("INVALID", "Invalid"),
                            ("PUBLISHED", "Published"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("minimum_items", models.PositiveSmallIntegerField(default=8)),
                ("maximum_items", models.PositiveSmallIntegerField(default=15)),
                (
                    "target_precision",
                    models.DecimalField(decimal_places=4, default=0.25, max_digits=5),
                ),
                ("stopping_policy", models.JSONField(default=dict)),
                ("competency_domain_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_diagnostic_blueprints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "graph_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnostic_blueprint",
                        to="self_study.curriculumgraphversion",
                    ),
                ),
            ],
            options={
                "db_table": "self_study_diagnostic_blueprint",
            },
        ),
        migrations.CreateModel(
            name="DiagnosticCompetencyEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estimate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "uncertainty",
                    models.DecimalField(decimal_places=4, default=1, max_digits=5),
                ),
                ("evidence_count", models.PositiveSmallIntegerField(default=0)),
                ("correct_evidence_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "incorrect_evidence_count",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNOBSERVED", "Unobserved"),
                            ("TENTATIVE", "Tentative"),
                            ("DEMONSTRATED", "Demonstrated"),
                            ("NOT_DEMONSTRATED", "Not demonstrated"),
                            ("UNCERTAIN", "Uncertain"),
                            ("NOT_DIAGNOSABLE", "Not diagnosable"),
                        ],
                        default="UNOBSERVED",
                        max_length=24,
                    ),
                ),
                ("algorithm_version", models.CharField(max_length=40)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "graph_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnostic_estimates",
                        to="self_study.curriculumnode",
                    ),
                ),
            ],
            options={
                "db_table": "self_study_diagnostic_estimate",
            },
        ),
        migrations.CreateModel(
            name="DiagnosticItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("stable_key", models.CharField(max_length=128)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("SINGLE_CHOICE", "Single choice"),
                            ("MULTIPLE_CHOICE", "Multiple choice"),
                            ("NUMERIC", "Numeric"),
                            ("SHORT_STRUCTURED", "Short structured"),
                            ("ORDERING", "Ordering"),
                            ("MATCHING", "Matching"),
                        ],
                        max_length=24,
                    ),
                ),
                ("prompt", models.TextField()),
                ("response_schema", models.JSONField()),
                ("scoring_specification", models.JSONField()),
                ("difficulty_band", models.PositiveSmallIntegerField(default=2)),
                ("discrimination_band", models.PositiveSmallIntegerField(default=2)),
                ("language", models.CharField(max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("VALIDATING", "Validating"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("RETIRED", "Retired"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("source", models.CharField(max_length=128)),
                (
                    "generation_method",
                    models.CharField(default="CURATED", max_length=32),
                ),
                ("review_status", models.CharField(default="VALIDATED", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="self_study.diagnosticblueprint",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_diagnostic_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "self_study_diagnostic_item",
            },
        ),
        migrations.CreateModel(
            name="DiagnosticItemNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=4, default=1, max_digits=5),
                ),
                (
                    "graph_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="self_study.curriculumnode",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="self_study.diagnosticitem",
                    ),
                ),
            ],
            options={
                "db_table": "self_study_diagnostic_item_node",
            },
        ),
        migrations.AddField(
            model_name="diagnosticitem",
            name="graph_nodes",
            field=models.ManyToManyField(
                related_name="diagnostic_items",
                through="self_study.DiagnosticItemNode",
                to="self_study.curriculumnode",
            ),
        ),
        migrations.CreateModel(
            name="DiagnosticItemPresentation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField()),
                ("selection_reason_code", models.CharField(max_length=64)),
                ("presented_at", models.DateTimeField(auto_now_add=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PRESENTED", "Presented"),
                            ("ANSWERED", "Answered"),
                            ("SKIPPED", "Skipped"),
                            ("EXPIRED", "Expired"),
                            ("INVALIDATED", "Invalidated"),
                        ],
                        default="PRESENTED",
                        max_length=16,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="presentations",
                        to="self_study.diagnosticitem",
                    ),
                ),
            ],
            options={
                "db_table": "self_study_diagnostic_presentation",
            },
        ),
        migrations.CreateModel(
            name="DiagnosticPlacementProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("graph_fingerprint", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FINAL", "Final"),
                            ("INCONCLUSIVE", "Inconclusive"),
                            ("SUPERSEDED", "Superseded"),
                            ("INVALIDATED", "Invalidated"),
                        ],
                        max_length=16,
                    ),
                ),
                ("algorithm_version", models.CharField(max_length=40)),
                ("profile_fingerprint", models.CharField(max_length=128, unique=True)),
                (
                    "overall_confidence",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                ("thresholds", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "graph_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnostic_profiles",
                        to="self_study.curriculumgraphversion",
                    ),
                ),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnostic_profiles",
                        to="self_study.selfstudyintent",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnostic_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="self_study.diagnosticplacementprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnostic_profiles",
                        to="users.institution",
                    ),
                ),
            ],
            options={
                "db_table": "self_study_diagnostic_profile",
            },
        ),
        migrations.CreateModel(
            name="DiagnosticPlacementNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("FRONTIER", "Starting frontier"),
                            ("DEMONSTRATED", "Demonstrated"),
                            ("GAP", "Gap"),
                            ("UNCERTAIN", "Uncertain"),
                            ("NOT_DIAGNOSABLE", "Not diagnosable"),
                            ("EXTERNAL_PREREQUISITE", "External prerequisite"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "estimate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profile_memberships",
                        to="self_study.diagnosticcompetencyestimate",
                    ),
                ),
                (
                    "graph_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnostic_placements",
                        to="self_study.curriculumnode",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classified_nodes",
                        to="self_study.diagnosticplacementprofile",
                    ),
                ),
            ],
            options={
                "db_table": "self_study_diagnostic_profile_node",
            },
        ),
        migrations.CreateModel(
            name="EntryDiagnostic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("graph_fingerprint", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("READY", "Ready"),
                            ("IN_PROGRESS", "In progress"),
                            ("EVALUATING", "Evaluating"),
                            ("COMPLETED", "Completed"),
                            ("INCONCLUSIVE", "Inconclusive"),
                            ("CHALLENGED", "Challenged"),
                            ("SUPERSEDED", "Superseded"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="READY",
                        max_length=16,
                    ),
                ),
                ("purpose_disclosed_at", models.DateTimeField()),
                ("algorithm_version", models.CharField(max_length=40)),
                ("item_bank_version", models.CharField(max_length=40)),
                ("maximum_items", models.PositiveSmallIntegerField()),
                ("minimum_items", models.PositiveSmallIntegerField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("current_sequence", models.PositiveSmallIntegerField(default=0)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnostics",
                        to="self_study.diagnosticblueprint",
                    ),
                ),
                (
                    "graph_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entry_diagnostics",
                        to="self_study.curriculumgraphversion",
                    ),
                ),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entry_diagnostics",
                        to="self_study.selfstudyintent",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entry_diagnostics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entry_diagnostics",
                        to="self_study.effectivelearningpolicysnapshot",
                    ),
                ),
                (
                    "prior_diagnostic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retakes",
                        to="self_study.entrydiagnostic",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entry_diagnostics",
                        to="users.institution",
                    ),
                ),
            ],
            options={
                "db_table": "self_study_entry_diagnostic",
            },
        ),
        migrations.CreateModel(
            name="DiagnosticResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("response_payload", models.JSONField()),
                ("response_hash", models.CharField(max_length=128)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scoring_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SCORED", "Scored"),
                            ("INVALID", "Invalid"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("score_result", models.JSONField(default=dict)),
                ("scoring_algorithm_version", models.CharField(max_length=40)),
                ("idempotency_key", models.CharField(max_length=128)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="self_study.diagnosticitem",
                    ),
                ),
                (
                    "presentation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="response",
                        to="self_study.diagnosticitempresentation",
                    ),
                ),
                (
                    "diagnostic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="self_study.entrydiagnostic",
                    ),
                ),
            ],
            options={
                "db_table": "self_study_diagnostic_response",
            },
        ),
        migrations.AddField(
            model_name="diagnosticplacementprofile",
            name="diagnostic",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="placement_profile",
                to="self_study.entrydiagnostic",
            ),
        ),
        migrations.CreateModel(
            name="DiagnosticPlacementChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CHECKPOINT_OFFERED", "Checkpoint offered"),
                            ("RETAKE_OFFERED", "Retake offered"),
                            ("RESOLVED", "Resolved"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="OPEN",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="challenges",
                        to="self_study.diagnosticplacementprofile",
                    ),
                ),
                (
                    "diagnostic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="challenges",
                        to="self_study.entrydiagnostic",
                    ),
                ),
            ],
            options={
                "db_table": "self_study_diagnostic_challenge",
            },
        ),
        migrations.AddField(
            model_name="diagnosticitempresentation",
            name="diagnostic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="presentations",
                to="self_study.entrydiagnostic",
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcompetencyestimate",
            name="diagnostic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="estimates",
                to="self_study.entrydiagnostic",
            ),
        ),
        migrations.CreateModel(
            name="DiagnosticBlueprintNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain_key", models.CharField(max_length=128)),
                ("is_entry_candidate", models.BooleanField(default=False)),
                ("is_target_outcome", models.BooleanField(default=False)),
                ("is_diagnosticable", models.BooleanField(default=True)),
                ("exclusion_reason", models.CharField(blank=True, max_length=64)),
                ("importance", models.PositiveSmallIntegerField(default=1)),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scope_nodes",
                        to="self_study.diagnosticblueprint",
                    ),
                ),
                (
                    "graph_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnostic_blueprint_memberships",
                        to="self_study.curriculumnode",
                    ),
                ),
            ],
            options={
                "db_table": "self_study_diagnostic_blueprint_node",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("blueprint", "graph_node"),
                        name="ssi_diag_blueprint_node_unique",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="diagnosticitemnode",
            constraint=models.UniqueConstraint(
                fields=("item", "graph_node"), name="ssi_diag_item_node_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="diagnosticitem",
            constraint=models.UniqueConstraint(
                fields=("blueprint", "stable_key", "version"),
                name="ssi_diag_item_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="diagnosticplacementnode",
            constraint=models.UniqueConstraint(
                fields=("profile", "graph_node", "classification"),
                name="ssi_diag_profile_node_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="entrydiagnostic",
            index=models.Index(
                fields=["intent", "status"], name="ssi_diag_intent_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entrydiagnostic",
            index=models.Index(
                fields=["learner", "created_at"], name="ssi_diag_learner_history_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="entrydiagnostic",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["READY", "IN_PROGRESS", "EVALUATING"])
                ),
                fields=("intent",),
                name="ssi_diag_one_active_per_intent",
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosticresponse",
            index=models.Index(
                fields=["diagnostic", "submitted_at"], name="ssi_diag_response_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="diagnosticresponse",
            constraint=models.UniqueConstraint(
                fields=("diagnostic", "idempotency_key"),
                name="ssi_diag_response_idem_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosticplacementprofile",
            index=models.Index(
                fields=["graph_version", "status"], name="ssi_diag_profile_graph_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosticplacementchallenge",
            index=models.Index(
                fields=["diagnostic", "status"], name="ssi_diag_challenge_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosticitempresentation",
            index=models.Index(
                fields=["diagnostic", "status"], name="ssi_diag_present_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="diagnosticitempresentation",
            constraint=models.UniqueConstraint(
                fields=("diagnostic", "sequence"), name="ssi_diag_sequence_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="diagnosticitempresentation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PRESENTED")),
                fields=("diagnostic",),
                name="ssi_diag_one_outstanding",
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosticcompetencyestimate",
            index=models.Index(
                fields=["diagnostic", "status"], name="ssi_diag_estimate_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="diagnosticcompetencyestimate",
            constraint=models.UniqueConstraint(
                fields=("diagnostic", "graph_node"),
                name="ssi_diag_estimate_node_unique",
            ),
        ),
    ]
