import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0006_content_review_fields"),
        ("content_processing", "0005_teaching_readiness_governance"),
        ("self_study", "0006_bridge_planning"),
        ("users", "0004_alter_institution_institution_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeachingPreparationRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("bridge_plan_fingerprint", models.CharField(max_length=128)),
                ("graph_fingerprint", models.CharField(max_length=128)),
                ("coverage_fingerprint", models.CharField(max_length=128)),
                ("mapping_set_fingerprint", models.CharField(max_length=128)),
                ("input_manifest", models.JSONField()),
                ("algorithm_version", models.CharField(max_length=64)),
                ("policy_version", models.CharField(max_length=64)),
                ("role_policy_version", models.CharField(max_length=64)),
                ("retrieval_schema_version", models.CharField(max_length=64)),
                ("readiness_policy_version", models.CharField(max_length=64)),
                ("run_fingerprint", models.CharField(max_length=128)),
                ("status", models.CharField(choices=[("PENDING","Pending"),("ASSEMBLING","Assembling"),("ASSEMBLY_READY","Assembly ready"),("PUBLISHING","Publishing"),("EVALUATING_READINESS","Evaluating readiness"),("COMPLETED","Completed"),("FAILED","Failed"),("STALE","Stale"),("INVALIDATED","Invalidated"),("SUPERSEDED","Superseded")], default="PENDING", max_length=24)),
                ("stage", models.CharField(default="CREATED", max_length=32)),
                ("claim_token", models.UUIDField(blank=True, null=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("claimed_by", models.CharField(blank=True, max_length=128)),
                ("failure_code", models.CharField(blank=True, max_length=96)),
                ("failure_detail", models.CharField(blank=True, max_length=500)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("bridge_plan", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_preparation_runs", to="self_study.bridgeplan")),
                ("coverage_evaluation", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_preparation_runs", to="self_study.curriculumcoverageevaluation")),
                ("graph_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_preparation_runs", to="self_study.curriculumgraphversion")),
                ("intent", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_preparation_runs", to="self_study.selfstudyintent")),
                ("predecessor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="successors", to="self_study.teachingpreparationrun")),
                ("requested_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="requested_teaching_preparation_runs", to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_preparation_runs", to="users.institution")),
            ],
            options={"db_table": "self_study_teaching_preparation_run", "indexes": [models.Index(fields=["intent", "status"], name="ssi_teach_run_status_idx"), models.Index(fields=["bridge_plan", "status"], name="ssi_teach_run_plan_idx")], "constraints": [models.UniqueConstraint(condition=models.Q(("status__in", ["INVALIDATED", "SUPERSEDED"]), _negated=True), fields=("tenant", "run_fingerprint"), name="ssi_teach_run_fp_unique")]},
        ),
        migrations.CreateModel(
            name="TeachingPreparationManifest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("PROPOSED","Proposed"),("READY_FOR_REVIEW","Ready for review"),("APPROVED","Approved"),("PUBLISHING","Publishing"),("PUBLISHED","Published"),("READY","Ready"),("BLOCKED","Blocked"),("REJECTED","Rejected"),("STALE","Stale"),("INVALIDATED","Invalidated"),("SUPERSEDED","Superseded")], default="PROPOSED", max_length=24)),
                ("manifest_snapshot", models.JSONField()),
                ("manifest_fingerprint", models.CharField(max_length=128)),
                ("pack_set_fingerprint", models.CharField(max_length=128)),
                ("assignment_set_fingerprint", models.CharField(max_length=128)),
                ("citation_set_fingerprint", models.CharField(max_length=128)),
                ("retrieval_manifest_fingerprint", models.CharField(blank=True, max_length=128)),
                ("readiness_fingerprint", models.CharField(blank=True, max_length=128)),
                ("algorithm_version", models.CharField(max_length=64)),
                ("policy_version", models.CharField(max_length=64)),
                ("role_policy_version", models.CharField(max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_reason", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="approved_teaching_preparations", to=settings.AUTH_USER_MODEL)),
                ("bridge_plan", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_preparation_manifests", to="self_study.bridgeplan")),
                ("coverage_evaluation", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_preparation_manifests", to="self_study.curriculumcoverageevaluation")),
                ("graph_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_preparation_manifests", to="self_study.curriculumgraphversion")),
                ("intent", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_preparation_manifests", to="self_study.selfstudyintent")),
                ("predecessor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="successors", to="self_study.teachingpreparationmanifest")),
                ("rejected_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="rejected_teaching_preparations", to=settings.AUTH_USER_MODEL)),
                ("run", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="manifest", to="self_study.teachingpreparationrun")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_preparation_manifests", to="users.institution")),
            ],
            options={"db_table": "self_study_teaching_preparation_manifest", "indexes": [models.Index(fields=["intent", "status"], name="ssi_teach_manifest_status_idx")], "constraints": [models.UniqueConstraint(fields=("tenant", "manifest_fingerprint"), name="ssi_teach_manifest_fp_unique"), models.UniqueConstraint(condition=models.Q(("status", "READY")), fields=("tenant", "intent", "bridge_plan"), name="ssi_teach_one_ready_scope")]},
        ),
        migrations.CreateModel(
            name="NodeTeachingPack",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("node_type", models.CharField(max_length=32)),
                ("ordinal", models.PositiveIntegerField()),
                ("topological_layer", models.PositiveIntegerField()),
                ("bridge_disposition", models.CharField(max_length=32)),
                ("material_feasibility", models.CharField(max_length=24)),
                ("coverage_state", models.CharField(max_length=16)),
                ("status", models.CharField(choices=[("UNEVALUATED","Unevaluated"),("ASSEMBLED","Assembled"),("PARTIAL","Partial"),("BLOCKED","Blocked"),("CONFLICTING","Conflicting"),("PUBLISHED","Published"),("READY","Ready"),("STALE","Stale"),("NOT_APPLICABLE","Not applicable")], default="UNEVALUATED", max_length=24)),
                ("role_policy_snapshot", models.JSONField(default=dict)),
                ("required_role_count", models.PositiveIntegerField(default=0)),
                ("satisfied_role_count", models.PositiveIntegerField(default=0)),
                ("assignment_count", models.PositiveIntegerField(default=0)),
                ("distinct_source_count", models.PositiveIntegerField(default=0)),
                ("duplicate_cluster_count", models.PositiveIntegerField(default=0)),
                ("blocker_count", models.PositiveIntegerField(default=0)),
                ("pack_fingerprint", models.CharField(max_length=128)),
                ("bridge_node", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_packs", to="self_study.bridgeplannode")),
                ("graph_node", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_packs", to="self_study.curriculumnode")),
                ("manifest", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="node_packs", to="self_study.teachingpreparationmanifest")),
            ],
            options={"db_table": "self_study_node_teaching_pack", "indexes": [models.Index(fields=["manifest", "topological_layer", "ordinal"], name="ssi_teach_pack_order_idx")], "constraints": [models.UniqueConstraint(fields=("manifest", "bridge_node"), name="ssi_teach_pack_node_unique"), models.UniqueConstraint(fields=("manifest", "pack_fingerprint"), name="ssi_teach_pack_fp_unique")]},
        ),
        migrations.CreateModel(
            name="TeachingRetrievalManifest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(default="PENDING", max_length=24)),
                ("expected_assignment_count", models.PositiveIntegerField(default=0)),
                ("published_assignment_count", models.PositiveIntegerField(default=0)),
                ("expected_assignment_identities", models.JSONField(default=list)),
                ("published_assignment_identities", models.JSONField(default=list)),
                ("metadata_filters", models.JSONField(default=dict)),
                ("manifest_fingerprint", models.CharField(max_length=128)),
                ("verification_fingerprint", models.CharField(blank=True, max_length=128)),
                ("retrieval_schema_version", models.CharField(max_length=64)),
                ("index_version", models.CharField(default="self-study-teaching-retrieval-v1", max_length=64)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("bridge_plan", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_retrieval_manifests", to="self_study.bridgeplan")),
                ("manifest", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="retrieval_manifest", to="self_study.teachingpreparationmanifest")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_retrieval_manifests", to="users.institution")),
            ],
            options={"db_table": "self_study_teaching_retrieval_manifest", "indexes": [models.Index(fields=["bridge_plan", "status"], name="ssi_teach_retrieval_status_idx")], "constraints": [models.UniqueConstraint(fields=("tenant", "manifest_fingerprint"), name="ssi_teach_retrieval_fp_unique")]},
        ),
        migrations.CreateModel(
            name="TeachingPackResource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("classification", models.CharField(max_length=32)),
                ("role", models.CharField(choices=[("PRIMARY_EXPLANATION","Primary explanation"),("SUPPORTING_EXPLANATION","Supporting explanation"),("PREREQUISITE_SUPPORT","Prerequisite support"),("DEFINITION","Definition"),("WORKED_EXAMPLE","Worked example"),("PROCEDURE","Procedure"),("PRACTICE","Practice"),("ASSESSMENT_SUPPORT","Assessment support"),("REFERENCE","Reference"),("ENRICHMENT","Enrichment"),("CONFLICT_WARNING","Conflict warning")], max_length=32)),
                ("rank", models.PositiveSmallIntegerField()),
                ("diversity_key", models.CharField(blank=True, max_length=128)),
                ("duplicate_cluster", models.CharField(blank=True, max_length=128)),
                ("licence_disposition", models.CharField(max_length=32)),
                ("safety_disposition", models.CharField(max_length=32)),
                ("citation_snapshot", models.JSONField(default=dict)),
                ("rationale_codes", models.JSONField(default=list)),
                ("policy_version", models.CharField(max_length=64)),
                ("assignment_fingerprint", models.CharField(max_length=128)),
                ("accepted_mapping", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_assignments", to="self_study.curriculumevidencemapping")),
                ("evidence_unit", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_assignments", to="self_study.contentevidenceunit")),
                ("pack", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="resources", to="self_study.nodeteachingpack")),
                ("resource", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="self_study_teaching_assignments", to="academic.learningresource")),
                ("source_block", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_assignments", to="content_processing.extractedblock")),
                ("source_input", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_assignments", to="self_study.evidencemappingrunresource")),
            ],
            options={"db_table": "self_study_teaching_pack_resource", "indexes": [models.Index(fields=["pack", "role", "rank"], name="ssi_teach_assignment_role_idx"), models.Index(fields=["resource", "role"], name="ssi_teach_asg_resource_idx")], "constraints": [models.UniqueConstraint(fields=("pack", "accepted_mapping"), name="ssi_teach_asg_map_unique"), models.UniqueConstraint(fields=("pack", "assignment_fingerprint"), name="ssi_teach_assignment_fp_unique")]},
        ),
        migrations.CreateModel(
            name="TeachingReadinessEvaluation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("state", models.CharField(choices=[("NOT_EVALUATED","Not evaluated"),("READY","Ready"),("PARTIAL","Partial"),("BLOCKED","Blocked"),("CONFLICTING","Conflicting"),("STALE","Stale"),("INVALIDATED","Invalidated")], max_length=24)),
                ("node_results", models.JSONField(default=list)),
                ("blocker_count", models.PositiveIntegerField(default=0)),
                ("warning_count", models.PositiveIntegerField(default=0)),
                ("evaluation_fingerprint", models.CharField(max_length=128, unique=True)),
                ("policy_version", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("manifest", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="readiness_evaluations", to="self_study.teachingpreparationmanifest")),
                ("retrieval_manifest", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="readiness_evaluations", to="self_study.teachingretrievalmanifest")),
            ],
            options={"db_table": "self_study_teaching_readiness_evaluation", "indexes": [models.Index(fields=["manifest", "state"], name="ssi_teach_ready_state_idx")]},
        ),
        migrations.CreateModel(
            name="TeachingReadinessFinding",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=96)),
                ("severity", models.CharField(choices=[("INFO","Info"),("WARNING","Warning"),("BLOCKER","Blocker")], max_length=16)),
                ("blocking", models.BooleanField(default=False)),
                ("scope", models.CharField(max_length=32)),
                ("affected_identities", models.JSONField(default=list)),
                ("details", models.JSONField(default=dict)),
                ("policy_version", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("manifest", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="findings", to="self_study.teachingpreparationmanifest")),
                ("pack", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="findings", to="self_study.nodeteachingpack")),
            ],
            options={"db_table": "self_study_teaching_readiness_finding", "indexes": [models.Index(fields=["manifest", "blocking", "severity"], name="ssi_teach_finding_idx"), models.Index(fields=["code"], name="ssi_teach_finding_code_idx")]},
        ),
    ]
