from __future__ import annotations

from typing import Protocol


class ApprovalReadinessRepository(Protocol):
    def add(self, snapshot): ...
    def get(self, snapshot_id, *, for_update: bool = False): ...


class ApprovalDecisionRepository(Protocol):
    def add(self, decision): ...
    def get_idempotent(self, session_id, idempotency_key): ...


class ApprovedProjectionRepository(Protocol):
    def add(self, projection): ...
    def get(self, projection_id): ...
    def get_by_approval_version(self, proposal_id, approval_version): ...


class ApprovedSectionRepository(Protocol):
    def add_many(self, sections): ...


class ApprovedConceptRepository(Protocol):
    def add_many(self, concepts): ...
